### ISSUE TITLE
Monitor requirements with requires.io

### ISSUE THREAD

**Issue by dennissiemensma** [dennissiemensma/dsmr-reader#101]
Requires.io (https://requires.io/) keeps track of all dependencies and whether they are outdated. Seems fair enough to try.

**Comment by dennissiemensma** [comment]
It seems some dependencies are outdated already: https://requires.io/github/dennissiemensma/dsmr-reader/requirements/?branch=master

**Comment by dennissiemensma** [comment]
I've updated `django-solo`, `dropbox`, `gunicorn`, `python-dateutil` and `pytz`. I will not update `Django` as current version `1.8` is LTS, which is fine for me (and this project).

**Comment by dennissiemensma** [comment]
Tests pass, but before merging I'll deploy and test Gunicorn on production just to be sure.

**Comment by dennissiemensma** [comment]
It works, also restarted Gunicorn with a hard restart. Dropbox was updated but sync still seems to work fine.

**Comment by jeroenpeters1986** [comment]
Cool tool :) Authored by the same team that wrote ShiningPanda, the clean-virtual-env builder :D

**Comment by dennissiemensma** [comment]
Yeah it's nice, but the only downside is that it marks Django LTS as outdated (even the latest patch). Well, can't have it all :]

**Comment by jeroenpeters1986** [comment]
Difference of opinion/vision I think. Cutting edge vs long term support.
Well, as you say: can't have it all :)
