### ISSUE TITLE
Improve data export field names

### ISSUE THREAD

**Issue by WatskeBart** [dennissiemensma/dsmr-reader#132]
A hourly or daily data export generates no data. Time span is a single day on the calendar.
See screenshot.
![image](https://cloud.githubusercontent.com/assets/471361/14965802/a2e513b2-10af-11e6-9a37-1a6f51606f30.png)

**Comment by dennissiemensma** [comment]
Thanks once again for the report. Does your archive page and trends page display any data yet? (because it's based on that data)

**Comment by WatskeBart** [comment]
You're right once again :) Generated just fine when it had enough data.
Maybe add low and high to the T1 and T2 sections.

Replace this
![image](https://cloud.githubusercontent.com/assets/471361/14988463/3ac653b8-1154-11e6-960f-15909fd05b60.png)
with something like;
![image](https://cloud.githubusercontent.com/assets/471361/14988568/b7c99bae-1154-11e6-83aa-8fd7fc616547.png)

**Comment by dennissiemensma** [comment]
Thanks for the suggestion. I will add verbose names to the fields, making them much more readable.

**Comment by dennissiemensma** [comment]
Fixed in 0774dda:

- Added verbose names to model fields with gettext support.
- Exposed them in the csv exports.
- Added gettext translations for Dutch.

Merged back to dev, will be bundled with release 1.2.
