### ISSUE TITLE
Pie charts on trends page overlap their canvas

### ISSUE THREAD

**Issue by WatskeBart** [dennissiemensma/dsmr-reader#136]
Currently both pie charts (weekly and monthly) overlap their canvas.
Minor cosmetic bug.

![image](https://cloud.githubusercontent.com/assets/471361/15029379/8f617f34-124d-11e6-8e68-a844b13319c1.png)

**Comment by dennissiemensma** [comment]
Thanks for reporting, I've fixed this in 1d0c8cf by adding some padding. The element behind the canvas lacked this.
