### ISSUE TITLE
Bug/ probleem met meten van  verbruik en zonnepanelen

### ISSUE THREAD

**Issue by Gschaafsma** [dennissiemensma/dsmr-reader#145]
Dennis,

Op dit moment wordt de P1 poort uitgelezen voor het bepalen van het gebruik.
Dit is correct voor een huishouden die alleen stroom gebruikt en niet zelf opwekt.
Indien er wel zonnepanelen aanwezig zijn, dan is het verbruik zoals nu wordt weer gegeven niet correct.
Je heb nu twee variabelen die je meet, namelijk het verbruik geleverd door het net (A) en teruglevering van de zonnepanelen aan het net (B). Je mist nu het derde component namelijk het gedeelte van de opgewekte stroom die meteen weer verbruikt wordt, component C.
Voor verdere ontwikkeling van de DSMR reader heb je component C nodig: Totale opgewekte energie. 
Dan kun je het echte verbruik uitrekenen, namelijk C-B+A.

Bij het implementeren van de scripts voor uitlezen van de zonnepanelen moet je er rekening mee houden dat er verschillende scripts bestaan voor bij [Solar Edge](https://github.com/jbuehl/solaredge), [SMA](https://sbfspot.codeplex.com/) of een Hosala omvormer.

Groet,

Gert

**Comment by dennissiemensma** [comment]
Bedankt voor je input. Zoals mondeling besproken gaat dergelijke functionaliteit buiten dit project om. De kern is het uitlezen van de slimme meter en **die** waardes opslaan en plotten. Het exporteren van gemeten data naar een externe website is eigenlijk al de grens.

Je gaf zelf aan aan dat er een alternatief is om de dsmr-data beschikbaar te maken in **PVOutput.org**. Toevallig heb ik daar nog steeds een eerder/oud ticket voor staan (Data export: PVOutput #9) en die zet ik op de mogelijke lijst voor een volgende release.
Aan de API docs (http://pvoutput.org/help.html#api-spec) te zien is zowel energieverbruik als opbrengst in te lezen. Hoe dat zich exact plot in die applicatie weet ik niet, maar dat zou een mogelijkheid kunnen zijn:
* `v1	Energy Generation	No1	number	watt hours		r1`	
* `v2	Power Generation	No	number	watts		r1`	

* `v3	Energy Consumption	No	number	watt hours		r1`	
* `v4	Power Consumption	No	number	watts		r1`

Vervolg voor deze app via #9. Het direct uitlezen van de omvormer zal buiten dit project om gaan.
