### ISSUE TITLE
Push notifications for Notify My Android / Prowl (iOS)

### ISSUE THREAD

**Issue by jeroenpeters1986** [dennissiemensma/dsmr-reader#152]
DSMR Reader great for pulling information, even with customizable reports and all. I think it might also be a good addition to have just little summarized daily usage-notifications being pushed to your phone.

Since Android and iOS are the most popular mobile platforms, I'd like to propose [NotifyMyAndroid](https://www.notifymyandroid.com) (for Android) and [Prowl](https://www.prowlapp.com) (for iOS).

**Comment by dennissiemensma** [comment]
I've created a branch `152-push-notifications` for your changes. Can you try creating a pull request to that specific branch?

See https://help.github.com/articles/creating-a-pull-request/

**Comment by dennissiemensma** [comment]
After all it seems to be merged, Travis is now checking it in:
https://travis-ci.org/dennissiemensma/dsmr-reader/builds/177738832

**Comment by dennissiemensma** [comment]
I have fixed the typo you found in 9bd9bfbcf44404f91004bcb2e37ad3c95920f493

**Comment by jeroenpeters1986** [comment]
Ha, you were ahead of me, I was planning to do that tonight. Good to see that it's fixed :)

**Comment by dennissiemensma** [comment]
I've tested this now and it likes like a charm :] 

I added some text formatting because my first notification was showing and electricity usage of `5.3439999999999999`. Now this (and the total prices + gas) will be rounded to two decimals.

**Comment by dennissiemensma** [comment]
Merged to `development` as https://travis-ci.org/dennissiemensma/dsmr-reader/builds/178703214 succeeded.

**Comment by jeroenpeters1986** [comment]
Cool :+1:

**Comment by dennissiemensma** [comment]
I just thought of the situation of some users not having their gas read at all. I've added a test for this in 8ecfcc253d0d557c5b09c1c22caf93b1f73d503e (using existing tests, but altering the loaded fixtures) to simulate this.

And as my own 'formatting' addition crashed, I've fixed that as well.

**Comment by dennissiemensma** [comment]
The release containing your pull requests has just been released: 
https://github.com/dennissiemensma/dsmr-reader/releases/tag/v1.4.0
