### ISSUE TITLE
Add new note from Dashboard has wrong time format

### ISSUE THREAD

**Issue by sevickson** [dennissiemensma/dsmr-reader#159]
First of all, great application! Keep up the good work. First time creating an issue on Github so bear with me.

When creating a note from the Dashboard, Dashboard is in english, it puts the wrong date-format in the note. See screenshot. 
The format it accepts is yyyy-mm-dd.
![add-note-error](https://cloud.githubusercontent.com/assets/23718156/20593997/bd63f42a-b234-11e6-95bb-c201add8360d.PNG)

**Comment by dennissiemensma** [comment]
Hi! Thank you for your kind words and reporting this bug. 

I can also reproduce this bug myself, it so I'll make sure to have it fixed. :]

**Comment by dennissiemensma** [comment]
I thought I made this note date variable locale independent, but I seem to only have applied that to the same button in the Archive page. 

Now it's fixed in 9af380679e3893cc0b2e46e63b2aecef98b8e23e and will be bundled with the upcoming `v1.4` release.

**Comment by dennissiemensma** [comment]
@sevickson all contributers are listed on the credits page: http://dsmr-reader.readthedocs.io/en/latest/credits.html. 

I will list you als "sevickson" by default, but if you'd like to have your real name listed there, just let me know here.

**Comment by dennissiemensma** [comment]
Tests greenlit @ https://travis-ci.org/dennissiemensma/dsmr-reader/builds/178648725

So hereby merged back to the main `development` branch for v1.4.

**Comment by sevickson** [comment]
@Dennis:

It is my real name. :-P


________________________________

**Comment by dennissiemensma** [comment]
Great! Then **Sevickson** it is, thanks again. ;-)

**Comment by dennis** [comment]
@sevickson Please don't use @dennis unless you want to notifiy me :)

**Comment by dennissiemensma** [comment]
The release containing the fix for your report has just been released: 
https://github.com/dennissiemensma/dsmr-reader/releases/tag/v1.4.0
