### ISSUE TITLE
Translate README to Dutch

### ISSUE THREAD

**Issue by dennissiemensma** [dennissiemensma/dsmr-reader#16]
I like to default to English to keep the documentation in sync with the code base. However, most users will be Dutch so I should make the README available in Dutch as well.

Might worth checking out: 
* https://www.transifex.com/signup/
* https://poeditor.com/

**Comment by dennissiemensma** [comment]
For later: https://www.transifex.com/signup/

**Comment by voipmeister** [comment]
Hi @dennissiemensma , you might want to check out https://poeditor.com/ as well. Free of charge if the project has an OSI license.

**Comment by dennissiemensma** [comment]
Thanks, I've added it to the issue. :]

**Comment by dennissiemensma** [comment]
Project docs will be hosted on Read The Docs, supporting sphinx and PO-files. Branched to Dutch here, but broken atm: http://dsmr-reader.readthedocs.org/nl/latest/

English main version will have to be completed first (#90).

**Comment by dennissiemensma** [comment]
`make gettext`+ `sphinx-intl update -p _build/locale -l nl`

**Comment by dennissiemensma** [comment]
Dutch version now builds as well: http://dsmr-reader.readthedocs.org/nl/latest/intro.html

For testing I only translated one word in the menu `Introduction` -> `Introductie` using PO. Seems to work perfectly.

**Comment by dennissiemensma** [comment]
Well, I'm about halfway there now! Already merged half of it to master branch and it works really well!

* http://dsmr-reader.readthedocs.org/nl/latest/index.html

vs

* http://dsmr-reader.readthedocs.org/en/latest/index.html


----

Only one page remains, but it also contains about half of the documentation I think:
http://dsmr-reader.readthedocs.org/nl/latest/installation.html

**Comment by dennissiemensma** [comment]
Completed at last! I'm sure there will be several typo's in there, but they will come around sometime anyway. 

For now I'm proud to have the documention hosted by RTD in both English and Dutch!

* http://dsmr-reader.readthedocs.org/en/latest/
* http://dsmr-reader.readthedocs.org/nl/latest/

I also fixed the theme, so now it's really easy to switch between those languages.
