### ISSUE TITLE
Update documentation for notifications

### ISSUE THREAD

**Issue by jeroenpeters1986** [dennissiemensma/dsmr-reader#160]
Notifications are now "live" in the developmentbranch. A little explaination about both notification services should lead users the way in setting them up

**Comment by jeroenpeters1986** [comment]
I'll make a PR for this :)

**Comment by jeroenpeters1986** [comment]
@dennissiemensma did you use specific tools to translate the documentation?

**Comment by dennissiemensma** [comment]
Many thanks. The v1.4 release was already frozen, but since it's only doc updates I've merged it.

I also updated the docs HOWTO in 0186f787450cd56a55d1c501cb0d5bbbd3ec5be7, as it seems possible after all to preview docs translation results.

**Comment by dennissiemensma** [comment]
RTD also built the docs now, looking good:

* http://dsmr-reader.readthedocs.io/en/development/faq.html

* http://dsmr-reader.readthedocs.io/nl/development/faq.html

**Comment by jeroenpeters1986** [comment]
Nice, looking good indeed 😎
