### ISSUE TITLE
Capability based push notifications

### ISSUE THREAD

**Issue by dennissiemensma** [dennissiemensma/dsmr-reader#165]
The recently added feature in #152 provides notifications about electricity and gas consumption. There are however users without gas consumption or users who also return electricity to the net.

It would be nice to construct the notification message based on the capabilities of the application environment.

**Comment by jeroenpeters1986** [comment]
I think I could make this change, is the gas-usage always 0, or does this
situation presents itself some other way?

Op zo 27 nov. 2016 om 15:41 schreef Dennis Siemensma <
notifications@github.com>

**Comment by dennissiemensma** [comment]
Thanks! But I'm already working on it. There is a service called `get_capabilities()` which can provide this information.

**Comment by jeroenpeters1986** [comment]
Cool!

Op zo 27 nov. 2016 om 16:35 schreef Dennis Siemensma <
notifications@github.com>

**Comment by dennissiemensma** [comment]
Merged to `development` as RC5. Also delayed v1.4 for a few days.
