### ISSUE TITLE
Netinstall installer-config.txt / ansible

### ISSUE THREAD

**Issue by dennissiemensma** [dennissiemensma/dsmr-reader#17]
Originally reported by: **Dennis Siemensma (Bitbucket: [dennissiemensma](http://bitbucket.org/dennissiemensma), GitHub: [dennissiemensma](http://github.com/dennissiemensma))**

----------------------------------------

My Pi just wouldn't install due to broken or laggy mirrors. I fixed it by using some german university as mirror (http://www.raspbian.org/RaspbianMirrors).

We might want to have a read-to-use installer-config.txt anyway, which might shorten the installation guide a lot (for the headless users). More info @ https://github.com/debian-pi/raspbian-ua-netinst#installer-customization

----------------------------------------
- Bitbucket: https://bitbucket.org/dennissiemensma/dsmr-reader/issue/17

**Comment by dennissiemensma** [comment]
**installer-config.txt**
`mirror=http://raspbian.mirror.technl.net/raspbian`

**Comment by jeroenpeters1986** [comment]
they just released a new Jessie Lite, using it for my Pi now :)

**Comment by dennissiemensma** [comment]
`dd if=2016-02-03-raspbian-jessie-lite.img of=/dev/mmcblk0 bs=1M`

**Comment by dennissiemensma** [comment]
Hmm Raspbian Lite misses a lot of stuff, such as python3, mysql, postgresql, so for now I'll have to revert to netinstall.

**Comment by dennissiemensma** [comment]
`xzcat raspbian-ua-netinst-v1.0.8.1.img.xz > /dev/mmcblk0`

**Comment by dennissiemensma** [comment]
Hmm seems ansible is not ready for python3 yet, so I'll have to suspend this issue for now.

**Comment by dennissiemensma** [comment]
Investigate whether we could use PIP sometime to checkout DSMR. Sentry does that as well, in a virtualenv, having only a .sentry/settings.py file. Might be interesting.

**Comment by dennissiemensma** [comment]
I think this would be outdated by both the PIP and pre-installed SD-card ticket.
