### ISSUE TITLE
Weather graph not showing when no gas data is available

### ISSUE THREAD

**Issue by Helloitsme** [dennissiemensma/dsmr-reader#170]
Thank you for the great program! Measurements from the meter are working great.
One issue however:  although weather is selected in the settings, there is no weather graph visible on the dashboard.

![weather 1](https://cloud.githubusercontent.com/assets/2877375/20936612/8a992aa2-bbe3-11e6-9abf-80dc1c4e9ea4.PNG)
![weather 2](https://cloud.githubusercontent.com/assets/2877375/20936613/8a9b3298-bbe3-11e6-866b-fc6b8448c413.PNG)

**Comment by dennissiemensma** [comment]
Hi! Thank you for reporting your issue. This is a bug I seem to have forgotten to fix while implementing it in #18.

It is 'caused' by the lack of gas readings in your situation, because I decided (in the earlier stages of this project) to have the gas reading trigger the weather readings every hour. This works for many users, including myself, but obviously not for anyone without a gas meter connected as well.

As this is a bug that should be fixed, I will schedule this for the upcoming release. Which is planned for mid January.

**Comment by Helloitsme** [comment]
Great, thanks!

**Comment by dennissiemensma** [comment]
I've fixed this and I've running it now for a day or so myself. Works fine, so it'll be merged back to the main `development` branch for the next release.

**Comment by dennissiemensma** [comment]
@Helloitsme please notice #180 as well.

**Comment by Helloitsme** [comment]
Hi Dennis, You can mention me, but i don't see myself as a tester



On Fri, Dec 16, 2016 at 9:32 PM +0100, "Dennis Siemensma" <notifications@github.com<mailto:notifications@github.com>> wrote:


@Helloitsme<https://github.com/Helloitsme> please notice #180<https://github.com/dennissiemensma/dsmr-reader/issues/180> as well.

**Comment by dennissiemensma** [comment]
Aah I see, maybe I wasn't clear enough then. 

It's just a 'wall of fame' for the project. It doesn't make you a tester or demand that you test stuff. It's just a way to say 'thank you' for your contribution (which can be a simple as reporting an issue). It's similar to pages like these: https://sentry.io/thanks/

It's optional anyway, but just so you know. :]

**Comment by dennissiemensma** [comment]
@Helloitsme the [`v1.5` release is out](https://github.com/dennissiemensma/dsmr-reader/releases/tag/v1.5.0), containing this issue.

Please mind:
- [the release notes](http://dsmr-reader.readthedocs.io/en/latest/changelog.html#v1-5-0-2017-01-01) 
- [how-to-upgrade docs](http://dsmr-reader.readthedocs.io/en/latest/faq.html#how-can-i-update-my-application)

Also note that upgrading requires you to cd into the project root and activate the VirtualEnv, after switching to the `dsmr` user. The installation guide hinted that before, but it's [highlighted more clearly now](http://dsmr-reader.readthedocs.io/en/latest/installation.html#virtualenv).

**Comment by Helloitsme** [comment]
It works, Thanks!
