### ISSUE TITLE
Status page visualisation

### ISSUE THREAD

**Issue by dennissiemensma** [dennissiemensma/dsmr-reader#172]
The status page currently display the background process progress, and hints when it's lagging behind. I think however that a visual bar or percentage will be more clear to the user.

Optionally every signal service's last check in could be logged and displayed as well.

**Comment by dennissiemensma** [comment]
It was quite some refactoring, but it's finished!

And I think that it's really awesome: 
http://dsmr-reader.readthedocs.io/en/development/_static/screenshots/status.png?r2

This will greatly help users checking both the data status and understand how it flows as well...

**Comment by markruys** [comment]
Nice 👍
