### ISSUE TITLE
Docs: How to restore backup

### ISSUE THREAD

**Issue by dennissiemensma** [dennissiemensma/dsmr-reader#190]
Extend both the FAQ and installation instructions with a `howto` restore backup.

**Comment by dennissiemensma** [comment]
For my own reference (and maybe the docs): 
- Restoring a backup on a RaspberryPi 3, containing roughly **3.2+ million** telegrams, took about 5 minutes. 

Which is very nice.

**Comment by Jeltel** [comment]
Pretty much getting the latest backup back to the pi and running that SQL command just after creating the database is fine. That's all there is to it.

So copy this and your fine: https://github.com/dennissiemensma/dsmr-reader/issues/178#issuecomment-268090931

**Comment by dennissiemensma** [comment]
Merged to `development`.
