### ISSUE TITLE
Bij wegvallen internetverbinding verspringt buitentemp

### ISSUE THREAD

**Issue by LadyIT** [dennissiemensma/dsmr-reader#198]
Puntjes op de i : 
Als het internet wegvalt en na een x aantal uur weer opkomt, dan zit er een sprong in de X-as (tijd) in de buitentemperatuur grafiek. Mogelijk om de verloren gegevens in dat tijdbestek terug op te halen en/of de x-as gewoon doorlaten lopen zonder gegevens oid? In het voorbeeld hieronder tussen 15:00 en 19:00.

![naamloos](https://cloud.githubusercontent.com/assets/15814366/21577009/4fb9c200-cf4a-11e6-85be-c878fb762d13.png)

**Comment by dennissiemensma** [comment]
Bedankt voor je ticket.

Het is niet mogelijk om de gegevens met terugwerkende kracht op te halen. De applicatie gebruikt [deze pagina van Buienradar](http://api.buienradar.nl/) en die toont alleen actuele gegevens.

Ik kan wel kijken of het mogelijk is om missende waardes op de X-as alsnog (leeg) te plotten. Andere grafieken hebben hier namelijk ook 'last' van.

**Comment by LadyIT** [comment]
Lijkt me een nette oplossing!

**Comment by dennissiemensma** [comment]
Momenteel sluit ik diverse issues in bulk, waaronder deze. Realistisch gezien kom ik hier de komende tijd niet (meer) aan toe, gezien mijn beschikbare tijd aanzienlijk is afgenomen én ik afdoende werk heb met het debuggen van issues waar men tegenaan loopt. 

En ik besteed liever wat meer tijd aan de kern van dit project: Ervoor zorgen dat gebruikers op zoveel mogelijk manieren bij hun data kunnen (export, MQTT, etc.). Alle andere features zijn vooral nice-to-have...

**Comment by dennissiemensma** [comment]
Dit specifieke probleem komt (naar mijn mening) te weinig voor om hier echt actie voor te ondernemen. Ik begrijp helemaal dat het mooi is om dit net te krijgen, maar gezien bovenstaande comment over mijn tijdsbesteding zie ik realistisch gezien geen oplossing gemaakt worden.
