### ISSUE TITLE
Mailnotificatie toevoegen?

### ISSUE THREAD

**Issue by ThinkPadNL** [dennissiemensma/dsmr-reader#202]
De notificatie mogelijkheid spreekt mij wel aan. 
Ik zou het handig vinden als een notificatie per mail zou kunnen worden verstuurd. Dan is het platformonafhankelijk. Al snap ik ook wel dat dat niet eenvoudig toe te voegen is, want de mail moet ergens verstuurd worden. Dan moet je al met SMTP-instellingen e.d. aan de gang.

**Comment by dennissiemensma** [comment]
Bedankt voor je verzoeken. Ik kan me zeker (in een deel) vinden. 

Het mailen is wel een technische uitdaging die goed getest mag worden. Mails zonder domeinnaam en SPF-records in de DNS worden vaak al gefiltered als spam. En voor thuis-Internet blokkeren de meeste providers ook al SMTP-poort 25 (en heb je inloggegevens nodig via de provider).

Zet dit voor nu op de lijst voor `v1.7` om er dan weer naar te kijken, gezien [`v1.6` inmiddels aardig vol is](https://github.com/dennissiemensma/dsmr-reader/milestone/25). De ticketlijsten voor de versies staan overigens nooit vast, helemaal niet aan het begin van een nieuwe release.

**Comment by ThinkPadNL** [comment]
Het mailen is inderdaad wel een technische uitdaging. Maar als men dsmr-reader draaiend heeft kunnen krijgen, dan moet het opzoeken & instellen van de gewenste SMTP-instellingen niet zo'n punt zijn lijkt mij ;-) Wanneer men gewoon het eigen mailadres gebruikt dan komt het niet zomaar in de spamfolder. Heb voor monitoring in m'n thuisnetwerk ook m'n Gmail-adres ingesteld en dat werkt prima.

Het versturen van notificaties via mail lijkt mij wel een zinvolle toevoeging. Ik kan namelijk wel een paar tegen-argumenten bedenken voor de huidige manier waarop notificaties zijn geïmplementeerd:

- Prowl (iOS) is een betaalde app
- Er zal wellicht ook iemand een verzoek indienen om op zijn/haar Windows Phone een notificatie te kunnen krijgen, dat is nu niet mogelijk
- Wellicht zijn er ook mensen die dit gebruiken en geen smartphone hebben (bestaan die :D ?) en dus geen pushnotificaties kunnen ontvangen.

E-mail is dan wel vrij universeel in dat opzicht.

**Comment by dennissiemensma** [comment]
Klopt, ik ben het daar helemaal mee eens hoor. De telefoon-notificaties zijn meer een nice to have, en optioneel. 

E-mail is zeker werkend te krijgen, het is alleen wel iets is wat goed getest mag worden zodat het een oplossing is die overal bij iedereen werkt. Altijd.
Uiteindelijk zie ik ook liever e-mailnotificaties dan via een (externe) app, omdat het zowel een externe app vereist en voor iOS betaald is (mocht je nog een andere gratis service weten dan hoor ik dat graag). Precies zoals je al aangeeft.

**Comment by ThinkPadNL** [comment]
> mocht je nog een andere gratis service weten dan hoor ik dat graag
Voor m'n domoticasysteem ([Home Assistant](https://home-assistant.io/)) gebruik ik [Telegram](https://telegram.org/) om notificaties vanuit het systeem naar mijzelf te sturen (wasmachine klaar, plaatje als er iemand aanbelt e.d.). Je maakt dan een zgn. 'bot' aan en kan dan berichtjes sturen. Is vrij eenvoudig (gewoon HTTP-calls), zie ook de [documentatie](https://core.telegram.org/bots).
Werkt op [zo'n beetje alle platformen](https://telegram.org/apps).

Maar feit blijft dat je dan ook weer een app hebt, terwijl e-mail op elk device met internet werkt.

**Comment by ThinkPadNL** [comment]
Ik heb dit issue even opgesplitst in meerdere issues (#205 en #206), dat maakt het voor jou wat overzichtelijker.

**Comment by dennissiemensma** [comment]
Momenteel sluit ik diverse issues in bulk, waaronder deze. Realistisch gezien kom ik hier de komende tijd niet (meer) aan toe, gezien mijn beschikbare tijd aanzienlijk is afgenomen én ik afdoende werk heb met het debuggen van issues waar men tegenaan loopt. 

En ik besteed liever wat meer tijd aan de kern van dit project: Ervoor zorgen dat gebruikers op zoveel mogelijk manieren bij hun data kunnen (export, MQTT, etc.). Alle andere features zijn vooral nice-to-have...

**Comment by dennissiemensma** [comment]
Ik weet niet of je dit project nog steeds gebruikt (ik kan me goed voorstellen dat met jouw wensen het te verperkt is), maar realistisch gezien kan/ga ik het niet allemaal verwerken. Toch erg bedankt voor je al goede ideeen, die zijn/waren echt top!
