### ISSUE TITLE
Mindergas.nl API: Tijdstip van verzending willekeurig maken

### ISSUE THREAD

**Issue by ThinkPadNL** [dennissiemensma/dsmr-reader#204]
Ik zit even de code door te kijken en volgens mij wordt [hier](https://github.com/dennissiemensma/dsmr-reader/blob/master/dsmr_mindergas/services.py#L39#L46) het tijdstip van verzending gasmeterstand naar mindergas.nl bepaald. Als ik het goed zie, gebeurt dat om 0:00 exact.

Ik heb zo mijn twijfels of dat een handige keuze is. Mindergas.nl zegt zelf namelijk:

> **_Wanneer posten?_**
> Om de serverbelasting wat te spreiden is het aan te raden om een vertraging in te bouwen tussen het uitlezen van de meterstand en het opsturen naar de server. Bijvoorbeeld een vertraging van een willekeurig aantal minuten tussen 0 en 60.

(Bron: https://mindergas.nl/member/api)

Zeker als er meer en meer mensen via dsmr-reader hun gasmeterstand gaan uploaden naar Mindergas.nl, dan is het wel zo vriendelijk om daar wat willekeurigheid in aan te brengen (Meterstand uploaden tussen 0:00 en 1:00 ofzo). Anders is `dsmr-reader` een soort botnet-in-wording 😆 

Ze bieden de API al enige jaren gratis aan, het zou jammer zijn als ze besluiten om de API dicht te zetten. Ik vind het een handige site namelijk

**Comment by dennissiemensma** [comment]
Dat klopt, je kunt het bij jezelf checken in de logs met:
`zgrep MinderGas /var/log/supervisor/dsmr_backend.log.* -B 10`

Het toevoegen van een willekeurige vertraging lijkt mij prima.

**Comment by dennissiemensma** [comment]
Merged 0aab1828b1abf279cb145dc846e5fc8d2683ebbd to `development` branch.

**Comment by dennissiemensma** [comment]
Deze is bij toeval onderdeel geworden van de patch die net uitgebracht is. 

De eerstvolgende keer dat de export gedraaid wordt, pakt hij middernacht + 15 tot 59 minuten voor de **opvolgende keer**. Dus feitelijk die van overmorgen.

**Comment by ThinkPadNL** [comment]
Goed bezig, heb hem geïnstalleerd. Zal het even controleren komende week met `zgrep MinderGas /var/log/supervisor/dsmr_backend.log.* -B 10`
