### ISSUE TITLE
Notificatie interval naar maandelijks i.p.v. dagelijks?

### ISSUE THREAD

**Issue by ThinkPadNL** [dennissiemensma/dsmr-reader#205]
De notificatie mogelijkheid spreekt mij wel aan. 
Alleen dagelijks is voor mijzelf nogal overkill en iets wat mij waarschijnlijk snel gaat irriteren. 
Is het misschien mogelijk om deze interval te vergroten naar maandelijks? (Om 0:00 / 0:01 van de eerste van de maand lijkt mij dan handig).

**Comment by dennissiemensma** [comment]
Momenteel sluit ik diverse issues in bulk, waaronder deze. Realistisch gezien kom ik hier de komende tijd niet (meer) aan toe, gezien mijn beschikbare tijd aanzienlijk is afgenomen én ik afdoende werk heb met het debuggen van issues waar men tegenaan loopt. 

En ik besteed liever wat meer tijd aan de kern van dit project: Ervoor zorgen dat gebruikers op zoveel mogelijk manieren bij hun data kunnen (export, MQTT, etc.). Alle andere features zijn vooral nice-to-have...

**Comment by dennissiemensma** [comment]
Dit delegeer ik deels naar MQTT via #367. Het is niet perse per maand, maar je zou dan zelf wat in elkaar kunnen flansen zodat jij de gegevens ziet die jij wil, op het moment dat jij wil.
