### ISSUE TITLE
Piek+dal Tarief  combineren in overzichten

### ISSUE THREAD

**Issue by Roeliooo** [dennissiemensma/dsmr-reader#233]
Op de archief /trend/ etc pagina totaalverbuik electra optelsom Piek/Dal tarief weergeven. Nu Niet Duidelijk Hoeveel het Totaalverbruik Per Dag Is.

**Comment by dennissiemensma** [comment]
Bedankt voor je ticket. In principe kun je het wel zelf optellen (lage getallen), maar ik zal kijken of ik een totaal telletjes kan maken bij de redesign van de pagina's.

**Comment by Roeliooo** [comment]
Zou heel fijn zijn :)

**Comment by Helloitsme** [comment]
Zou wellicht ook een idee zijn om in plaats van 2 lijnen in de grafiek te gebruiken, een stacked column grafiek te maken, dan zie je zowel de details als het totaal goed. Vooral op de archief pagina, waar je op maand niveau zowel dal als piek tarief hebt zou dat handig zijn

**Comment by dennissiemensma** [comment]
Bedankt voor je suggestie, wellicht is dat wel een goede optie. Ik zal tzt meerdere formaten uitproberen en kijken welke het duidelijkste is.

**Comment by dennissiemensma** [comment]
Dit is voor een deel opgepakt in de pull request #341 van helmo. Het hervormen van de interface is een apart iets, waar ik sowieso wel een release aan kwijt ben. Voor nu zou dit afdoende moeten zijn.
