### ISSUE TITLE
Brondata elders opslaan (NAS?) 

### ISSUE THREAD

**Issue by Varsame** [dennissiemensma/dsmr-reader#241]
Hoi Dennis, 
Ik zat eens te prakkiseren over het potentiële probleem van een kapotte SD kaart in de Raspberry Pi door teveel read/write sequences. Hoewel je in je programma een keurige backup optie hebt om na een restore gewoon verder te kunnen, heb ik bijvoorbeeld niet standaard een reserve SD in huis voor deze gevallen... Dus er zal wat tijd overheen gaan voor ik verder kan loggen zeg maar. 
Is het iets om een optie in te bouwen om naar een externe SQL server te loggen, zoals bv. een NAS die vaak ook in de meterkast staat? 
Eventueel via een buffer op een RAM-drive op de Raspberry Pi om netwerk issues te ondervangen (bv wifi connectie problemen oid). Mijn eerste generatie Pi B heeft al voldoende vrij geheugen om dit mogelijk te maken. 

In hoeverre dit echt "nodig" is weet ik niet, ik heb nog nooit een corrupte SD gehad. Maar het gebruik van een externe database maakt ook restore na een crash makkelijker. Maar wellicht ook lastiger om te managen vanwege dependencies. Ik snap dat het een lange termijn ding is, áls je er al aan begint :) 

(wat natuurlijk óók kan is het hele Dsmr-reader op de NAS draaien... Maar dat terzijde :))

**Comment by dennissiemensma** [comment]
Bedankt voor het delen van je gedachtengang. Ik kan je aanraden om sowieso een extra kaartje in huis te hebben, niet zozeer voor dsmr-reader, maar omdat je SD-kaart sowieso ooit kapot gaat. En áltijd op een slecht moment. 
Ik heb zelf goede ervaringen [met deze Sansumg-kaart](https://www.dataio.nl/samsung-16gb-micro-sd-evo-met-adapter-uhs-i-class-10-48mbs/) (en vind ik persoonlijk ook betaalbaar).

Wat betreft het loggen naar een externe bron, dat is zeker mogelijk. Het doel van dit projectje is om hobby-techneuten iets leuk met de rPi te kunnen laten doen, maar de software werkt in principe in elke Linux-omgeving en [is zelfs te scheiden qua datalogger / applicatie](http://dsmr-reader.readthedocs.io/en/latest/api.html#script). 
Je zou zelfs de database en applicatie nog los van elkaar kunnen draaien, mits de verbinding daartussen stabiel genoeg is. Ik raad echter wel aan om database en applicatie bij elkaar te houden. De datalogger kan een losstaand iets zijn, zelfs via een ESP (zie ticket #187).

Het opbouwen van een buffer via een RAM-drive zou kunnen, maar is eigenlijk overcomplex. Ik zou dan de hele applicatie ergens anders draaien en alleen de datalogger op je rPi houden. De kans dat je kaart dan stuk gaat door (dsmrreader-)writes is nihil.

Ik gebruik [Django als onderliggend framework](https://docs.djangoproject.com/en/1.10/ref/databases/) voor een hoop zaken en die ondersteunt ook externe databaseverbindingen. Je kunt dat eventueel zelf instellen. Zie daarvoor op je rPi:
```
sudo su - dsmr
cat dsmrreader/settings.py 
```

Die `settings.py` heb je tijdens de installatie gekopieerd en bevat een standaard locatie, maar je kunt de database naar hartelust ergens anders draaien.

Ik ga hier geen expliciete ondersteuning voor bouwen omdat dit dus al mogelijk is. Mocht je hulp nodig hebben bij het verplaatsen van je database of iets dan kan ik je altijd tips geven.
