### ISSUE TITLE
Grafiek gasverbruik doet wat vreemd na aantal uur geen nieuwe data

### ISSUE THREAD

**Issue by ThinkPadNL** [dennissiemensma/dsmr-reader#245]
Ik zit even te kijken naar m'n verbruik, maar volgens mij komt e.e.a. niet overeen. Nu is het zo dat de metingen er een paar uur uit hebben gelegen, zou het kunnen dat e.e.a daardoor niet meer synchroon loopt?
![dsmr1](https://cloud.githubusercontent.com/assets/12446338/22081208/fa595c4e-ddc2-11e6-8fda-396aaa523021.png)
![dsmr2](https://cloud.githubusercontent.com/assets/12446338/22081209/fa91fce8-ddc2-11e6-8855-7c43af21369e.png)

Als ik de punten in de grafiek optel (vanaf 0:00 uiteraard) kom ik op 1,9m3. De tekstweergave-indicator zal wel kloppen, maar die grafiek doet een beetje raar op deze manier 😄 Met het cumulatief maken van gasverbruik in #235 valt er wel beter te zien wat er verkeerd gaat in zo'n situatie denk ik.

**Comment by dennissiemensma** [comment]
Ja klopt, alle meetpunten zijn event-gebaseerd, dus als er geen data is maakt die ook geen datapunt en weet de grafiek ook niet dat er iets mist. 

Dit valt denk ik onder dezelfde noemer als #198 en dan mag de grafiek rekening houden met lege punten.

**Comment by m2day** [comment]
Ik denk dat het komt omdat, in [dsmr-reader/dsmr_stats/services.py](https://github.com/dennissiemensma/dsmr-reader/blob/master/dsmr_stats/services.py) de functie  create_hourly_statistics slechts naar het actuele verbruik op het hele uur kijkt in plaats van gedurende het uur. 

In het geval van meters die meerdere resultaten per uur teruggeven zoals bij mijn DSMR v5 klopt de grafiek dan niet. Ik zou verwachten dat de berekening voor het verbruik dan gelijk zou moeten zijn aan die van elektriciteit. Dus stand aan het eind van het uur - stand aan het begin van het uur.

Dus iets in de trant van:
```
if gas_readings.exists():
	gas_start = gas_readings[0] 
	gas_end = gas_readings[gas_readings.count() - 1] 
	creation_kwargs['gas'] = gas_end.delivered - gas_start.delivered
```

in plaats van:
```
if gas_readings.exists(): 
	# Gas readings are unique per hour anyway. 
	creation_kwargs['gas'] = gas_readings[0].currently_delivered 
```

**Comment by dennissiemensma** [comment]
Bedankt voor je input. Ik denk dat dat nog een stukje nazorg is, dat ik ben vergeten om te bouwen bij het ondersteunen van DSMR v5.

**Comment by dennissiemensma** [comment]
Even onderzocht, test kunnen maken om te reproduceren en de bovenstaande voorgestelde oplossing doorgevoerd. Bedankt voor het melden/uitwerken.
