### ISSUE TITLE
Changing USB device

### ISSUE THREAD

**Issue by mbnn** [dennissiemensma/dsmr-reader#247]
Hello, thanks for the great application however, in the installation documentation it doesnt say anything about changing the USB logging port, in our case its bound to: ttyUSB22

What can we do to make your application work with that port?

Update: NVm :) Found it under configuration!

**Comment by dennissiemensma** [comment]
Thank you for reporting this issue, I've already scheduled updating the docs by explaining each setting available in #232. Glad you did already figured it out yourself.
