### ISSUE TITLE
Feature request: Add icon for iOS homescreen (save to homescreen)

### ISSUE THREAD

**Issue by emilkwaaitaal** [dennissiemensma/dsmr-reader#250]
I'm launching DSMR Reader from my homescreen on iPhone and iPad (save webpage to homescreen in Safari browser). There are possibilities to add a homescreen icon and also possibilities to launch full screen (without browser controls) to make it really look like a native iOS app.

See official documentation from Apple on how to get this working:
https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html

Would be great if this can be implemented to further improve the user experience on iOS devices

**Comment by dennissiemensma** [comment]
Hi, thank your for your request.

 I think there is some overlap with #249, which was just created before your ticket. I will close this one and move the information you provided to the other ticket.
