### ISSUE TITLE
Data verwerking

### ISSUE THREAD

**Issue by knetsooj** [dennissiemensma/dsmr-reader#254]
Kon niet vinden waar ik evt vragen kan stallen dus dan maar hier.
Ik maak al enkele weken tevreden gebruik van deze applicatie en alles was tot dusver goed.
nu keek ik vandaag naar de interface en zag ik het volgende:

![afbeelding](https://cloud.githubusercontent.com/assets/18591795/22563799/5e04766e-e982-11e6-80bb-91d60259180e.png)

Wat kan er voor zorgen dat de data verwerking niet meer loopt?
een reboot van de RPI deed het verwerken van telegrammen weer starten met behoud van alle data (erg fijn!)

**Comment by dennissiemensma** [comment]
Bedankt voor het melden. Het kan door een bug komen of een databasebackup. Van de week crashte het ook al bij iemand om deze reden: #251

Kun je zien of je een foutmelding kan terugvinden in de logs van de dataverwerking? Die staan in `/var/log/supervisor/dsmr_backend.log`.

**Comment by knetsooj** [comment]
Helaas, ik maak voor de logging gebruik van tmpfs om mijn SD te besparen. Er is daar dus niets terug te zien van voor de reboot.

**Comment by dennissiemensma** [comment]
Oke. Mocht het weer voorkomen, dan kun je in ieder geval in die logs kijken voor een mogelijke oorzaak.

**Comment by dennissiemensma** [comment]
@knetsooj ik heb in #251 een mogelijke fix gemaakt voor een van de oorzaken van dit probleem. Dat gaat mee bij de volgende v1.6 release. Mocht in de tussentijd toch nog zo'n fout ervaren en meer informatie hebben, dan hoor ik het graag. :]

**Comment by knetsooj** [comment]
@dennissiemensma na een weekje te zijn weggeweest zag ik zojuist dat de telegrammen al 4,5 dag niet meer verwerkt worden. in de backend log zie ik geen foutmeldingen,  laatste bericht:
***
2017-03-13 10:00:02.648887+01:00: Calling backend services
 - Processed reading: 2017-03-13 09:59:00+01:00.
 - Processed reading: 2017-03-13 09:59:11+01:00.
 - Processed reading: 2017-03-13 09:59:31+01:00.
 - Processed reading: 2017-03-13 09:59:41+01:00.
 - Processed reading: 2017-03-13 09:59:51+01:00.
 - Performing temperature reading at Buienradar.
***
Hierna is er voor de dsmr_backend.log geen nieuwe logging meer aangemaakt. Status in de supervisor is nog steeds running.

**Comment by dennissiemensma** [comment]
Bedankt voor het melden. Betekent dit dat je onverwerkte telegrammen hebt, of heeft de applicatie helemaal niets meer gemeten? (zie Status pagina)

**Comment by knetsooj** [comment]
Ik heb voor bijna 5 dagen aan onverwerkte telegrammen,  na service restart was #280 na een aantal uren het gevolg, ik weet echter niet in hoeverre dit aan elkaar gerelateerd was en of dit als twee individuele issues moet worden behandeld

**Comment by dennissiemensma** [comment]
Ik denk dat het losse dingen zijn. Zojuist is versie v1.6 uitgebracht en die verhelpt sowieso een probleem dat door foute data van Buienradar veroorzaakt kan worden.
