### ISSUE TITLE
Req: Track generated solar power consumed before the meter

### ISSUE THREAD

**Issue by Want100Cookies** [dennissiemensma/dsmr-reader#255]
I am looking for an application to track the power actually generated by the solar panels through the inverter.
My inverter exposes an api which I consume with a cron job.

Is there an possibility to send this to the dsmr-reader api to view the actual generated power from the solar panels in stead of the power that got send to the grid through the smart meter?
From this data there should be the possibility to calculate how much of the power from the solar panels got used by in-home devices and how much got sold to the power company. 
This produces an more accurate representation of the power usage in a home.

**Comment by dennissiemensma** [comment]
Hi, I think you might like [PVOuput](http://pvoutput.org/). It allows you to input data from several sources, including power generated (inverter) and consumption (smart meter). There are some inverters who have integrations for PVOuput as well. You could check if yours has support for it.

There is a ticket for exporting the meter positions to PVOutput as well (#9). You might follow that one. 

This project is only meant  to provide an easy solution for *reading your smart meter*, even though I see that it would be handy for some people if it did all kinds of other stuff as well.
