### ISSUE TITLE
dsmr_webinterface                FATAL      Exited too quickly (process log may have details)

### ISSUE THREAD

**Issue by eterpstra** [dennissiemensma/dsmr-reader#256]
Hoi,

Sinds gister kon ik dsmrreader webinterface niet meer laden.  Supervisor geeft de volgende error aan bij status:

dsmr_webinterface                FATAL      Exited too quickly (process log may have details)

reread commando lukt helaas niet. Ik krijg dan de volgende melding:
No config updates to processes

Hoe kan ik ervoor zorgen dat de webinterface weer gaat werken?

**Comment by dennissiemensma** [comment]
Je kunt het proces weer proberen te starten met de `sudo supervisorctl` tool. Eventueel direct een command meegeven:

* `sudo supervisorctl start dsmr_webinterface`

De `reread` gebruik je alleen als je wijzigingen aanbrengt in de configuratie (eenmalig bij installatie).

**Comment by dennissiemensma** [comment]
@eterpstra is dit gelukt? Draait het weer naar behoren?
