### ISSUE TITLE
Aanpassen data in DB om verkeerde meting door slimme meter

### ISSUE THREAD

**Issue by dbmnl** [dennissiemensma/dsmr-reader#258]
Net als issue #229 heb ik ook een entry in mijn DB waarbij ik  "opeens" energie aan het terugleveren ben aan de energiemaatschappij zonder dat ik zonnepanelen of iets dergelijks heb.

`sudo -u postgres psql dsmrreader -c "select * from dsmr_consumption_electricityconsumption where currently_returned is not null order by currently_returned desc limit 5;"`

![image](https://cloud.githubusercontent.com/assets/24806247/22770899/f320672e-ee93-11e6-93ee-50127cb45c48.png)

Raar, maar als gevolg hiervan zie ik nu ook grafieken voor energie terugleveren en wat ik momenteel aan het terugleveren ben. 
Gezien het maar 1x is gebeurd (heb het even een tijdje afgewacht om te kijken of ik niet een soortgelijk probleem had als #229 ) wil ik nu eigenlijk die extra grafieken er weer uit hebben omdat ik ook niet in de nabije  toekomst gebruik wil maken van energie terugleveren.

Nu vraag ik mij af of als ik de data aanpas in de DB of dit dan ook de grafieken voor terugleveren verwijderd of dat ik hier een ander trucje voor moet uithalen?
Tnx alvast

**Comment by dennissiemensma** [comment]
Klopt dat is [exact het veld dat gebruikt wordt](https://github.com/dennissiemensma/dsmr-reader/blob/v1.5.5/dsmr_backend/services.py#L26) daarvoor als kenmerk/conditie voor die grafieken.

Als je hem weer op nul zet, zou het goed moeten gaan en de extra grafieken verdwijnen.
