### ISSUE TITLE
Add link to readthedocs in Django for Dropbox instructions

### ISSUE THREAD

**Issue by TopdRob** [dennissiemensma/dsmr-reader#260]
Hi Dennis,

Maybe you could add a link to https://dsmr-reader.readthedocs.io/nl/latest/faq.html#dropbox-automated-backup-sync in the Django UI.

Best regards,
Robert

**Comment by dennissiemensma** [comment]
Thanks for the suggestion. I think I will combine it with #232 at that time.

**Comment by dennissiemensma** [comment]
I've added the link in the Django GUI via #232.
