### ISSUE TITLE
Move to Github

### ISSUE THREAD

**Issue by dennissiemensma** [dennissiemensma/dsmr-reader#28]
Originally reported by: **Dennis Siemensma (Bitbucket: [dennissiemensma](http://bitbucket.org/dennissiemensma), GitHub: [dennissiemensma](http://github.com/dennissiemensma))**

----------------------------------------

I do not like GIT a lot, but GitHub seems to be the preferred place for open source projects.

Import should be easy using:
https://import.github.com/new/

Clone URL:
https://dennissiemensma@bitbucket.org/dennissiemensma/dsmr-reader

----------------------------------------
- Bitbucket: https://bitbucket.org/dennissiemensma/dsmr-reader/issue/28

**Comment by dennissiemensma** [comment]
Mention voor @jeroenpeters1986. Dit is de nieuwe locatie van het project. Ik moet nog even uitvogelen hoe GIT precies werkt, maar ik kom er vast wel uit :D

Ik kan je aanraden om eerst nog even een laatste deploy te doen vanaf bitbucket. Momenteel zijn er nog geen nieuwe features sinds de migratie hier naar toe.

**Comment by dennissiemensma** [comment]
Forget that I still have to update README and deploy script and such.

**Comment by jeroenpeters1986** [comment]
Just did my last deploy from Bitbucket :)

**Comment by dennissiemensma** [comment]
Updated docs + deploy script. Switched my production to git checkout.

**Comment by dennissiemensma** [comment]
@jeroenpeters1986 mocht je het ingebouwde deployscript niet gebruiken, als het goed is haal je hier voortaan de laatste stable binnen, ipv `hg pull --up`:

* `git fetch --tags`
* `git checkout stable`

----

Voor het wisselen van de checkout op productie heb ik dit zelf gedaan:

* `su - dsmr`
* `cd ~` (om te voorkomen dat je nog in projectmap zit)

Nieuwe checkout naast die van hg:
* `git clone https://github.com/dennissiemensma/dsmr-reader.git --branch stable dsmr-reader.git`

Settings kopieren. Pak je eigen uit de hg-versie als je niet de default gebruikt.
* `cd dsmr-reader.git`
* `cp dsmrreader/provisioning/django/mysql.py dsmrreader/settings.py`

Controleer of je nieuwe checkout werkt (qua settings + DB conn.):
* `./manage.py check`
* `./manage.py migrate --list`

Tijd om te wisselen, alles wat de code gebruikt even stoppen:
* ctrl +D naar root of sudo-user
* `supervisorctl stop all` (of alleen de dsmr-commands als je meer in supervisor hebt)

Terug naar DSMR-user:
* `su - dsmr`
* `cd ~` (om te voorkomen dat je nog in projectmap zit)

Move de hg-checkout als kopie/backup.
* `dsmr-reader dsmr-reader.mercurial`

Je hebt nu `dsmr-reader.mercurial` en `dsmr-reader.git` in deze mappen staan. Je kunt ofwel de git-versie renamen ofwel  een symlink maken:
* `ln -s dsmr-reader.git dsmr-reader` of `mv dsmr-reader.git dsmr-reader`

Klaar, weer terug naar root en supevisor aanzetten en natuurlijk even de webinterface testen/minuutje afwachten.
* `supervisorctl start all`

**Comment by dennissiemensma** [comment]
For own reference, how to keep the stable tag moving (blergh):

http://stackoverflow.com/a/8044605

**Comment by dennissiemensma** [comment]
Closing issue for now.
