### ISSUE TITLE
Instructies voor upgrade naar 1.6 in documentatie incorrect

### ISSUE THREAD

**Issue by goegol** [dennissiemensma/dsmr-reader#283]
In je documentatie schrijf je (https://dsmr-reader.readthedocs.io/nl/latest/faq.html#how-can-i-update-my-application) dat je als dsmr user moet zijn ingelogd, en dan in de hoofdmap de file ./upgrade.sh moet draaien.

Deze file ontbreekt bij mij.
Volgende files staan in de hoofdmap:
backups      coverage_report  dsmr_api      dsmr_consumption  dsmr_mindergas     dsmr_stats    logs            pre-deploy.sh  README.md
CHANGELOG    deploy.sh        dsmr_backend  dsmr_datalogger   dsmr_notification  dsmr_weather  manage.py       pylama.ini     reload.sh
codecov.yml  docs             dsmr_backup   dsmr_frontend     dsmrreader         LICENCE       post-deploy.sh  quick-test.sh  test-all.sh

Wat kan ik doen om upgrade te draaien?

**Comment by dennissiemensma** [comment]
Bedankt voor het melden, zeer scherp! Ik heb de documentatie wat herschreven en dit klopt inderdaad niet. Ik zal het aanpassen.

Om te upgraden kun je het `./deploy.sh` script draaien.

**Comment by dennissiemensma** [comment]
Het is aangepast, bedankt.
