### ISSUE TITLE
Verzoek: mogelijkheid in het dashboard om een eigen tijdspanne weer te geven

### ISSUE THREAD

**Issue by michielvisser** [dennissiemensma/dsmr-reader#285]
Op dit moment laat de elektriciteitsgrafiek (ik heb geen teruglevering en gas) standaard het laatste half uur zien in het dashboard. Het is mogelijk terug te kijken d.m.v. de knoppen onder de grafiek. Echter, omdat data pas een dag later geaggregeerd wordt in het archief, zou ik de volgende twee opties voor het bekijken van de 'live' grafiek een goede aanvulling vinden:

- Mogeljkheid tot het bekijken van een grotere tijdspanne naast de standaard 30 minuten, bijvoorbeeld laatste uur, laatste 2 uur, enz. 
- Knop waarmee je na terugscrollen met 1 klik erop weer teruggaat naar de laatste metingen.

Ik weet niet of iets dergelijks te realiseren valt, maar wellicht is het een idee voor toekomstige releases.

**Comment by dennissiemensma** [comment]
Bedankt voor je suggesties. Voor je eerste idee staat al een redesign voor later op de planning. Zie #235. Voor je tweede idee, daar is zeker wel iets voor te maken.

**Comment by dennissiemensma** [comment]
Momenteel sluit ik diverse issues in bulk, waaronder deze. Realistisch gezien kom ik hier de komende tijd niet (meer) aan toe, gezien mijn beschikbare tijd aanzienlijk is afgenomen én ik afdoende werk heb met het debuggen van issues waar men tegenaan loopt. 

En ik besteed liever wat meer tijd aan de kern van dit project: Ervoor zorgen dat gebruikers op zoveel mogelijk manieren bij hun data kunnen (export, MQTT, etc.). Alle andere features zijn vooral nice-to-have...

**Comment by dennissiemensma** [comment]
Redesign van de GUI is momenteel helaas (realistisch gezien) niet mogelijk, dus ik laat dit nu voor wat het is.
