### ISSUE TITLE
API option to get status info

### ISSUE THREAD

**Issue by helmo** [dennissiemensma/dsmr-reader#291]
It would be nice to get the info from the /status page via an API call.

This would make it easier to let a monitoring tool like Nagios check periodically to see if the service is still up and receiving data.

PS: Thanks for doing this... it works/looks pretty cool already.

**Comment by dennissiemensma** [comment]
Thank you for your kind words and this excellent idea. I haven't thought about this yet, but it seems a nice addition for when I'm finishing #230 (working on that a.t.m.).

**Comment by dennissiemensma** [comment]
Toegevoegd voor de volgende release: 

http://dsmr-reader.readthedocs.io/nl/development/api.html#get-application-status

**Comment by dennissiemensma** [comment]
Bedankt voor je scherpte, ik had de 1.20 branch nog niet op mijn eigen productieomgeving gecontroleerd. Bij deze is het gefixt.

**Comment by dennissiemensma** [comment]
Uitgebracht in nieuwe release: https://github.com/dennissiemensma/dsmr-reader/releases/tag/v1.20.0
