### ISSUE TITLE
Verschillende kleuren.

### ISSUE THREAD

**Issue by Michielbaartman** [dennissiemensma/dsmr-reader#294]
Is het ook mogelijk om het dal en piek tarief verschillende kleuren te geven. In het dashboard grafiek zie ik maar een kleur,  in trends zijn er wel twee kleuren

**Comment by dennissiemensma** [comment]
Hoi bedankt voor je melding. 

Dit kan als het goed is in de [interfaceconfiguratie](http://dsmr-reader.readthedocs.io/nl/latest/settings.html#frontend-configuration). Wees er wel van bewust dat het **Dashboard** altijd maar één kleur tegelijkertijd toont, omdat die je *huidige verbruik* neemt en die pakt dus ook altijd je *huidige tarief*.
De applicatie toont in het Dashboard dus *niet de overgang tussen de twee tarieven* (mocht je dat zoeken). :]
