### ISSUE TITLE
Snelheid frontend

### ISSUE THREAD

**Issue by TopdRob** [dennissiemensma/dsmr-reader#301]
Ik draai dsmr-reader op een Raspberry Pi B+. Dat is niet de allersnelste maar ik vroeg me af of bijvoorbeeld het gebruik van node.js i.p.v. nginx als server bijdraagt aan de snelheid van de frontend. Of is het aantebevelen om een snelle Raspberry te gebruiken?

**Comment by dennissiemensma** [comment]
Je kunt in principe elke webserver vóór de applicatie zetten (Nginx stuurt alle applicatie-requests door naar Gunicorn/Supervisor en serveert effectief alleen statische bestanden voor deze app). Sowieso werkt Apache ook, NodJS heb ik geen ervaringen mee.

Ik dacht te menen dat de Pi B+ slechts één CPU heeft. Als dat het geval is vermoed ik dat dát de performance nekt. Dit project vereist namelijk een webserver, applicatieserver, database en óók nog eens 1 a 2 Supervisor-processen. 
Doorgaans is dat te zwaar voor een lichte, enkelvoudige CPU. Om die reden beveel ik minimaal een Pi 2+ aan (ik draai zelf ook op een Pi 2).

Het is overigens mogelijk om de database of applicatie ergens anders te draaien, zodat je alleen nog een datalogger overhoudt.
