### ISSUE TITLE
Trend staafdiagrammen afgelopen week / afgelopen maand altijd gelijk

### ISSUE THREAD

**Issue by dbmnl** [dennissiemensma/dsmr-reader#305]
Het viel mij al een tijdje op dat op de pagina trends de staafdiagrammen altijd exact gelijk zijn. (week / Maand) Ik denk dat de berekening voor beide gelijk zijn aan elkaar. Kan jij daar eens naar kijken? Tnx

![image](https://cloud.githubusercontent.com/assets/24806247/25556050/8e9cc2ac-2cf5-11e7-8d45-0f886aabbfac.png)

**Comment by dennissiemensma** [comment]
Bedankt voor het melden. Ik heb even gekeken en er lijkt inderdaad een foutje in te zitten. De gegevens worden wel goed opgehaald, maar om de een of andere manier gaat het mis bij het tekenen van de grafieken.

Ik zal hier later een fix voor maken die dit oplost.

**Comment by Varsame** [comment]
Hi Dennis, 
Heeft deze bug nog je aandacht? :)

**Comment by dennissiemensma** [comment]
Ik ben als eerste bezig met #9, een langekoesterde wens. Daarna doe ik zeer waarschijnlijk een release met fixes voor de frontend/GUI.

**Comment by dennissiemensma** [comment]
Ik heb de bug gevonden en opgelost voor de volgende release. Nogmaals bedankt voor het melden.

**Comment by dbmnl** [comment]
Wederom bedankt Dennis. 
Ik maak hier graag gebruik van en wacht dus met smart op 1.10.
