### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by HFeenstra** [dennissiemensma/dsmr-reader#308]
Hi Dennis,

Wel nu alles draait heb ik een vraag voor mogelijk in de toekomst:
Zou het mogelijk wezen dat je in de toekomst kunt uitzoomen op de grafiek in de Dashboard?
Nu zie je de laatste 30 minuten, dus 30x 1 minuut per punt/meting.
Mogelijk kun je later uitzoomen en dat de grafiek dan steeds grotere stappen laat zien. Bijvoorbeeld:

1. eerste uitzoom is 5 minuten per punt/meting(dus 30x 5 minuten punt/meting)
2. tweede uitzoom is 10 minuten per punt/meting (dus 30 x 10 minuten punt/meting)
3. derde uitzoom is per 15 minuten per punt/meting (enz..)
4. uitzoom per 30 minuten per punt/meting
5. uitzoom per 60 minuten per punt/meting
6. uitzoom per 3 uur per punt/meting

Kortom dat wanneer je uitzoomt een sneller overzicht krijgt van een langere periode.

Hette Feenstra

**Comment by dennissiemensma** [comment]
Bedankt voor je input. Hier is meerdere keren om gevraagd, dus ik kijk daar zeker in de toekomst naar. Gezien het grote overeenkomsten heeft met de eerdere aanvragen in #235, #189, #213 sluit ik deze. Er zal nog wel wat tijd overheen gaan voordat ik weer aan visuele wijzigingen toekom.
