### ISSUE TITLE
Vragen mbt kopje meterstatistieken

### ISSUE THREAD

**Issue by Bl4ckviper** [dennissiemensma/dsmr-reader#311]
Allereerst mijn complimenten over dit project. Het was super snel up and running op de PI.

Even wat context ik heb een kaifa meter met 3-fase en PV panelen. Heb de dsmr-reader sinds gister avond runnend.

Nu zie ik op de <pi-ip>/statistics pagina bij meterstatistieken het volgende staan:
- Aantal stroomstoringen in alle fases 27
- Aantal langdurige stroomstoringen in alle fases 4

Wat wordt hier mee bedoelt? Er is geen stroomstoring geweest. In de documentatie kon ik hier niets over terug vinden.

Daarnaast vroeg ik mij af of er ergens een lijstje is waaraan gewerkt wordt of gewerkt gaat worden. Ik zag al de vraag mbt de teruglevering terugkomen en de 3 fase grafiek te laten staan. Dit zijn beide dingen waarin ik erg geïnteresseerd ben.

**Comment by dennissiemensma** [comment]
Bedankt voor je ticket. Wat betreft de stroomstoringen, ik weet niet exact hoe ze geteld worden, maar ze komen voort uit de statistieken van je slimme meter. 
Zie de DSMR-specs: [Dutch Smart Meter Requirements v5.0.2 Final P1.pdf](https://github.com/dennissiemensma/dsmr-reader/files/974182/Dutch.Smart.Meter.Requirements.v5.0.2.Final.P1.pdf). Op pagina 20/21 staat alleen '`Number of power failures in any phase`' / '`Number of long power failures in any phase`'. Ik heb die maar overgenomen, maar inhoudelijk weet ik de condities voor het tellen daarvan niet.

Wat betreft de roadmap van het project, deze is gericht op dingen waar de meeste vraag naar is. Momenteel zijn dat #230, die bijna klaar is en dan gereleased wordt in `v1.7`. Daarna #9 en #141 voor `v1.8`. 
Vermoedelijk kan ik mij dan in `v1.9` weer richten op de frontend/grafische zaken, die ik nu even uitstel om bovenstaande tickets eerst af te maken.
