### ISSUE TITLE
Aantal errors tijdens upgrade naar 1.7

### ISSUE THREAD

**Issue by goegol** [dennissiemensma/dsmr-reader#312]
Hoi,

Net de upgrade gedaan. Draait als zonnetje!
Zag wel deze twee errors voorbij komen tijdens upgrade.
Misschien kan je er wat mee.

Installing collected packages: coreapi, django-filter, djangorestframework, coreschema, itypes, uritemplate, jinja2, MarkupSafe
  Running setup.py install for coreapi

    warning: no previously-included files matching '__pycache__' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.pyo' found anywhere in distribution
  Running setup.py install for coreschema

  Running setup.py install for itypes

*** Error compiling '/tmp/pip-build-drfww6ld/jinja2/jinja2/asyncfilters.py'...
  File "/tmp/pip-build-drfww6ld/jinja2/jinja2/asyncfilters.py", line 7
    async def auto_to_seq(value):
            ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip-build-drfww6ld/jinja2/jinja2/asyncsupport.py'...
  File "/tmp/pip-build-drfww6ld/jinja2/jinja2/asyncsupport.py", line 22
    async def concat_async(async_gen):
            ^
SyntaxError: invalid syntax

**Comment by dennissiemensma** [comment]
Dankjewel voor het melden! 

Ik zag ze zelf ook, ze lijken voor te komen in de dependencies die dit project gebruikt. Maar gezien het bij mij ook verder prima draait, laat ik ze voor wat het is. :]
