### ISSUE TITLE
Add web-applicatie mogelijkheid ala pihole

### ISSUE THREAD

**Issue by Jeltel** [dennissiemensma/dsmr-reader#314]
Eigenlijk alle webpagina's kun je met Chrome toevoegen aan je bureaublad. Dat werkt vooral goed op een telefoon/tablet. Er wordt dan bijvoorbeeld geen URL-venster en wel een icoontje. Dan lijkt het alsof je een applicatie draait in plaats van een webpagina.

Kun je dat toevoegen voor DSMR-Reader? 

Zie ook: https://developers.google.com/web/updates/2017/02/improved-add-to-home-screen
en: https://developers.google.com/web/fundamentals/engage-and-retain/app-install-banners/

**Comment by dennissiemensma** [comment]
Bedankt voor je voorstel. Lijkt me een goed iets om mee te nemen, gezien ik dit laatst ook al voor iOS heb toegevoegd.

**Comment by dennissiemensma** [comment]
Ik heb het doorgevoerd voor de volgende release. Lijkt goed te werken op Android 6 (inderdaad zonder adresbalk zoals je aangaf). Bedankt!
