### ISSUE TITLE
Errors in v1.7 installer

### ISSUE THREAD

**Issue by dajappie** [dennissiemensma/dsmr-reader#317]
Hi Dennis,

During the upgrade from v1.6.2 to v1.7 I noticed the following errors executing the deploy.sh:
```
*** Error compiling '/tmp/pip-build-h96s2pqx/jinja2/jinja2/asyncfilters.py'...
  File "/tmp/pip-build-h96s2pqx/jinja2/jinja2/asyncfilters.py", line 7
    async def auto_to_seq(value):
            ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip-build-h96s2pqx/jinja2/jinja2/asyncsupport.py'...
  File "/tmp/pip-build-h96s2pqx/jinja2/jinja2/asyncsupport.py", line 22
    async def concat_async(async_gen):
            ^
SyntaxError: invalid syntax
```
Don't know if these are problematic, but maybe something to check

**Comment by dennissiemensma** [comment]
Thank you for reporting this. The errors are related to some external libraries, which are installed during the upgrade. They can be ignored safely, as it doesn't affect the application and I cannot fix them myself either. :]

See #312 as well.
