### ISSUE TITLE
Datum dashboard past niet automatisch aan

### ISSUE THREAD

**Issue by goegol** [dennissiemensma/dsmr-reader#319]
Hoi,

Als je dashboard meerdere dagen laat open staan (of verwerking van telegrammen lopen achter, en worden weer ingehaald), dan blijft de datum op dashboard staan van vorige dag of (in mijn geval, omdat verwerking was gestopt) op paar dagen geleden.

grafiek en tijd update wel automatisch.
Klein bugje, (of nieuwe feature?) mogelijk helemaal niet de moeite waard om te fixxen
Edit; verbruik en kosten worden ook niet automatisch gerefresht, lijkt op bij design.  Feature request? ;)

Groeten,

Hans-Paul

**Comment by dennissiemensma** [comment]
Bedankt voor het melden. Het is inderdaad 'by design', maar meer in de trend van dat ik er geen rekening mee heb gehouden dat iemand een pagina langer dan 5 minuten o.i.d. open laat staan.

Wellicht dat ik er bij het refactoren van de interface rekening mee kan houden.

**Comment by dennissiemensma** [comment]
Mogelijk neem ik dit mee in de redesign van de applicatie. Sowieso is de datumweergave in het dashboard niet altijd correct (bij achterstand), dus ik mag daar een betere oplossing voor vinden. Voor nu sluit ik deze.
