### ISSUE TITLE
Hardware support/specifications

### ISSUE THREAD

**Issue by dommels** [dennissiemensma/dsmr-reader#322]
Hi,

I have a question regarding hardware support. Is it limited to only Raspberry boards or is any capable board running a debian jessie based OS able to run this software? I would like to run dsmr-reader (dedicated) on an orange pi zero.

**Comment by dennissiemensma** [comment]
Hi, thank you for asking. The software is not limited to any hardware. You should indeed be able to run it on any (Debian) based OS, as long as the software required during the installation is available. 

Feel free to ask for help if you do hit any limitations.
