### ISSUE TITLE
Hoe een update uitvoeren

### ISSUE THREAD

**Issue by HFeenstra** [dennissiemensma/dsmr-reader#324]
Hallo, misschien overbodig, maar kon niet een eerdere vraag hierover vinden, dus toch maar weer zo:
hoe kan ik de meest recente update gaan toepassen? Ik zie dus een nieuwe update, maar heb geen idee hoe deze uit te voeren?
Mogelijk een paar stappen die mij kunnen overhalen om het uit te voeren.

**Comment by dennissiemensma** [comment]
Update-instructies kun je hier vinden: http://dsmr-reader.readthedocs.io/nl/latest/faq.html#how-can-i-update-my-application :]
