### ISSUE TITLE
Aanpassen bashrc bestand

### ISSUE THREAD

**Issue by nelbs** [dennissiemensma/dsmr-reader#327]
Ik heb een korte vraag over de installatie van dsmr reader. In stap 8 wordt aangegeven om een tweetal commands toe te voegen aan het bashrc bestand van de dsmr gebruiker. 

Wordt hiermee gewoon het bashrc bestand in de map pi/home bedoeld? Ik begrijp niet wat ik met de toevoeging "van de dsmr gebruiker" moet. Dit lijkt alsof er meerdere bashrc files zijn?

Bijvoorbaat dank

**Comment by dennissiemensma** [comment]
Bedankt voor je vraag. Ze mogen toegevoegd worden aan de bashrc van de `dsmr` gebruiker zelf. Dit is de bashrc file in het absolute pad `/home/dsmr/.bashrc`. Ofwel ook wel `~/.bashrc` als je ingelogd als `dsmr` gebruiker (dit is hetzelfde bestand).

Als je niet zeker weet welk pad je in welke situatie moet aanpassen, kies dan voor `/home/dsmr/.bashrc`. Aan het einde van hoofdstuk 6 staat tevens aangegeven hoe kan testen of je wijziging goed is doorgevoegd.

Mocht je er desondanks niet uitkomen, dan hoor ik het graag.
