### ISSUE TITLE
Daily Cost calculations

### ISSUE THREAD

**Issue by MJBBRU** [dennissiemensma/dsmr-reader#333]
Something is wrong with the calculation of the daily costs for the electricity.
I entered a price of 0.16661 per kWh.
I used 2.66 kWh but the costs show as €0.15.
Refreshing the page or restarting all the services don't make any difference.

Thanks in advance,

**Comment by dennissiemensma** [comment]
Thank you for reporting this issue. I do need some more information, since I've not experienced this myself yet.

* Can you make a screenshot of it?

**Comment by MJBBRU** [comment]
Here is a screenshot after killing all processes and rebooting the Pi.
It's still not working properly.

![image](https://user-images.githubusercontent.com/25267885/27251406-95e39f46-5346-11e7-9f4b-554ba21fed2f.png)

**Comment by dennissiemensma** [comment]
Thank you for providing the information. I'm not sure how this could happen, some possibilities:

- Did you make sure the start and ending date of the energy prices are within this month?

- You could have the application recalculate all readings again, by deleting the aggregated data. This will **not** affect the readings (source data):
```
sudo su - dsmr
./manage.py dsmr_backend_delete_aggregated_data
```

If you just started using the application, this process will delete the data quickly and I presume the background process will regenerate the data quite fast as well. 
More info here, in the 'Note' block: https://dsmr-reader.readthedocs.io/en/latest/api.html#id2

Let me know if this fixes your problem. If the prices are set correctly, a clean sweep should show valid data.

**Comment by MJBBRU** [comment]
Today I was finally able to check this.
- The start and ending date for the energy prices are correct. (01-2017 to 01-2018)
- Recalculation of the readings with the command line you sent didn't work

An error showed up that the commandline needs to be extended with  --ack-to-delete-my-data 
(or something)
By doing this I think that all data is gone :(
I killed all processes and rebooted the raspberry but I still get this screen.
![image](https://user-images.githubusercontent.com/25267885/27489302-55113d86-583a-11e7-95d1-d7f722de29aa.png)

For now I will see how the calculations are going.
I'll keep you informed.

Thanks so far

**Comment by dennissiemensma** [comment]
I see I forget to mention the 'ack' parameter. It's to prevent people from randomly trying commands.

You can safely execute the `./manage.py dsmr_backend_delete_aggregated_data --ack-to-delete-my-data` command. 
It will **not** delete the readings (source data), but it will delete all data calculated from the readings, such as the day totals and costs. It will basically reset all stats and start from the beginning, while using the readings stored so far.

See also #328 and [this comment](https://github.com/dennissiemensma/dsmr-reader/issues/328#issuecomment-307013093) for more info.

**Comment by dennissiemensma** [comment]
@MJBBRU did my last comment fix your issue?

**Comment by MJBBRU** [comment]
Everything is working fine now.
Thanks!

![afbeelding](https://user-images.githubusercontent.com/25267885/27882554-62b56f6a-61cd-11e7-8e61-048c08f697da.png)
