### ISSUE TITLE
Python Error

### ISSUE THREAD

**Issue by FutureCow** [dennissiemensma/dsmr-reader#336]
Ik gok dat dit een "persoonlijk" probleem is. Nadat er een package update was van Python krijg ik de volgende foutmelding:
```  File "/home/dsmr/.virtualenvs/dsmrreader/bin/pip3", line 7, in <module>
    from pip import main
  File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.5/site-packages/pip/__init__.py", line 26, in <module>
    from pip.utils import get_installed_distributions, get_prog
  File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.5/site-packages/pip/utils/__init__.py", line 19, in <module>
    import zipfile
  File "/usr/lib/python3.5/zipfile.py", line 9, in <module>
    import importlib.util
  File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.5/importlib/util.py", line 7, in <module>
    from ._bootstrap_external import MAGIC_NUMBER, _BACKCOMPAT_MAGIC_NUMBER
ImportError: cannot import name '_BACKCOMPAT_MAGIC_NUMBER'
```
De versie van Python die ik gebruik: 
Python 3.5.3rc1 (default, Jan  3 2017, 04:40:57)
[GCC 6.3.0 20161229] on linux

Hoe zou ik dit kunnen oplossen?

**Comment by dennissiemensma** [comment]
Het lijkt erop dat er een Release Candidate (rc1) geinstalleerd is. Mogelijk zit er nog een bug in die release of iets. 

Ik kan je alleen aanraden om een stabiele Python 3 versie te installeren. De foutmelding lijkt namelijk ook betrekking te hebben op `importlib`, iets buiten dit project om.
Zelf gebruik ik Python 3.4 in productie en ontwikkel ik in Python 3.5.2. Een van die twee versies zou moeten werken. Mocht het daarna nog niet werken, dan hoor ik het graag. :]
