### ISSUE TITLE
Show combined low+high tariff value

### ISSUE THREAD

**Issue by helmo** [dennissiemensma/dsmr-reader#340]
It would be nice to have the sum of the low and high tariff on both the dashboard and the archive pages.
Not that the math is that difficult ;) but it's just easier to compare the daily or monthly usage that way.

Here's a mockup:
![selection_117](https://user-images.githubusercontent.com/104120/27762778-98418ff4-5e78-11e7-9adf-300fc98f7938.png)

From a usability perspective it might be a bit confusing combined with the 'Total' row ... I'm open to suggestions.

**Comment by dennissiemensma** [comment]
Thank you for your suggestion. Did you also try [merging the tariffs](https://dsmr-reader.readthedocs.io/en/latest/settings.html#merge-electricity-tariffs)?

 It's not quite the same, but it sums up the totals everywhere. It's a interface-only feature, so it shouldn't affect any data read and can be turned off again any time.

**Comment by helmo** [comment]
An html change was enough ... while experimenting a bit I ended up with:![selection_118](https://user-images.githubusercontent.com/104120/27770036-40568d1a-5f38-11e7-83c7-15db1d833f9f.png)

**Comment by helmo** [comment]
The merge function is a reasonable workaround ... but I'm interested in both.

**Comment by dennissiemensma** [comment]
Merged #341
