### ISSUE TITLE
Backup to dropbox never finish (free plan no more space)

### ISSUE THREAD

**Issue by joopy** [dennissiemensma/dsmr-reader#342]
Hi,
I have version 1.8 running. My dropbox account was full, no more free space. The DSMR program keeps trying to backup (+- 30MB). So in 1 day I got a alarm from my monitoring software that my raspberry was using 50GB bandwith a day. Networkscanner reveals my raspberry was doing dropbox request.

Can you build in a check that when dropbox account is full, backup will be paused?

**Comment by goegol** [comment]
Already upgrade to version 1.8.1?
There was an issue with the dropbox client in dmsr.

**Comment by dennissiemensma** [comment]
Thank you for reporting this! The application does not check the quota available, but it definitely should. I will fix this in a future release.

**Comment by dennissiemensma** [comment]
The v1.8.1 patch was only for #339, due to a heads up of Dropbox that the API will change in two months, so unrelated to this issue.

**Comment by joopy** [comment]
Thnx Dennis

**Comment by dennissiemensma** [comment]
Even lokaal getest, ik kan een melding maken op basis van een ruwe matching op `insufficient_space` in de fout:
```
ApiError('x', UploadError('path', UploadWriteFailed(reason=WriteError('insufficient_space', None), upload_session_id='x')))
```

En dan tevens de backups pauzeren voor een (halve) dag.

**Comment by joopy** [comment]
Lijkt mij prima Dennis!

**Comment by dennissiemensma** [comment]
Gemerged naar `development` voor de volgende release.

**Comment by dennissiemensma** [comment]
Uitgebracht in [v1.15](https://github.com/dennissiemensma/dsmr-reader/releases/tag/v1.15.0).
