### ISSUE TITLE
Teruggeleverd wordt niet meegenomen in kosten

### ISSUE THREAD

**Issue by vgouw** [dennissiemensma/dsmr-reader#343]
De Kosten (€) zoals weergegeven bij Elektriciteit 2 (piektarief) houd geen rekening met het Teruggeleverd (kWh) . Ik zou verwachten dat hier een negatief bedrag zou staan ipv van 0,10€
![dsmrreader_kostenteruglevering](https://user-images.githubusercontent.com/7560921/27965201-443d124e-633b-11e7-9501-ee1d2d0951e4.png)

**Comment by dennissiemensma** [comment]
Bedankt voor het melden van dit issue. Het is overigens een bekend iets, er staat ook al #163 voor om het terugleveren uberhaupt goed te verwerken. Wegens de salderingsregeling en verschillende teruglevertarieven, kan ik er (nog) niet van uitgaan dat dezelfde prijs gebruikt wordt voor teruglevering. Daarvoor is meer nopig.

Ik raad je aan om #163 in de gaten te houden. Deze staat overigens niet voor de korte termijn op de planning.

**Comment by dennissiemensma** [comment]
Opgepakt in #163. Zie hier hieronder voor een voorbeeld met fictieve getallen en (onrealistische) bedragen:

![screenshot from 2017-09-28 20-01-30](https://user-images.githubusercontent.com/16581744/30982504-e35facaa-a487-11e7-89c6-abefa62269e9.png)
