### ISSUE TITLE
Feature request - Water consumption monitoring

### ISSUE THREAD

**Issue by PeterEIER** [dennissiemensma/dsmr-reader#345]
It would be awesome if DSMR-Reader could also show me my water consumption (which I now monitor in a separate application). I monitor total water usage, daily water usage and actual water flow rate.

Small extensions to DMSR-Reader its API or MQTT functionality could make this possible I guess.

**Comment by dennissiemensma** [comment]
Hi, thank you for your suggestion! 

This project however is limited to DSMR only. So I won't integrate other data sources, but I do support exporting the data or DSMR-reader to other sources (such as via the API or MQTT).

See similar requests in #209 and #297 as well.
