### ISSUE TITLE
Question: Is mSATA SSD supported?

### ISSUE THREAD

**Issue by PeterEIER** [dennissiemensma/dsmr-reader#353]
Hi,

already mentioned is the fact that SDcards will not last forever... especially with a DSMR 5 meter which produces a telegram every second I guess this will be the case... this is why I am looking into an alternative in the form of an mSATA pi head together with a  32GB mSATA SSD. An yes, I realise that SSD's do also not last forever...

This is what I am looking at....

https://nl.aliexpress.com/item/HUALLY-MSATA-MSATA2-SSD-Most-Competitive-Series-8GB-16GB-32GB-Solid-State-Disk-Drive-Hard-Disk/32800457114.html?spm=a2g0z.search0104.3.41.FVfedd&ws_ab_test=searchweb0_0,searchweb201602_1_10152_10065_10151_10068_10209_10304_10307_10301_10137_10060_10155_10154_10333_10334_10056_10335_10055_10336_10054_10059_10332_100031_10099_10103_10102_10052_10053_10142_10107_10050_10051_10326_10084_10083_10080_10082_10081_10177_10110_10111_10112_10113_10114_10312_10313_10314_10078_10079_10210_10073-normal#cfs,searchweb201603_21,ppcSwitch_7&btsid=a89dfcea-018b-48db-b02d-d9d5ed13f582&algo_expid=1fab6072-57e9-4d86-90f8-796c5568098b-5&algo_pvid=1fab6072-57e9-4d86-90f8-796c5568098b&transAbTest=ae803_3

https://nl.aliexpress.com/item/Raspberry-Pi-3-Model-B-mSATA-SSD-Storage-Expansion-Board-X850-USB-3-0-Expansion-Board/32817586840.html?spm=a2g0z.search0104.3.1.lxNu7a&ws_ab_test=searchweb0_0,searchweb201602_1_10152_10065_10151_10068_10209_10304_10307_10301_10137_10060_10155_10154_10333_10334_10056_10335_10055_10336_10054_10059_10332_100031_10099_10103_10102_10052_10053_10142_10107_10050_10051_10326_10084_10083_10080_10082_10081_10177_10110_10111_10112_10113_10114_10312_10313_10314_10078_10079_10210_10073-10332_10333,searchweb201603_21,ppcSwitch_7&btsid=aaf7b79a-162e-44c1-a0eb-9d068f4cb885&algo_expid=ebd1b2c7-b004-4058-8d5a-bea299e3c747-0&algo_pvid=ebd1b2c7-b004-4058-8d5a-bea299e3c747&transAbTest=ae803_3

**Comment by dennissiemensma** [comment]
Thank you for your question. The SD cards can indeed wear off quickly when running this application. I just replaced my initial card, after running it for 16 months or so.
The project was designed while only DSMR v4 was around, so the amount of telegrams sent by DSMR v5 is something I still have to find a solution for.

I don't think it really matters what kind of disk you are using to 'solve' that problem. Either HDD or SSD is fine. I also heard good stories about "WD PiDrive", but I'm still using an SD card myself, so I can't vouch for it.
If you even happen to have a server/VPS running somewhere, I would even recommend installing the application there.
