### ISSUE TITLE
Postgress still busy after +- 300.000 telegrams

### ISSUE THREAD

**Issue by joopy** [dennissiemensma/dsmr-reader#355]
There where +-300.000 unprocessed telegrams (~ 4 weeks). After raspberry pi 2 reboot processing started. After ~ 35 hours al telegrams where processed.

Still slow Raspberry, htop reveals postgress is still doing magic. So for more dan 3 day's I have a almost 90% cpu with postgress.

psql statistics:
postgres-# order by pg_database_size(datname) desc;
  datname   | pg_size_pretty
------------+----------------
 dsmrreader | 499 MB
 postgres   | 6516 kB
 template1  | 6417 kB
 template0  | 6409 kB
(4 rows)

984 | -00:00:00.782917 | dsmrreader | COMMIT
 1036 | -00:00:17.485937 | dsmrreader | SELECT "dsmr_datalogger_dsmrreading"."id", "dsmr_datalogger_dsmrreading"."timestamp", "dsmr_datalogger_dsmrreading"."electricity_delivered_1", "dsmr_datalogger_dsmrreading"."electricity_returned_1", "dsmr_datalogger_dsmrreading"."electricity_delivered_2", "dsmr_datalogger_dsmrreading"."electricity_returned_2", "dsmr_datalogger_dsmrreading"."electricity_currently_delivered", "dsmr_datalogger_dsmrreading"."electricity_currently_returned", "dsmr_datalogger_dsmrreading"."phase_currently_delivered_l1", "dsmr_datalogger_dsmrreading"."phase_currently_delivered_l2", "dsmr_datalogger_dsmrreading"."phase_currently_delivered_l3", "dsmr_datalogger_dsmrreading"."extra_device_timestamp", "dsmr_datalogger_dsmrreading"."extra_device_delivered", "dsmr_datalogger_dsmrreading"."processed" FROM "dsmr_datalogger_dsmrreading" WHERE "dsmr_datalogger_dsmrreading"."processed" = false ORDER BY "dsmr_datalogger_dsmrreading"."timestamp" ASC LIMIT 1024

SELECT max(now() - xact_start) FROM pg_stat_activity WHERE state IN ('idle in transaction', 'active');
       max
-----------------
 00:00:01.036794
(1 row)

Any Idea's? Running second to last DSMR version

**Comment by dennissiemensma** [comment]
I asume you have tried restartingall  the supervisor processes? Or the entire system?

**Comment by joopy** [comment]
Ja de raspberry heeft meerdere keren een reboot gekregen denk 2 keer. Maar het is nog steeds erg druk zo druk dat de webserver het niet trekt. Enig idee dennis?

**Comment by dennissiemensma** [comment]
- Welke processen zie je dan als je `SELECT pid, datname, usename, query_start, query FROM pg_stat_activity;` doet?

- En als je op de command line dit doet, wat staat daar allemaal bij? `sudo ps faux | grep postg`

- Mocht je daar nog niets bijzonders in zien, wellicht kun je het zien aan de systemcalls die het betreffende (90% cpu) proces doet met: `strace -p PID` (PID = process ID)

**Comment by joopy** [comment]
Systeem krijgt iets meer lucht. Heb de pingdom check extern eraf gehaald. Niet elke x min de site opvragen.

**Comment by dennissiemensma** [comment]
Maar verder dus niet gezien welke queries of processen er uitgevoerd worden?

**Comment by joopy** [comment]
Thanks voor de hulp. Zonder elke min een pingdom check trekt de Raspberry het prima.

* Welke processen zie je dan als je SELECT pid, datname, usename, query_start, query FROM pg_stat_activity; doet?

 pid  |  datname   |  usename   |          query_start          |                                                                                                                                                                                                                                                                                                                                                                                                                                                                  query                                                                                                                                                                                                                                                                                                                                                                                                                                      
------+------------+------------+-------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 3653 | dsmrreader | dsmrreader | 2017-09-15 20:04:16.138601+00 | SELECT "dsmr_datalogger_dataloggersettings"."id", "dsmr_datalogger_dataloggersettings"."track", "dsmr_datalogger_dataloggersettings"."track_phases", "dsmr_datalogger_dataloggersettings"."verify_telegram_crc", "dsmr_datalogger_dataloggersettings"."dsmr_version", "dsmr_datalogger_dataloggersettings"."com_port" FROM "dsmr_datalogger_dataloggersettings" WHERE "dsmr_datalogger_dataloggersettings"."id" = 1
 3658 | dsmrreader | dsmrreader | 2017-09-15 20:04:22.064633+00 | SELECT "dsmr_consumption_electricityconsumption"."id", "dsmr_consumption_electricityconsumption"."read_at", "dsmr_consumption_electricityconsumption"."delivered_1", "dsmr_consumption_electricityconsumption"."returned_1", "dsmr_consumption_electricityconsumption"."delivered_2", "dsmr_consumption_electricityconsumption"."returned_2", "dsmr_consumption_electricityconsumption"."currently_delivered", "dsmr_consumption_electricityconsumption"."currently_returned", "dsmr_consumption_electricityconsumption"."phase_currently_delivered_l1", "dsmr_consumption_electricityconsumption"."phase_currently_delivered_l2", "dsmr_consumption_electricityconsumption"."phase_currently_delivered_l3" FROM "dsmr_consumption_electricityconsumption" WHERE "dsmr_consumption_electricityconsumption"."read_at" > '2017-09-15T00:00:00+02:00'::timestamptz ORDER BY "dsmr_consumption_electricityconsumption"."read_at" ASC LIMIT 1
 3683 | dsmrreader | dsmrreader | 2017-09-15 20:02:13.882119+00 | SELECT "dsmr_datalogger_meterstatistics"."id", "dsmr_datalogger_meterstatistics"."timestamp", "dsmr_datalogger_meterstatistics"."dsmr_version", "dsmr_datalogger_meterstatistics"."electricity_tariff", "dsmr_datalogger_meterstatistics"."power_failure_count", "dsmr_datalogger_meterstatistics"."long_power_failure_count", "dsmr_datalogger_meterstatistics"."voltage_sag_count_l1", "dsmr_datalogger_meterstatistics"."voltage_sag_count_l2", "dsmr_datalogger_meterstatistics"."voltage_sag_count_l3", "dsmr_datalogger_meterstatistics"."voltage_swell_count_l1", "dsmr_datalogger_meterstatistics"."voltage_swell_count_l2", "dsmr_datalogger_meterstatistics"."voltage_swell_count_l3", "dsmr_datalogger_meterstatistics"."rejected_telegrams" FROM "dsmr_datalogger_meterstatistics" WHERE "dsmr_datalogger_meterstatistics"."id" = 1
 3735 | postgres   | postgres   | 2017-09-15 20:04:21.994661+00 | SELECT pid, datname, usename, query_start, query FROM pg_stat_activity;
(4 rows)


root@raspberrypi:~# sudo ps faux | grep postg
root      3764  0.0  0.4   4264  2012 pts/1    S+   20:05   0:00                          \_ grep postg
postgres   657  0.0  4.0 161044 18056 ?        S    18:48   0:00 /usr/lib/postgresql/9.4/bin/postgres -D /var/lib/postgresql/9.4/main -c config_file=/etc/postgresql/9.4/main/postgresql.conf
postgres   811  0.0  2.0 161144  8948 ?        Ss   18:48   0:00  \_ postgres: checkpointer process
postgres   812  0.0  1.1 161044  5060 ?        Ss   18:48   0:00  \_ postgres: writer process
postgres   813  0.0  1.8 161044  8284 ?        Ss   18:48   0:00  \_ postgres: wal writer process
postgres   814  0.0  1.2 161328  5696 ?        Ss   18:48   0:00  \_ postgres: autovacuum launcher process
postgres   815  0.0  0.8  18564  3868 ?        Ss   18:48   0:02  \_ postgres: stats collector process
postgres  3653  0.3  2.8 162028 12472 ?        Ss   19:57   0:01  \_ postgres: dsmrreader dsmrreader ::1(36574) idle
postgres  3658  4.6  4.1 162076 18328 ?        Ss   19:58   0:19  \_ postgres: dsmrreader dsmrreader ::1(36576) idle
postgres  3683  0.3  3.8 162520 17256 ?        Ss   20:01   0:00  \_ postgres: dsmrreader dsmrreader ::1(36584) idle

root@raspberrypi:~# strace -p 3641
Process 3641 attached
rt_sigprocmask(SIG_BLOCK, [PIPE], [], 8) = 0
write(7, "\27\3\3\0\362\230\235\3743\376\322\210\0367\257#\30\312\310\36\303\335yJ\303I\304\214\31B\362\311"..., 247) = 247
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
poll([{fd=7, events=POLLIN|POLLERR}], 1, -1) = 1 ([{fd=7, revents=POLLIN}])
rt_sigprocmask(SIG_BLOCK, [PIPE], [], 8) = 0
read(7, "\27\3\3\0\366", 5)             = 5
read(7, "\316\276\24[\265\225\vny%\255J\22\26d5\304\256M?\357X`o2\277EDVW-w"..., 246) = 246
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
gettimeofday({1505505970, 210315}, NULL) = 0
rt_sigprocmask(SIG_BLOCK, [PIPE], [], 8) = 0
write(7, "\27\3\3\0016\230\235\3743\376\322\210\37M\354\367\25\252\233\21\266\242F#\352\235 \362\\V\315s"..., 315) = 315
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
poll([{fd=7, events=POLLIN|POLLERR}], 1, -1) = 1 ([{fd=7, revents=POLLIN}])
rt_sigprocmask(SIG_BLOCK, [PIPE], [], 8) = 0
read(7, "\27\3\3\0\265", 5)             = 5
read(7, "\316\276\24[\265\225\vo\263e\33\326\357e\302\343\251\261}\346\35z\vw\371:\345\250\316\372je"..., 181) = 181
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, [PIPE], [], 8) = 0
write(7, "\27\3\3\1\242\230\235\3743\376\322\210 \313\250\332\233\10_\261\314\364\220\204\325A\235\371w\246b\343"..., 423) = 423
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
poll([{fd=7, events=POLLIN|POLLERR}], 1, -1) = 1 ([{fd=7, revents=POLLIN}])
rt_sigprocmask(SIG_BLOCK, [PIPE], [], 8) = 0
read(7, "\27\3\3\1+", 5)                = 5
read(7, "\316\276\24[\265\225\vp\320`\233\23|iS\331\201\0o\24\2\303\271+\27\364\306k4 \350A"..., 299) = 299
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
gettimeofday({1505505970, 285712}, NULL) = 0
write(1, "Command completed. Sleeping for "..., 47) = 47
write(1, "\n", 1)                       = 1
select(0, NULL, NULL, NULL, {1, 0})     = 0 (Timeout)
gettimeofday({1505505971, 311433}, NULL) = 0
write(1, "2017-09-15 22:06:11.311433+02:00"..., 59) = 59
rt_sigprocmask(SIG_BLOCK, [PIPE], [], 8) = 0
write(7, "\27\3\3\3\307\230\235\3743\376\322\210!\330\232\226\225*G\220\374\266?\16mG\241'\5\203<y"..., 972) = 972
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
poll([{fd=7, events=POLLIN|POLLERR}], 1, -1) = 1 ([{fd=7, revents=POLLIN}])
rt_sigprocmask(SIG_BLOCK, [PIPE], [], 8) = 0
read(7, "\27\3\3\3\7", 5)               = 5
read(7, "\316\276\24[\265\225\vq\373\2534\261\24\244\261Z\366\356\36\342\7Y&\265d\27S\22P\344\342k"..., 775) = 775
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, [PIPE], [], 8) = 0
write(7, "\27\3\3\0\364\230\235\3743\376\322\210\"\222R \325\f\nU(\252\240\30j\312%OO\20W["..., 249) = 249
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
poll([{fd=7, events=POLLIN|POLLERR}], 1, -1) = 1 ([{fd=7, revents=POLLIN}])
rt_sigprocmask(SIG_BLOCK, [PIPE], [], 8) = 0
read(7, "\27\3\3\0\203", 5)             = 5
read(7, "\316\276\24[\265\225\vrw@fP\243\235lX\20\377\326\313\206',\342\17\n\237\332\244v\7\355"..., 131) = 131
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
gettimeofday({1505505971, 433023}, NULL) = 0
rt_sigprocmask(SIG_BLOCK, [PIPE], [], 8) = 0
write(7, "\27\3\3\1#\230\235\3743\376\322\210#\33\372\v:\213Y:=\312\254\365\241\4\233\235\177\335\362/"..., 296) = 296
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
poll([{fd=7, events=POLLIN|POLLERR}], 1, -1) = 1 ([{fd=7, revents=POLLIN}])
rt_sigprocmask(SIG_BLOCK, [PIPE], [], 8) = 0
read(7, "\27\3\3\0\324", 5)             = 5
read(7, "\316\276\24[\265\225\vs\2348Uya\4\363\3132\232u\300\263\202\371/\17\375\t\300\365\30e~"..., 212) = 212
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
gettimeofday({1505505971, 471559}, NULL) = 0
rt_sigprocmask(SIG_BLOCK, [PIPE], [], 8) = 0
write(7, "\27\3\3\2\342\230\235\3743\376\322\210$-5&an\352\266\304\6\267\247\302f\221\2{\2\233\327"..., 743) = 743
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
poll([{fd=7, events=POLLIN|POLLERR}], 1, -1) = 1 ([{fd=7, revents=POLLIN}])
rt_sigprocmask(SIG_BLOCK, [PIPE], [], 8) = 0
read(7, "\27\3\3\2t", 5)                = 5
read(7, "\316\276\24[\265\225\vta#\256\372\0046\224\336\245{\373\335\215\17p@\377\16\376m\265\376BQ"..., 628) = 628
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, [PIPE], [], 8) = 0
write(7, "\27\3\3\3\246\230\235\3743\376\322\210%\313F\340%\357\327\3468\341#\200\234\232\217\207?\322\332\10"..., 939) = 939
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
poll([{fd=7, events=POLLIN|POLLERR}], 1, -1) = 1 ([{fd=7, revents=POLLIN}])
rt_sigprocmask(SIG_BLOCK, [PIPE], [], 8) = 0
read(7, "\27\3\3\2#", 5)                = 5
read(7, "\316\276\24[\265\225\vu\243@\204\364\v\2565=\257\331\0\33PeCU>\256\216A\217v\203#"..., 547) = 547
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
gettimeofday({1505505971, 575857}, NULL) = 0
rt_sigprocmask(SIG_BLOCK, [PIPE], [], 8) = 0
write(7, "\27\3\3\1D\230\235\3743\376\322\210&he\4\316/\363#\343\376S\5\312d\241\375h>\v'"..., 329) = 329
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
poll([{fd=7, events=POLLIN|POLLERR}], 1, -1) = 1 ([{fd=7, revents=POLLIN}])
rt_sigprocmask(SIG_BLOCK, [PIPE], [], 8) = 0
read(7, "\27\3\3\1\3", 5)               = 5
read(7, "\316\276\24[\265\225\vv\3727P\276\0376\351\2\1V\0028>\320\333\306]\264`\320\31\323\273\350"..., 259) = 259
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
gettimeofday({1505505971, 617504}, NULL) = 0
rt_sigprocmask(SIG_BLOCK, [PIPE], [], 8) = 0
write(7, "\27\3\3\0\362\230\235\3743\376\322\210'&\36\1\210\235?\212\3403\235\247\203q\253\204\255Z\335\266"..., 247) = 247
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
poll([{fd=7, events=POLLIN|POLLERR}], 1, -1) = 1 ([{fd=7, revents=POLLIN}])
rt_sigprocmask(SIG_BLOCK, [PIPE], [], 8) = 0
read(7, "\27\3\3\0\366", 5)             = 5
read(7, "\316\276\24[\265\225\vwy\224\0355YGD\325\341\271\357\240)\0369g\\q\270\357\315\235O\313"..., 246) = 246
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
gettimeofday({1505505971, 654635}, NULL) = 0
rt_sigprocmask(SIG_BLOCK, [PIPE], [], 8) = 0
write(7, "\27\3\3\0016\230\235\3743\376\322\210(\360\231k\27\355\r$\215\312\334'(\247r\321\363\260\177\371"..., 315) = 315
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
poll([{fd=7, events=POLLIN|POLLERR}], 1, -1) = 1 ([{fd=7, revents=POLLIN}])
rt_sigprocmask(SIG_BLOCK, [PIPE], [], 8) = 0
read(7, "\27\3\3\0\265", 5)             = 5
read(7, "\316\276\24[\265\225\vxv\250\340N\32\314\252\0\215\367\22\223D\361q\325\277\250\232\353+\333O+"..., 181) = 181
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, [PIPE], [], 8) = 0
write(7, "\27\3\3\1\242\230\235\3743\376\322\210)fl\322\207\261#]+)\326\t\24$\377n6\342|~"..., 423) = 423
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
poll([{fd=7, events=POLLIN|POLLERR}], 1, -1) = 1 ([{fd=7, revents=POLLIN}])
rt_sigprocmask(SIG_BLOCK, [PIPE], [], 8) = 0
read(7, "\27\3\3\1+", 5)                = 5
read(7, "\316\276\24[\265\225\vy\34\263]\vp\327\330\314I\t6\350z\334\fCl\35P-\"P\222`"..., 299) = 299
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
gettimeofday({1505505971, 729833}, NULL) = 0
write(1, "Command completed. Sleeping for "..., 47) = 47
write(1, "\n", 1)                       = 1
select(0, NULL, NULL, NULL, {1, 0})     = 0 (Timeout)
gettimeofday({1505505972, 755546}, NULL) = 0
write(1, "2017-09-15 22:06:12.755546+02:00"..., 59) = 59
rt_sigprocmask(SIG_BLOCK, [PIPE], [], 8) = 0
write(7, "\27\3\3\3\307\230\235\3743\376\322\210*\340\232\221>[\34Y\361\201\267\363\214\243H%\301\316\353b"..., 972) = 972
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
poll([{fd=7, events=POLLIN|POLLERR}], 1, -1) = 1 ([{fd=7, revents=POLLIN}])
rt_sigprocmask(SIG_BLOCK, [PIPE], [], 8) = 0
read(7, "\27\3\3\3\7", 5)               = 5
read(7, "\316\276\24[\265\225\vz\374\252!\365g\1L\257)\366\365\321q\352\354\27\236\377\350\276\nw\355K"..., 775) = 775
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, [PIPE], [], 8) = 0
write(7, "\27\3\3\0\364\230\235\3743\376\322\210+\326/`\310.jV\205\264\\$\255]\254\r;\201\377\200"..., 249) = 249
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
poll([{fd=7, events=POLLIN|POLLERR}], 1, -1) = 1 ([{fd=7, revents=POLLIN}])
rt_sigprocmask(SIG_BLOCK, [PIPE], [], 8) = 0
read(7, "\27\3\3\0\203", 5)             = 5
read(7, "\316\276\24[\265\225\v{u\222\30\351\310\336?B\6n\250\232\217b\223\210\223\252\314\212>\31l'"..., 131) = 131
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
gettimeofday({1505505972, 878467}, NULL) = 0
rt_sigprocmask(SIG_BLOCK, [PIPE], [], 8) = 0
write(7, "\27\3\3\1#\230\235\3743\376\322\210,W\306\25\301\212]\344\225\220\234\214w\177!\212\313\375\356\214"..., 296) = 296
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
poll([{fd=7, events=POLLIN|POLLERR}], 1, -1) = 1 ([{fd=7, revents=POLLIN}])
rt_sigprocmask(SIG_BLOCK, [PIPE], [], 8) = 0
read(7, "\27\3\3\0\324", 5)             = 5
read(7, "\316\276\24[\265\225\v|I\263WD\320\267U\324T\343\1\335\25\2002\332\26<\215\306\215\345\\\356"..., 212) = 212
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
gettimeofday({1505505972, 918872}, NULL) = 0
rt_sigprocmask(SIG_BLOCK, [PIPE], [], 8) = 0
write(7, "\27\3\3\2\342\230\235\3743\376\322\210-\213\310C\25bX<\30k\v\247b W\203\235-\n\30"..., 743) = 743
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
poll([{fd=7, events=POLLIN|POLLERR}], 1, -1) = 1 ([{fd=7, revents=POLLIN}])
rt_sigprocmask(SIG_BLOCK, [PIPE], [], 8) = 0
read(7, "\27\3\3\2t", 5)                = 5
read(7, "\316\276\24[\265\225\v}\271\242\276\307\255s\223\330!\345`U0\257\266\361\334r\300\2t\4\316\223"..., 628) = 628
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, [PIPE], [], 8) = 0
write(7, "\27\3\3\3\246\230\235\3743\376\322\210.\310)(\316\305+\205R\24\f\206\355Q\375\260\31\233\25\363"..., 939) = 939
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
poll([{fd=7, events=POLLIN|POLLERR}], 1, -1) = 1 ([{fd=7, revents=POLLIN}])
rt_sigprocmask(SIG_BLOCK, [PIPE], [], 8) = 0
read(7, "\27\3\3\2#", 5)                = 5
read(7, "\316\276\24[\265\225\v~\356\244\3354\21S\277\201\360\271\372'\262\201\211\232\1t\17\354\177\336\177\362"..., 547) = 547
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
gettimeofday({1505505973, 25548}, NULL) = 0
rt_sigprocmask(SIG_BLOCK, [PIPE], [], 8) = 0
write(7, "\27\3\3\1D\230\235\3743\376\322\210/\177K\322\233\317\220\267\27\3616I\216\265\351\30\177\370\304\202"..., 329) = 329
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
poll([{fd=7, events=POLLIN|POLLERR}], 1, -1) = 1 ([{fd=7, revents=POLLIN}])
rt_sigprocmask(SIG_BLOCK, [PIPE], [], 8) = 0
read(7, "\27\3\3\1\3", 5)               = 5
read(7, "\316\276\24[\265\225\v\177\315>TR\315\16\252\203Da\331\3138\377\"\366j\6C\7{\213\236\310"..., 259) = 259
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
gettimeofday({1505505973, 65808}, NULL) = 0
rt_sigprocmask(SIG_BLOCK, [PIPE], [], 8) = 0
write(7, "\27\3\3\0\362\230\235\3743\376\322\2100\260\17~xp\347RM0\305\372\323\22\351\325e\20\320\30"..., 247) = 247
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
poll([{fd=7, events=POLLIN|POLLERR}], 1, -1) = 1 ([{fd=7, revents=POLLIN}])
rt_sigprocmask(SIG_BLOCK, [PIPE], [], 8) = 0
read(7, "\27\3\3\0\366", 5)             = 5
read(7, "\316\276\24[\265\225\v\200\313f\34\341-\2079\34>\305\261Z\336\207R>\260\255\333\375\302\212A\323"..., 246) = 246
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
gettimeofday({1505505973, 110169}, NULL) = 0
rt_sigprocmask(SIG_BLOCK, [PIPE], [], 8) = 0
write(7, "\27\3\3\0016\230\235\3743\376\322\2101EA7L_\5\374\221\21\214:L\337\344\3103\252a\256"..., 315) = 315
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
poll([{fd=7, events=POLLIN|POLLERR}], 1, -1) = 1 ([{fd=7, revents=POLLIN}])
rt_sigprocmask(SIG_BLOCK, [PIPE], [], 8) = 0
read(7, "\27\3\3\0\265", 5)             = 5
read(7, "\316\276\24[\265\225\v\201\273\227P\263\315y\265\364\257\254\0\22\374*\276V\324\3PD\243{;\322"..., 181) = 181
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, [PIPE], [], 8) = 0
write(7, "\27\3\3\1\242\230\235\3743\376\322\2102`\t3\353iFu\213\253=\264\337W\24\222\rJ\334C"..., 423) = 423
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
poll([{fd=7, events=POLLIN|POLLERR}], 1, -1) = 1 ([{fd=7, revents=POLLIN}])
rt_sigprocmask(SIG_BLOCK, [PIPE], [], 8) = 0
read(7, "\27\3\3\1+", 5)                = 5
read(7, "\316\276\24[\265\225\v\202\315\377G\337\320\273'\256\244\235[O\327\33\377\306\214\345\244\331N\306\206\255"..., 299) = 299
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
gettimeofday({1505505973, 195395}, NULL) = 0
write(1, "Command completed. Sleeping for "..., 47) = 47
write(1, "\n", 1)                       = 1
select(0, NULL, NULL, NULL, {1, 0}^CProcess 3641 detached
 <detached ...>

**Comment by dennissiemensma** [comment]
Oke, wellicht was het dan iets te veel met dat pingdom erbij. Ik zie geen vreemde zaken als ik even snel een blik werp.
