### ISSUE TITLE
Gestapelde staafdiagramen in Archief en Vergelijk

### ISSUE THREAD

**Issue by vgouw** [dennissiemensma/dsmr-reader#360]
Issue
In "Archief" en "Vergelijk" worden  lijn-grafieken gebruikt.  ik ben van mening dat:
- De lijn-grafiek onterecht een verloop aangeeft, terwijl het absolute/totaal uur/dag/maand waardes zijn 
- Voor elektriciteit is elk tarief apart getoond. Hierdoor is het moeilijk om weekend-dagen (alleen laag tarief) te vergelijken met niet weekend-dagen (normaal en laag tarief)

Voorstel
Gebruik gestapelde staaf diagrammen voor "Archief" en "Vergelijk"

**Comment by dennissiemensma** [comment]
Bedankt voor je input! Mogelijk neem ik het mee voor #236, wanneer ik daar aan toekom. Deze staat sowieso niet voor de korte termijn op de agenda.

**Comment by dennissiemensma** [comment]
Momenteel sluit ik diverse issues in bulk, waaronder deze. Realistisch gezien kom ik hier de komende tijd niet (meer) aan toe, gezien mijn beschikbare tijd aanzienlijk is afgenomen én ik afdoende werk heb met het debuggen van issues waar men tegenaan loopt. 

En ik besteed liever wat meer tijd aan de kern van dit project: Ervoor zorgen dat gebruikers op zoveel mogelijk manieren bij hun data kunnen (export, MQTT, etc.). Alle andere features zijn vooral nice-to-have...

**Comment by dennissiemensma** [comment]
Zoals in gerelateerde tickets: redesign zie ik niet zo 1-2-3 gebeuren voorlopig.
