### ISSUE TITLE
Pvoutput upload zonder teruglevering

### ISSUE THREAD

**Issue by arvdsar** [dennissiemensma/dsmr-reader#370]
Hi,
vandaag de DSMR Reader geinstalleerd en het werkt prima. Enige is dat het uploaden naar PVoutput niet lukt als er geen teruglevering wordt geregistreerd.

Ik heb wel een slimme meter maar geen zonnepanelen (meer). De upload naar PVoutput kreeg ik niet werkend totdat ik een handmatige aanpassing deed in /dsmr_pvoutput/services.py
onderstaande code heb ik uitgecommentarieerd.

`
if not capabilities['electricity_returned']:
     print(' - [!] PVOutput | No electricity return recorded by application!')
    return False
`

Kun je hier ook een optie van maken in de user interface? 

Groet,
Alexander

**Comment by dennissiemensma** [comment]
Bedankt voor het melden, dit is een bug. In een eerdere iteratie voor de PVOuput-integratie was nog sprake van het uploaden van netto teruglevering. Dat is later gewijzigd naar alleen nette verbruik, dus deze check hoort er uberhaupt niet meer in.

**Comment by dennissiemensma** [comment]
Ik heb het aangepast voor de volgende release.

**Comment by dennissiemensma** [comment]
`v1.11` is [gereleased](https://github.com/dennissiemensma/dsmr-reader/releases/tag/v1.11.0), inclusief dit ticket.
