### ISSUE TITLE
Nieuwe meter

### ISSUE THREAD

**Issue by TopdRob** [dennissiemensma/dsmr-reader#376]
Hoi Dennis,

Mijn slimme meter is vervangen voor een andere en die begint nu weer op 0. Is het mogelijk om de standen van de nieuwe meter op te hogen met de standen van de oude meter? Ik heb nu een negatief verbruik?

Bedankt,
Robert

**Comment by dennissiemensma** [comment]
Zie #242. Ik heb hier momenteel nog geen oplossing voor.

Als het goed is krijg je de dag erna wél de goede standen (hij kijkt telkens naar de voorgaande dag). Vervolgens zou je in de admin-interface eenmalig handmatig de foutieve dag kunnen corrigeren (zul je zelf even moeten rekenen).

**Comment by dennissiemensma** [comment]
@TopdRob is bovenstaande gelukt?

**Comment by TopdRob** [comment]
Hoi @dennissiemensma,

Bedankt voor je hulp. Ik heb de dag op 0 gezet en daarmee is het opgelost!

**Comment by dennissiemensma** [comment]
Top!
