### ISSUE TITLE
SUGGESTIE - Automatisch installatie script

### ISSUE THREAD

**Issue by wesley9946** [dennissiemensma/dsmr-reader#380]
Hallo,

Is het misschien een goed idee om een automatisch installatie script te maken?
Scheelt een hele hoop getyp/copypasten :]

**Comment by dennissiemensma** [comment]
Bedankt voor je suggestie, ik heb daar momenteel al #203 voor. Je kunt die eventueel volgen wanneer die opgepakt wordt. :]
