### ISSUE TITLE
Total NOOB question about REST API

### ISSUE THREAD

**Issue by casperleenheer** [dennissiemensma/dsmr-reader#383]
Hi Dennis,

I'm a total NOOB around REST and the API calls. I want to get some measurements from dsmr-reader by sending an url. I only don't know how to add the authentication (X_HEADER) to the url. So basically one url in my browser should give me the result. By the way, very nice product.

Thanks,

Casper

**Comment by dennissiemensma** [comment]
Ik denk niet dat je het via de browser kan doen, maar je kunt wel een plugin/app gebruiken zoals `Postman`. 
Daarin kun je namelijk naast een URL, ook headers opgeven. Er is tevens ondersteuning voor het uitlijnen van de API response (JSON).

![selection_006](https://user-images.githubusercontent.com/16581744/32983470-6612d14c-cc95-11e7-9886-4b43f5992a95.png)

**Comment by casperleenheer** [comment]
Dank je wel voor het antwoord. Ik heb het alsnog op een andere manier opgelost.
