### ISSUE TITLE
Gas meterstand via API

### ISSUE THREAD

**Issue by casperleenheer** [dennissiemensma/dsmr-reader#384]
Is het mogelijk om via de API de gasmeterstand uit te lezen? Ik zie alleen maar calls voor elektriciteit. Zie ik iets over het hoofd?

Alvast bedankt,

Casper

**Comment by dennissiemensma** [comment]
De rauwe meterstanden staan in `dsmrreading`. 

http://dsmr-reader.readthedocs.io/nl/latest/api.html#get-datalogger-dsmrreading

* `extra_device_delivered` is de meterstand
* `extra_device_timestamp` is het tijdstip, volgens de gasmeter
