### ISSUE TITLE
Feature Request: Ondersteuning voor zonnepanelen

### ISSUE THREAD

**Issue by casperleenheer** [dennissiemensma/dsmr-reader#388]
Op het ogenblik lees ik in openhab via een YouLess mijn opbrengst van mijn zonnepanelen uit. Voorheen (nu dus via de api van dsmr-reader) las ik ook mijn P1 port uit. Met deze gegevens calculeer ik mijn bruto verbruik ( BrutoVerbruik = BrutoProductie - LeveringHoog - LeveringLaag + VerbruikHoog + VerbruikLaag ) waarbij BrutoProductie de zonnecellen opbrengt is. Op deze manier weet ik tenminste wat ik echt aan stroom verbruik. Het zou mooi zijn deze gegevens ook in dsmr-meter te hebben. Vandaar dit verzoek.

**Comment by dennissiemensma** [comment]
Bedankt voor je verzoek. Je bent niet de eerste die dit graag zou willen, maar ik beperk dit project/de applicatie tot de gegevens die uit de slimme meter komt. Daarom bouw ik dit niet in.

Ik bied overigens wel ondersteuning voor het exporteren van de gegevens uit DSMR-reader naar zoveel mogelijk bronnen (MinderGas, PVOutput, CSV, API). In jouw geval zou je PVOutput kunnen proberen. 

Als ik het goed lees heeft Youless ondersteuning voor het exporteren van de opbrengst en DSMR-reader heeft ondersteuning voor het exporteren van het verbruik. Je zou dan in PVOutput e.e.a. moeten kunnen inzien qua bruto-gegevens.

Zie http://www.youless.nl/blogpost/items/pvoutput.html en ticket #9.

(Ik heb zelf overigens geen zonnepanelen dus ik kan je er inhoudelijk niet mee helpen)
