### ISSUE TITLE
Gas- en elektriciteitsverbruik vanaf start energie contract

### ISSUE THREAD

**Issue by tpjanssen** [dennissiemensma/dsmr-reader#390]
Is het een idee om het gas- en elektriciteitsverbruik (en terug levering) te kunnen monitoren vanaf de start van je huidige energiecontract?

**Comment by dennissiemensma** [comment]
Wat bedoel je exact met monitoren? Doel je op het kunnen selecteren wat je verbruik was tijdens een specifieke periode?

**Comment by tpjanssen** [comment]
Precies! Dus het verschil in meterstanden tussen nu en een zelf te bepalen datum in het verleden.

**Comment by dennissiemensma** [comment]
Oke duidelijk, lijkt me een goede toevoeging. Ik zet hem op de backlog.

**Comment by dennissiemensma** [comment]
Ik heb een opzet gemaakt voor een aparte pagina waar **alle contracten** getoond worden, inclusief de prijzen en het verbruik binnen die periode. Volgens mij is dat een mooie toevoeging, nog iets uitgebreider dan de wens in dit ticket. Dat hoeven we ook niet zelf datums gaan selecteren.

Hieronder twee screenshots met wat testdata voor een voorbeeld:
![energy contracts dsmr reader - google chrome_013](https://user-images.githubusercontent.com/16581744/41174066-50fe5638-6b59-11e8-8e33-e1b82ef9df5f.png)

![energy contracts dsmr reader - google chrome_014](https://user-images.githubusercontent.com/16581744/41174067-511dea98-6b59-11e8-810e-5f6089d86467.png)

**Comment by dennissiemensma** [comment]
Gemerged naar `development` voor volgende release.

**Comment by tpjanssen** [comment]
Mooi! Enig idee wanneer de volgende release komt?

**Comment by dennissiemensma** [comment]
Bij deze in [v1.19](https://github.com/dennissiemensma/dsmr-reader/releases/tag/v1.19.0).
