### ISSUE TITLE
restart dsmr_backend

### ISSUE THREAD

**Issue by HFeenstra** [dennissiemensma/dsmr-reader#393]
Hoi, eind oktober 2017 en nu eind november 2017 opnieuw zie ik dat de dsmr_backend vast loopt.
Ik heb 1.11 geïnstalleerd maar het valt me op dat ik nu opnieuw deze moet herstarten.
Zie verder geen enkele foutmelding op de frontpage van de pagina, dus daar kan ik ook niets terugvinden.
Heb vervolgens als: `sudo supervisorctl` en `restart dsmr_backend` het weer aan de praat gekregen. 
edit: zie zojuist dat het proces na 2/3 minuten opnieuw stopte. Begint nu vreemd te worden.

Hebben meer hier last van? 1.9 en daarvoor, gebeurde dit nooit bij mij....

**Comment by dennissiemensma** [comment]
Wat geeft de logfile aan?

**Comment by HFeenstra** [comment]
Zou dit graag delen, maar weet niet hoe ik deze te voorschijn kan krijgen. Hoe deze uit te lezen? Middels welk programma?

**Comment by dennissiemensma** [comment]
Zie http://dsmr-reader.readthedocs.io/nl/latest/troubleshooting.html

Je kunt doorgaans `view LOGFILE`, `tail -n 100 LOGFILE` of `cat LOGFILE` gebruiken op de commandline. Of `tail -f LOGFILE` om de logfile te monitoren terwijl die gevuld wordt. Waarbij LOGFILE de betreffende log is.

**Comment by dennissiemensma** [comment]
Ben je nog iets wijzer geworden uit de logs?
