### ISSUE TITLE
Connect to Postgres database on non-standard port

### ISSUE THREAD

**Issue by arvdsar** [dennissiemensma/dsmr-reader#395]
Hi,
I like to move the postgres database of my raspberry pi and use it within a Docker container on my Synology. The default postgres port 5432 is in use by Synology and therefore I need to use another port for the database.
Withing settings.py I can change the localhost to the IP of the database server (synology), but how can I configure another port?

Thanks,
Alex

**Comment by dennissiemensma** [comment]
De instelling heet simpelweg [`PORT` (docs)](https://docs.djangoproject.com/en/1.11/ref/settings/#port).

Je kunt hem toevoegen aan de bestaande structuur binnen `settings.py`:

```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', DSMRREADER_NAME),
        'USER': os.environ.get('DB_USER', DSMRREADER_USER),
        'PASSWORD': os.environ.get('DB_PASS', DSMRREADER_PASSWORD),
        'HOST': os.environ.get('DB_HOST', DSMRREADER_HOST),
        'PORT': 5432,
        'CONN_MAX_AGE': os.environ.get('CONN_MAX_AGE', DSMRREADER_CONN_MAX_AGE),
    }
}
```

**Comment by arvdsar** [comment]
Bedankt!! Het werkt inmiddels!

**Comment by xirixiz** [comment]
Hi Dennis,

Would it be possible to add the following to the correct sections? It would save a lot of hustle in Docker.

```'PORT': os.environ.get('DB_PORT', DSMRREADER_PORT),```

```DSMRREADER_PORT=5432"

and perhaps add
```DSMRREADER_BACKEND_SLEEP=<default value>```

**Comment by Simanias** [comment]
Ik probeer ook mijn postgreSQL database te migreren naar een andere remote VM.
Ik heb de settings.py aangepast als volgt:


```
<knip>
```


Maar nadat ik het ./manage.py migrate commando uitvoer, krijg ik de volgende melding:

```
<knip>

  File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.6/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.close_at = None if max_age is None else time.monotonic() + max_age
TypeError: unsupported operand type(s) for +: 'float' and 'str'
```

Ergens doe ik iets niet, goed maar waar?

**Comment by dennissiemensma** [comment]
Dit is een heel oud issue en daarmee outdated. Tegenwoordig staan de instellingen in `.env` (of envvars bij Docker), overzicht staat hier: https://dsmr-reader.readthedocs.io/en/latest/env_settings.html#django-settings-overrides

**Comment by xirixiz** [comment]
En het hangt er uiteraard vanaf of je ook in Docker draait of niet.
