### ISSUE TITLE
Enkel tarief elektriciteit: gecombineerd tarief tonen op 'Statistieken'-pagina

### ISSUE THREAD

**Issue by jorisvervuurt** [dennissiemensma/dsmr-reader#396]
Wij maken gebruik van een enkel tarief voor de verbruikte elektriciteit. In de interface-configuratie heb ik 'Voeg tarieven samen' aangevinkt en bij de tarieven van de energieleverancier hetzelfde bedrag ingevuld voor zowel dal- als piektarief.

Op de 'Dashboard'-pagina wordt netjes één tarief 'Elektriciteit (enkel tarief)' getoond.
Op de 'Statistieken'-pagina worden echter twee losse tarieven getoond.

Als ik het goed begrijp, registreert de meter - ongeacht of je voor enkel tarief kiest - twee losse tarieven. Het is dus wel interessant om op de 'Statistieken'-pagina de twee gescheiden tarieven te kunnen zien. Bij het handmatig doorgeven van de meterstanden, moet ik de twee losse tarieven bij elkaar optellen.

Is het mogelijk om op de 'Statistieken'-pagina naast de twee losse tarieven, ook een gecombineerd tarief te tonen (onder de naam 'Elektriciteit 3 (dal- en piektarief gecombineerd)' bijvoorbeeld)? Simpelweg een optelling van de geregistreerde dal- en piektarieven dus. ;-)

**Comment by dennissiemensma** [comment]
Bedankt voor je verzoek. Als ik het goed begrijp doel je dus op het eerste blokje op die pagina, betreffende de meterstanden? En die wil je bij elkaar opgeteld hebben?

**Comment by jorisvervuurt** [comment]
Dat is inderdaad wat ik bedoel. 😉 

Nu ziet het er zo uit:
![schermafbeelding 2017-12-07 om 19 24 10](https://user-images.githubusercontent.com/13164041/33731827-a99e9c54-db84-11e7-92c2-866caa2948e0.png)

Zoiets lijkt mij ideaal:
![schermafbeelding 2017-12-07 om 19 25 48](https://user-images.githubusercontent.com/13164041/33731873-cd54aea4-db84-11e7-8bd4-471f3762c7f6.png)

**Comment by dennissiemensma** [comment]
Oke bedankt voor de opheldering, duidelijk!

**Comment by dennissiemensma** [comment]
Gaat mee in volgende release.

**Comment by jorisvervuurt** [comment]
Top!

**Comment by dennissiemensma** [comment]
De betreffende release is zojuist uitgebracht.
