### ISSUE TITLE
Veel calls naar api.buienradar

### ISSUE THREAD

**Issue by dbmnl** [dennissiemensma/dsmr-reader#399]
Hoi Dennis,

Sinds deze week heeft Pi-Hole een functie om verder terug in het verleden te kijken in plaats van slechts 24 uur geleden. Toen ik echter ging kijken voor de afgelopen dagen vielen mij 2 spikes op.
![spikes api buienradar](https://user-images.githubusercontent.com/24806247/33804013-c2b2474e-dd9c-11e7-87bf-f494557850a9.PNG)

Bij nader onderzoek bleken dit calls naar api.buienradar te zijn. Het enige hier in huis wat een call doet hier naartoe is dsmrreader op zowel IPv4 als IPv6. Maar het aantal is aan de hoge kant en wel heel vaak achter elkaar.
![calls api buienradar](https://user-images.githubusercontent.com/24806247/33804026-eacc989c-dd9c-11e7-9933-7b0189d0349a.PNG)

Vermoedelijk zal dit komen doordat api.buienradar niet beschikbaar is, maar het is natuurlijk onnodig om dan 1000 calls te doen :)

Kan jij hier eens naar kijken of mij laten weten of je nog meer informatie nodig hebt. Ik zat al te kijken in de logs directory, maar zie dat de dsmrreader.log voor het laatst op 19 oktober is bijgewerkt. In de logfile van django staat niets relevants. En bij supervisor logs kan ik ook geen relevante informatie vinden of foutmeldingen.

**Comment by dennissiemensma** [comment]
Bedankt voor het melden. Ik zal er foutafhandeling in bouwen zodat die het pas na 5 minuten opnieuw probeert.

**Comment by dennissiemensma** [comment]
Ik heb er een mogelijke fix voor gemaakt voor de volgende release.

**Comment by dennissiemensma** [comment]
Zojuist uitgebracht in [release v1.12](https://github.com/dennissiemensma/dsmr-reader/releases/tag/v1.12.0).
