### ISSUE TITLE
Lost django password

### ISSUE THREAD

**Issue by RemcoLeonard** [dennissiemensma/dsmr-reader#402]
Is there a way to change the username/password for the configuration page?
I lost them.....

**Comment by jeroenpeters1986** [comment]
Hi @RemcoLeonard, if you want; you can create a new admin user by following this instruction https://dsmr-reader.readthedocs.io/en/latest/installation.html?highlight=createsuperuser#bootstrapping, starting from 'Create an application superuser.'

**Comment by dennissiemensma** [comment]
See the lnik Jeroen wrote above, it should help you. Let us know if you still have trouble creating a superuser account.

**Comment by VincentSC** [comment]
For new version it's possible to change the password of the default user 'dsmr'. See https://dsmr-reader.readthedocs.io/en/latest/installation/explained.html and search for "changepassword".

Log in as user `dsmr`, go to the directory `dsmr-reader` and run:
> dsmr@raspberrypi:~/dsmr-reader $ `./manage.py changepassword admin`
