### ISSUE TITLE
Spelling correction trends page

### ISSUE THREAD

**Issue by mkruiver** [dennissiemensma/dsmr-reader#406]
On the trends page there is mention of "PASSED WEEK" & "PASSED MONTH" where it should be past week & past month. Further up on the same page it is written correctly (past four weeks).

**Comment by dennissiemensma** [comment]
Dankje, ik zal het aanpassen.

**Comment by dennissiemensma** [comment]
Gaat mee met de volgende release, bedankt voor je scherpte.

**Comment by dennissiemensma** [comment]
Zojuist uitgebracht in [release v1.12](https://github.com/dennissiemensma/dsmr-reader/releases/tag/v1.12.0).
