### ISSUE TITLE
Enable power generation

### ISSUE THREAD

**Issue by Martinvdm** [dennissiemensma/dsmr-reader#409]
Hi,

I do not get any values for Power Generation. Have enabled DSMR2.2 and working fine for Power Consumption. For Generation it gives: No data.

Should i enable this somewhere?

**Comment by dennissiemensma** [comment]
Hi, ik neem aan dat je dit allemaal hebt ingesteld: http://dsmr-reader.readthedocs.io/nl/latest/pvoutput.html ?

Je zou anders nog in de logs kunnen kijken van het `dsmr_backend` proces. Daar zou sowieso elke X minuten informatie voorbij moeten komen over PVOuput, wanneer correct ingesteld. Elke data upload wordt gemeld met: ` - PVOutput | Uploading data @ ...`

Je kunt dit zien in de logfile `/var/log/supervisor/dsmr_backend.log` (http://dsmr-reader.readthedocs.io/nl/latest/troubleshooting.html)

**Comment by Martinvdm** [comment]
Morgen nog eens kijken, maar het lijkt erop dat het even een uurtje nodig had om het telraam in DSMR reader te activeren. Als ik morgen weer opwek ga ik nog eens kijken.

**Comment by Martinvdm** [comment]
Helaas is de Power Generation nog steeds 0
![aaaa](https://user-images.githubusercontent.com/1952661/34460926-6a1a6e9a-ee1d-11e7-9a8a-5c80bafc572d.png)

**Comment by dennissiemensma** [comment]
Ooh sorry ik dacht dat dit over PVOutput ging. In dat geval zul je de output van je slimme meter moeten controleren.

Zou je eens willen kijken wat je telegrammen zijn in de output van `/var/log/supervisor/dsmr_datalogger.log` (als je de standaard datalogger gebruikt)?

Ter vergelijking, bij mij heb ik deze waardes:

```
...
1-0:1.8.1(002440.944*kWh)
1-0:2.8.1(000000.000*kWh)
1-0:1.8.2(002386.725*kWh)
1-0:2.8.2(000000.000*kWh)
...
```

De `1-0:2.8.1` en `1-0:2.8.2` is de teruglevering. Zijn die bij jou wel aanwezig, en gevuld?

**Comment by Martinvdm** [comment]
Working just fine now. Wans't sunny enough to activate the meter and consuming all generated power in the house it self! Great project, thanks for all the effort. 👍

**Comment by dennissiemensma** [comment]
Top, bedankt voor je feedback.
