### ISSUE TITLE
DSMR 5.x wordt elke seconde uitgelezen.

### ISSUE THREAD

**Issue by BBasss** [dennissiemensma/dsmr-reader#415]
Mijn slimme meter heeft het 'nieuwe' DSMR 5 protocol waardoor elke seconde een meting wordt doorgegeven. Dit komt omdat de RTS van de P1 kabel altijd "hoog" is waardoor de meter continu data blijft doorgeven. Dit is natuurlijk voor normaal gebruik een enorme overkill.

Is er een mogelijkheid om de uitleesfrequentie in te stellen naar bv. elke 10 sec. ?

Ciao, Bas

(Dit is m'n eerste Github bericht ever..... , als ik mij niet geheel aan alle etiquette heb gehouden bij voorbaat sorry daarvoor ;-))

**Comment by dennissiemensma** [comment]
Hi, bedankt voor je vraag.

Heel toevallig liep iemand daar deze week ook tegenaan. In de aankomende release is daar een setting voor gemaakt. Voor nu kun je het met de hand aanpassen (en bij updaten zul je de wijzigingen moeten resetten.

Zie #413 voor hoe dit exact aangepast kan worden. Als je er niet uitkomt, hoor ik het graag. Vergeet niet `./reload.sh` uit te voeren na je wijzigingen.
