### ISSUE TITLE
Aanpassing grafiek type

### ISSUE THREAD

**Issue by Helloitsme** [dennissiemensma/dsmr-reader#416]
Hallo Dennis

Allereerst (nogmaals) dank voor het handige programma. Het draait inmiddels al meer dan een jaar zonder problemen bij me.

Ik zou wel graag een aanpassing in het type grafieken willen zien omdat het met lijngrafieken lastig is om het totaal te zien. Een (stacked) kolomgrafiek is daar handig voor (naar mijn bescheiden mening :-) )

zie plaatjes 

huidig

![huidig](https://user-images.githubusercontent.com/2877375/34646936-251e6d02-f375-11e7-99e0-5b23f6d35bce.JPG)

gewenst type (het gaat me niet direct om de details zoals kleuren etc)

![gewenst](https://user-images.githubusercontent.com/2877375/34646945-51c753c8-f375-11e7-9456-0ec540949484.JPG)

**Comment by dennissiemensma** [comment]
Bedankt voor je input. Ik heb je verzoek voor nu opgenomen in het algemene ticket, voor het op de schop gooien van de complete UI: #236
