### ISSUE TITLE
Requests for donating a beer or coffee

### ISSUE THREAD

**Issue by dennissiemensma** [dennissiemensma/dsmr-reader#425]
Some people have (recently) expressed their grattitude and wish to support this project in a financial way. 

Even though this project will always be free to use, and I already make an okay living with my full time job, I will allow donators to simply "buy me a beer or coffee", if they really wish to.

**Comment by dennissiemensma** [comment]
Toegevoegd aan docs.

**Comment by mkruiver** [comment]
Waar dan?

**Comment by dennissiemensma** [comment]
Dit staat pas klaar voor de volgende release. 

Er is echter ook altijd een schaduw-versie van de documentatie beschikbaar, die gebouwd wordt vanaf de `development` branch (reflectie van de elke aankomende release): https://dsmr-reader.readthedocs.io/nl/development/
