### ISSUE TITLE
More options for outside temperature

### ISSUE THREAD

**Issue by hsleewis** [dennissiemensma/dsmr-reader#433]
It would be awesome if there would be more options to fetch the weather data for the outside temperature. Right now my install is looking at a weather station that's over 30km's away and I see big differences in temperatures. Last night I measured -4.5 at one point. The weather station my DSMR install is looking at reported +1,5 at the lowest.

https://www.wunderground.com/weather/api?MR=1 is quite a good one, only have to create a developer account to be able to use it. :)

**Comment by dennissiemensma** [comment]
Bedankt voor je verzoek! Ik heb hier in 2016 ook al naar gekeken (#49) en heb toen besloten om het niet in te bouwen. 
Daarnaast focus ik dit project op het uitlezen van de slimme meter en het exporteren van die data (CSV, API, MQTT). De import van andere gegevens laat ik voor wat het is (zoals PV-omvormers, maar ook weergegevens). Ik begrijp van jouw perspectief dat het een mooie integratie zou zijn geweest. :]
