### ISSUE TITLE
Problem installing dsmr-reader at step 8

### ISSUE THREAD

**Issue by raoulteeuwen** [dennissiemensma/dsmr-reader#440]
Hello.

First of all: thank you for creating & maintaining dsmr-reader!

I'm a Linux-newbie and ran into some trouble trying to do everything as in http://dsmr-reader.readthedocs.io/en/latest/installation.html to install dsmr-reader on my Rpi3 with Hassbian.

But for now i think i was able to fix it. So no problems to report, just saying thank you :-).

Kindest regards,

Raoul.

**Comment by dennissiemensma** [comment]
Hallo Raoul, bedankt voor je vriendelijke woorden. Mocht je desondanks toch nog hulp nodig hebben, dan hoor ik het graag.
