### ISSUE TITLE
Kosten via MQTT

### ISSUE THREAD

**Issue by Baseje** [dennissiemensma/dsmr-reader#447]
De support voor MQTT is fantastisch,
Alleen zou ik ook de kosten wel via MQTT willen uitlezen middels home-assistant.

**Comment by dennissiemensma** [comment]
Bedankt voor je verzoek, dat lijkt me een goede toevoeging.

**Comment by dennissiemensma** [comment]
Op welke kosten doel je trouwens? De dagtotalen? Want dan zou dit een goede aanvulling zijn voor #367

**Comment by dennissiemensma** [comment]
Ik doe dit via #367

**Comment by dennissiemensma** [comment]
Uitgebracht in de [nieuwe release](https://github.com/dennissiemensma/dsmr-reader/releases/tag/v1.14.0).
