### ISSUE TITLE
Meterstatistieken via MQTT beschikbaar

### ISSUE THREAD

**Issue by f0nt4** [dennissiemensma/dsmr-reader#449]
Zoals besproken in https://github.com/dennissiemensma/dsmr-reader/issues/367 zou ik graag de meterstatistieken via MQTT kunnen verzenden waarbij het mij in eerste instantie om de "Electricity tariff" gaat zodat ik in Home Assistant kan weergeven wat het huidige tarief is.

**Comment by dennissiemensma** [comment]
@f0nt4 ik heb een opzet voor je gemaakt. Wil je eens proberen of dat afdoende voor je werkt? Het is toegevoegd als metere categorie 'meter statistieken per split topic' onder alle MQTT instellingen.

Testen kan met:
```
sudo su - dsmr
git fetch
git checkout -b 449-datalogger-statistics-via-mqtt origin/449-datalogger-statistics-via-mqtt
./deploy.sh
```

**Comment by f0nt4** [comment]
@dennissiemensma Getest en lijkt allemaal te werken! :)
https://i.imgur.com/Jj3vral.png

**Comment by dennissiemensma** [comment]
Oke top, bedankt! Ik neem aan dat dat niet de waarden zijn die ik zie, maar iets anders? Tarief hoort 1 of 2 te zijn.

**Comment by f0nt4** [comment]
Klopt, dat zijn het aantal ontvangen mqtt berichten.

**Comment by dennissiemensma** [comment]
Top, dan zal ik dit straks terugmergen naar de algemene development branch.

**Comment by dennissiemensma** [comment]
Gemerged

**Comment by f0nt4** [comment]
Cool, thanks!

**Comment by dennissiemensma** [comment]
Ik probeer elke X aantal weken wat te releasen, maar je kunt rustig op deze branch blijven, of wisselen naar `development`. Daar zit die al in.

**Comment by f0nt4** [comment]
I see. Ik draai de applicatie in Docker, dus dat iets minder simpel dan gezegd :P

**Comment by dennissiemensma** [comment]
Uitgebracht in [v1.15](https://github.com/dennissiemensma/dsmr-reader/releases/tag/v1.15.0).

**Comment by f0nt4** [comment]
Cool en thanks! Ik heb de docker-compose Dockerfile geüpdated.
