### ISSUE TITLE
Omnik-data in dsmr-reader

### ISSUE THREAD

**Issue by raoulteeuwen** [dennissiemensma/dsmr-reader#451]
Ik heb Home Assistant draaien en een Omnik als omvormer voor mijn zonnepanelen. Vooralsnog heb ik nu https://github.com/cyberjunky/home-assistant-custom-components#solarportal-sensor-component gebruikt om gegevens uit te lezen en te tonen in HA. Zou die data ook in DSRM in te lezen zijn en daar te tonen (en evt naar PVOUTPUT te uploaden)...?

**Comment by dennissiemensma** [comment]
Hallo Raoul, bedankt voor je verzoek. Dit project is helaas qua scope beperkt tot alleen het uitlezen van de slimme meter (en het exporteren van die gegevens naar andere systemen toe). 

Wanneer je gegevens van je zonnepanelen wilt delen met PVOutput, dan zul je dat via je omvormer moeten doen. 
Sommige omvormers ondersteunen volgens mij een koppeling daar naar toe. Vervolgens zou je in DSMR-reader je verbruik kunnen laten exporteren en dat tegen elkaar plotten in PVOutput. Voor meer informatie zou je ticket #9 kunnen bekijken.
