### ISSUE TITLE
Geen metingen meer na vervangen kabel

### ISSUE THREAD

**Issue by eterpstra** [dennissiemensma/dsmr-reader#456]
Hoi Dennis,

Sinds ik de kabel heel even uit de slimme meter moest halen doet DSMR reader geen metingen meer.
sudo supervisorctl restart all heb ik getest en gereboot maar helaas komt er niks meer binnen.

Enige idee wat ik hieraan kan doen ?

Gr,
Elroy

**Comment by eterpstra** [comment]
Laat maar... Kabel zat er niet goed in haha ! Sorry1

**Comment by dennissiemensma** [comment]
Kan gebeuren :]
