### ISSUE TITLE
Opwekking laat gehele opwek zien

### ISSUE THREAD

**Issue by trekker25** [dennissiemensma/dsmr-reader#460]
Als ik altijd goed begreep dan merkt de slimme meter niet wat er gebeurd tussen de opwekking en wat je op dat moment gebruikt in je huis.

Echter als ik bij mij kijk staat er bij Dashboard:
380 watt rood (verbruik) 1820 watt groen (opwek)

ga ik bij mijn omvormer kijken wordt er ook echt nagenoeg precies 1820 opgewekt.

Kan het zijn omdat ik 3 fase heb dat wel alle opwek geregistreerd wordt?
Kan ik dan ook per dag de gehele opwek bekijken? Op dit moment doet die toch alleen de echte terug levering zien bij de dag statistieken.

**Comment by dennissiemensma** [comment]
Ik kan je hier helaas geen antwoord op geven. Mijn thuissituatie heeft helaas geen zonnepanelen of een omvormer en ik ben ook geen expert op dat gebied.

* De applicatie weergeeft als het goed is simpelweg wat de meter aangeeft (je zou even kunnen dubbelchecken of de applicatie overeenkomt met wat je slimme meter op de display weergeeft).

* Ik weet dus niet of er verschil is met 3 fasen. Ik heb thuis alleen drie fasen verbruik en dat lijkt te kloppen, als in, alles wordt op een stapel gegooid door de meter)

* De slimme meter houdt alleen de totale meterstanden bij, dus wat je in de applicatie ziet is wat je de hele dag hebt teruggeleverd aan het net (**waar je verbruik dus al gedeeltelijk in verwerkt kan zijn, afhankelijk van de stroomvraag in je huis tijdens het opwekken van de stroom**). Om te zien wat je daadwerkelijk opwekt, zul je deze gegevens uit je omvormer moeten halen. Mogelijk ondersteunt die zelfs PVOutput, zie ticket #9 voor meer informatie daarover.
