### ISSUE TITLE
Donatie

### ISSUE THREAD

**Issue by krijnenr** [dennissiemensma/dsmr-reader#464]
In verband met privacy maak ik geen gebruik van PayPal.

Wellicht een idee om Patreon als donatie mechanisme toe te voegen.
https://www.patreon.com

**Comment by dennissiemensma** [comment]
Bedankt voor je idee en heel begrijpelijk dat je geen Paypal gebruikt!

Ik heb destijds wel gekeken naar Patreon, maar ik kon daar niet zo 1-2-3 iets vinden voor eenmalige donaties. Daarom heb ik het maar bij Paypal gehouden.
