### ISSUE TITLE
PVO uploadtijden in sync houden

### ISSUE THREAD

**Issue by mkruiver** [dennissiemensma/dsmr-reader#467]
Op het moment dat mij PV productie een beetje dipt, wolk ofzo, raporteert PVO dit niet alleen als een dip in PV productie, maar ook als een piek in consumptie. Omdat ik zeker weet dat de consumptie niet daadwerkelijk - bijvoorbeeld - 500W kan zijn, is hier iets fout.

![image](https://user-images.githubusercontent.com/3832319/38871879-4993cbc4-4252-11e8-8f42-7dfcc7b41cf1.png)

![image](https://user-images.githubusercontent.com/3832319/38871920-6036d1e6-4252-11e8-89d9-08ef887259da.png)

Zou dit komen door het middelen van PVO en de bijbehorende netto berekening? Dus omdat de aangeleverde data over een 5min timeslot eigenlijk een iets te hoge 'generation' geeft voor een bepaald moment, wordt dit gecompenseerd door de netto berekening door het 'consumption' iets te verhogen? Of gaat er danwel in de meter, danwel in DSMR iets fout?

Als mijn pv productie constant, of laag is, treedt dit issue niet op.

![image](https://user-images.githubusercontent.com/3832319/38872132-d0a498f0-4252-11e8-8d7d-19ddaf6b21c0.png)

![image](https://user-images.githubusercontent.com/3832319/38872205-febf3dd0-4252-11e8-9988-d90888230475.png)

https://www.pvoutput.org/intraday.jsp?id=54637&sid=49673&dt=20180321&gs=0&m=0

### Jouw omgeving
* DSMR-reader versie : `v1.15` (maar data van 1.14 en eerder laat hetzelfde gedrag zien)
* Hardware Pi3
* DSMR-protocol versie van slimme meter : `v5`

**Comment by mkruiver** [comment]
Het DSMR dashboard laat niet hetzelfde zien, deze staat strak op 0 verbruik, ook bij dipjes.

**Comment by dennissiemensma** [comment]
Bedankt voor je issue. Het is voor mij lastig om te zeggen waar dit misgaat, omdat ik niet weet hoe PVOutput zaken berekent/weergeeft en DSMR-reader niet expliciet logt wat die opstuurt.

Wellicht dat ik hiervoor het beste wat extra debug logging kan inbouwen zodat exact te zien is wat die naar PVOutput stuurt en waar die gegevens vandaan komen. 

Je zou zelf nog wel kunnen kijken naar de records in `dsmr_consumption_electricityconsumption`, waar de gegevens vandaan komen. En dan expliciet naar de velden `currently_delivered` en `currently_returned` rond dat tijdstip van de dipjes.

```
sudo su - postgresql
psql dsmrreader

# - Pas tijdstip/datum aan in query.
# - Let op, tijdzone in DB is standaard UTC, dus momenteel onze tijd -2 uur.
select * from dsmr_consumption_electricityconsumption where read_at between '2018-04-01 12:45:00'::timestamp and '2018-04-01 13:00:00'::timestamp;
```

Hij doet `net_power = last.currently_delivered - last.currently_returned` en dan `net_power * 1000` die hij upload naar PVOutput (in Watt).

**Comment by dennissiemensma** [comment]
@mkruiver ben je in de tussentijd nog wat wijzer geworden? 

Je zou eventueel nog de waarden die naar PVOutput gestuurd worden kunnen loggen. Ik zal ervoor zorgen dat dat standaard gebeurt vanaf de volgende release.

**Comment by mkruiver** [comment]
Nog geen tijd gehad om te loggen/debuggen helaas.

**Comment by dennissiemensma** [comment]
@mkruiver speelt dit nog steeds?

Vanaf een van de afgelopen releases wordt de data die naar PVOutput gestuurd wordt gelogd. Je kunt het vinden in de backend log bij de tekst `PVOutput | Uploading data`.

**Comment by mkruiver** [comment]
Ja, dit speelt nog. Eens kijken of ik wat kan vinden in de logs....

![image](https://user-images.githubusercontent.com/3832319/43390214-eb1d3d8a-93ed-11e8-9f45-5c3dc05055ea.png)

**Comment by mkruiver** [comment]
- PVOutput | Uploading data @ {'v3': 1070, 'd': '20180730', 'n': 1, 't': '11:04', 'v4': -1119}
 - PVOutput | Uploading data @ {'v3': 1070, 'd': '20180730', 'n': 1, 't': '11:09', 'v4': -509}
 - PVOutput | Uploading data @ {'v3': 1070, 'd': '20180730', 'n': 1, 't': '11:14', 'v4': -415}
 - PVOutput | Uploading data @ {'v3': 1070, 'd': '20180730', 'n': 1, 't': '11:19', 'v4': -485}
 - PVOutput | Uploading data @ {'v3': 1070, 'd': '20180730', 'n': 1, 't': '11:24', 'v4': -696}
 - PVOutput | Uploading data @ {'v3': 1070, 'd': '20180730', 'n': 1, 't': '11:29', 'v4': -615}
 - PVOutput | Uploading data @ {'v3': 1070, 'd': '20180730', 'n': 1, 't': '11:34', 'v4': -944}
 - PVOutput | Uploading data @ {'v3': 1070, 'd': '20180730', 'n': 1, 't': '11:39', 'v4': -570}
 - PVOutput | Uploading data @ {'v3': 1070, 'd': '20180730', 'n': 1, 't': '11:44', 'v4': -927}
 - PVOutput | Uploading data @ {'v3': 1183, 'd': '20180730', 'n': 1, 't': '11:53', 'v4': -692}
 - PVOutput | Uploading data @ {'v3': 1214, 'd': '20180730', 'n': 1, 't': '11:58', 'v4': 681}
 - PVOutput | Uploading data @ {'v3': 1275, 'd': '20180730', 'n': 1, 't': '12:03', 'v4': 958}

PVO Magic, ik zie de match niet...

![image](https://user-images.githubusercontent.com/3832319/43392567-58b4b228-93f4-11e8-9a3b-2f40ba9d2f02.png)

**Comment by mkruiver** [comment]
https://www.pvoutput.org/intraday.jsp?id=54637&sid=49673

**Comment by dennissiemensma** [comment]
Bedankt voor je onderzoek. Op bovenstaande afbeelding doel je dus op het hoge verbruik in PVOutput van `12:00` en `12:05`?

Ik zie wel een afwijking in twee van deze output, het laatste `v4` getal is **groter dan nul** (dus verbruik volgens dsmr-reader?).

```
PVOutput | Uploading data @ {'v3': 1183, 'd': '20180730', 'n': 1, 't': '11:53', 'v4': -692}
PVOutput | Uploading data @ {'v3': 1214, 'd': '20180730', 'n': 1, 't': '11:58', 'v4': 681}
PVOutput | Uploading data @ {'v3': 1275, 'd': '20180730', 'n': 1, 't': '12:03', 'v4': 958}
```

Klopt dat?

**Comment by mkruiver** [comment]
Klopt, als er V4's groter dan nul zijn dan was er netto ook verbruik (import). Dat geloof ik wel op momenten dat er iemand thuis is.

Het issue waar is op doel is dat mijn daadwerkelijk verbruik dit is:

![image](https://user-images.githubusercontent.com/3832319/43461657-49854e76-94d4-11e8-9e47-571b9b3b78bb.png)

Maar het wordt weergegeven als:

![image](https://user-images.githubusercontent.com/3832319/43461703-68e89b2e-94d4-11e8-9c2a-f4c8e5ec8a65.png)


Met zelfs dips naar "0 used", terwijl dat nooit waar kan zijn (tenzij alle stroom uitstaat en ik dus ook geen data kan voorzien.....).

**Comment by mkruiver** [comment]
Ik denk overigens dat het een issue is van PVO, welke data "middeld" en daarbij de aanvoer van gegevens mbt productie (v1, v2) als "waar" aanhoud en de v3,v4 daarop aanpast als het ware voor het netto plaatje.
Dit gaat goed als er niet teveel fluctuaties zijn in v1/v2 data, maar niet als er dips (wolken) zijn.

**Comment by dennissiemensma** [comment]
Dank voor je opheldering. Is er nog iets wat je voor je kan doen om dit verder te debuggen? Of om ergens inzicht in te geven? 
Anders zul je het denk ik bij PVOutput zelf moeten aankaarten, voor zover het al niet bekend is daar.

**Comment by mkruiver** [comment]
Kan ik het tijdstip van uploaden (timestamp) beïnvloeden? Ik had verwacht
dat deze zou verschuiven adhv de delay die ik van 11 naar 7 minuten had
gezet, maar hij zit nog steeds niet op 5 'hele minuten' eg 12.20, 12.25,
etc ipv 12.49, 12.54

**Comment by dennissiemensma** [comment]
Ik zal kijken of ik daar iets voor kan maken voor je, dan kun je dat even uitproberen.

**Comment by mkruiver** [comment]
Bedankt voor je support van deze externe dienst Dennis!

**Comment by dennissiemensma** [comment]
@mkruiver ik ben weer eens in de code gedoken om te kijken hoe dit werkt.

* `Upload interval` is niet vrij in te vullen (5, 10, 15) en zou de uploadtijd moeten afronden op een veelvoud van de instelling. Dus als die op `5 minuten` staat, zou die om `12:00`, `12:05`, `12:10`, etc moeten uploaden.

* `Uploadvertraging` is wel vrij in te vullen en heeft **geen** invloed op het tijdstip van uploaden, alleen op de data die hij selecteert voor de upload. Zie ook de beschrijving bij het veld zelf.

Kan het zijn dat je deze door elkaar heen haalt? Als je de eerste instelling op 5 minuten zet en de tweede op nul, dan zou die exact 'rond' op de vijf minuten moeten uploaden.

Als dat niet goed werkt, dan zal ik er nog eens dieper naar moeten kijken.

**Comment by mkruiver** [comment]
Hmm... dat lijkt niet helemaal te kloppen. Ik heb interval en vertraging beiden al een paar dagen op 5 staan, maar loopt niet op de .05 intervals.


![screenshot_20180803-141931](https://user-images.githubusercontent.com/3832319/43642614-9a78f566-9728-11e8-9148-e8592e092620.png)


 - PVOutput | Uploading data @ {'v3': 458, 'd': '20180730', 'n': 1, 't': '03:44', 'v4': 135}
 - PVOutput | Delaying the next export until: 2018-07-30 02:00:00.969511+00:00

 - PVOutput | Uploading data @ {'v3': 470, 'd': '20180730', 'n': 1, 't': '03:49', 'v4': 131}
 - PVOutput | Delaying the next export until: 2018-07-30 02:05:00.034850+00:00

 - PVOutput | Uploading data @ {'v3': 1313, 'd': '20180730', 'n': 1, 't': '12:43', 'v4': -302}
 - PVOutput | Delaying the next export until: 2018-07-30 10:55:00.565043+00:00

 - PVOutput | Uploading data @ {'v3': 1313, 'd': '20180730', 'n': 1, 't': '12:48', 'v4': -399}
 - PVOutput | Delaying the next export until: 2018-07-30 11:00:00.918933+00:00

**Comment by mkruiver** [comment]
Dat wil zeggen: de daadwerkelijke actie is wel op .05 intervals, maar de meegegeven timestamp "T" heeft een andere offset!

**Comment by dennissiemensma** [comment]
Helder, bedankt voor de toelichting. Dan weet ik nu ook wat je bedoelt. Ik zal even kijken of ik zo kan zien waarom de meegegeven upload-tijdstip anders is.

Wellicht dat ik het anders moet insteken, zodat de instelling niet het moment van uploaden bepaalt, maar het moment tot wanneer de data meegenomen wordt.

**Comment by mkruiver** [comment]
Ik ben benieuwd, bedankt voor je wederom snelle actie Dennis!

On 3 Aug 2018 18:41, "Dennis Siemensma" <notifications@github.com> wrote:

Helder, bedankt voor de toelichting. Dan weet ik nu ook wat je bedoelt. Ik
zal even kijken of ik zo kan zien waarom de meegegeven upload-tijdstip
anders is.

Wellicht dat ik het anders moet insteken, zodat de instelling niet het
moment van uploaden bepaalt, maar het moment tot wanneer de data meegenomen
wordt.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/dennissiemensma/dsmr-reader/issues/467#issuecomment-410310006>,
or mute the thread

**Comment by dennissiemensma** [comment]
@mkruiver ik heb een losstaande wijziging hiervoor gemaakt. 

Het is gebaseerd op `v1.23` dus zorg ervoor dat je eerst op de laatste release zit. Daarna:

```
sudo su - dsmr
git fetch
git checkout -b 467-pvoutput-upload-sync origin/467-pvoutput-upload-sync
./deploy.sh
```

* Op dezelfde locatie, in de logs van `dsmr_backend` kun je nu zien of het beter gaat. Hij zou nu de data moeten uploaden tot het exacte gewenste moment.

* Afhankelijk van hoe snel je datalogger groepeert (als je dat aan hebt staan), kan het zijn dat je de melding `[i] PVOutput: Data found, not in sync. Last data timestamp < expected` krijgt. Dat betekent dat hij wil uploaden, maar nog geen data heeft. Dus hij wacht net zolang totdat er data is. Dit kom je denk ik alleen tegen wanneer de upload-vertraging `0` is.

----

Mocht je iets geks zien, of het toch niet lekker lopen, dan kun je gewoon terug naar master (`v1.23`):

```
sudo su - dsmr
git checkout master
./deploy.sh
```

**Comment by mkruiver** [comment]
Ik heb de 'beta' een tijdje gedraaid, maar volgens mij loste dit het issue niet op.
Wel is mijn omgeving sinds 13 augustus ineens stuk (bad gateway). Feature request: statusmonitor-process met emailmelding....

Hoe fiets ik deze weer recht?


![screenshot_20180820-134019](https://user-images.githubusercontent.com/3832319/44338693-0b2b7780-a47f-11e8-8656-acb724077b2d.png)

SSH Session Transcript

Host: 192.168.1.110
Date: Monday, 20 August 2018
---------------------------------
Linux raspberrypimeterkast 4.9.59-v7+ #1047 SMP Sun Oct 29 12:19:23 GMT 2017 armv7l

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Sat Aug 4 11:30:44 2018 from 10.16.0.2
pi@raspberrypimeterkast:~ $ sudo su dsmr (dsmrreader) dsmr@raspberrypimeterkast:~/dsmr-reader $ ./deploy.sh


--- You are currently running version:
1.24b1


Please make sure you've read EACH release note BEFORE deploying, since some
changes might not always be backwards compatible or depend on your database!

>>> https://github.com/dennissiemensma/dsmr-reader/releases 


~~~ Still want to deploy? (type Y + ENTER to continue or press CTRL + C to abort)
y


--- Pulling remote repository for new commits...
error: cannot open .git/FETCH_HEAD: Read-only file system


--- Merging/updating checkout.
fatal: Unable to create '/home/dsmr/dsmr-reader/.git/ORIG_HEAD.lock': Read-only file system


>>> Running post-deployment script. 


--- Checking whether VirtualEnv is activated.


--- Checking & synchronizing base requirements for changes.
The directory '/home/dsmr/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/dsmr/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Exception:
Traceback (most recent call last):
File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
status = self.run(options, args)
File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.5/site-packages/pip/commands/install.py", line 307, in run
delete=build_delete) as build_dir:
File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.5/site-packages/pip/utils/build.py", line 22, in __init__
name = os.path.realpath(tempfile.mkdtemp(prefix="pip-build-"))
File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.5/tempfile.py", line 497, in mkdtemp
prefix, suffix, dir, output_type = _sanitize_params(prefix, suffix, dir)
File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.5/tempfile.py", line 269, in _sanitize_params
dir = gettempdir()
File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.5/tempfile.py", line 435, in gettempdir
tempdir = _get_default_tempdir()
File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.5/tempfile.py", line 370, in _get_default_tempdir
dirlist)
FileNotFoundError: [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/home/dsmr/dsmr-reader']


--- Checking & synchronizing database changes/migrations.
Traceback (most recent call last):
File "/usr/lib/python3.5/logging/config.py", line 558, in configure
handler = self.configure_handler(handlers[name])
File "/usr/lib/python3.5/logging/config.py", line 731, in configure_handler
result = factory(**kwargs)
File "/usr/lib/python3.5/logging/handlers.py", line 150, in __init__
BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
File "/usr/lib/python3.5/logging/handlers.py", line 57, in __init__
logging.FileHandler.__init__(self, filename, mode, encoding, delay)
File "/usr/lib/python3.5/logging/__init__.py", line 1009, in __init__
StreamHandler.__init__(self, self._open())
File "/usr/lib/python3.5/logging/__init__.py", line 1038, in _open
return open(self.baseFilename, self.mode, encoding=self.encoding)
OSError: [Errno 30] Read-only file system: '/home/dsmr/dsmr-reader/logs/django.log'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "./manage.py", line 10, in 
execute_from_command_line(sys.argv)
File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.5/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
utility.execute()
File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.5/site-packages/django/core/management/__init__.py", line 347, in execute
django.setup()
File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.5/site-packages/django/__init__.py", line 19, in setup
configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.5/site-packages/django/utils/log.py", line 73, in configure_logging
logging_config_func(logging_settings)
File "/usr/lib/python3.5/logging/config.py", line 795, in dictConfig
dictConfigClass(config).configure()
File "/usr/lib/python3.5/logging/config.py", line 566, in configure
'%r: %s' % (name, e))
ValueError: Unable to configure handler 'django_file': [Errno 30] Read-only file system: '/home/dsmr/dsmr-reader/logs/django.log'


--- Checking & synchronizing static file changes.
Traceback (most recent call last):
File "/usr/lib/python3.5/logging/config.py", line 558, in configure
handler = self.configure_handler(handlers[name])
File "/usr/lib/python3.5/logging/config.py", line 731, in configure_handler
result = factory(**kwargs)
File "/usr/lib/python3.5/logging/handlers.py", line 150, in __init__
BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
File "/usr/lib/python3.5/logging/handlers.py", line 57, in __init__
logging.FileHandler.__init__(self, filename, mode, encoding, delay)
File "/usr/lib/python3.5/logging/__init__.py", line 1009, in __init__
StreamHandler.__init__(self, self._open())
File "/usr/lib/python3.5/logging/__init__.py", line 1038, in _open
return open(self.baseFilename, self.mode, encoding=self.encoding)
OSError: [Errno 30] Read-only file system: '/home/dsmr/dsmr-reader/logs/django.log'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "./manage.py", line 10, in 
execute_from_command_line(sys.argv)
File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.5/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
utility.execute()
File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.5/site-packages/django/core/management/__init__.py", line 347, in execute
django.setup()
File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.5/site-packages/django/__init__.py", line 19, in setup
configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.5/site-packages/django/utils/log.py", line 73, in configure_logging
logging_config_func(logging_settings)
File "/usr/lib/python3.5/logging/config.py", line 795, in dictConfig
dictConfigClass(config).configure()
File "/usr/lib/python3.5/logging/config.py", line 566, in configure
'%r: %s' % (name, e))
ValueError: Unable to configure handler 'django_file': [Errno 30] Read-only file system: '/home/dsmr/dsmr-reader/logs/django.log'


--- Reloading app code...

* Reloading process: dsmr_webinterface (Gunicorn)kill: (789): No such process
[OK]
* Reloading process: dsmr_backend kill: (30479): No such process
[OK]
* Reloading process: dsmr_datalogger kill: (30477): No such process
[OK]
* Reloading process: dsmr_mqtt kill: (4240): No such process
[OK]


--- Clearing cache...
Traceback (most recent call last):
File "/usr/lib/python3.5/logging/config.py", line 558, in configure
handler = self.configure_handler(handlers[name])
File "/usr/lib/python3.5/logging/config.py", line 731, in configure_handler
result = factory(**kwargs)
File "/usr/lib/python3.5/logging/handlers.py", line 150, in __init__
BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
File "/usr/lib/python3.5/logging/handlers.py", line 57, in __init__
logging.FileHandler.__init__(self, filename, mode, encoding, delay)
File "/usr/lib/python3.5/logging/__init__.py", line 1009, in __init__
StreamHandler.__init__(self, self._open())
File "/usr/lib/python3.5/logging/__init__.py", line 1038, in _open
return open(self.baseFilename, self.mode, encoding=self.encoding)
OSError: [Errno 30] Read-only file system: '/home/dsmr/dsmr-reader/logs/django.log'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "./manage.py", line 10, in 
execute_from_command_line(sys.argv)
File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.5/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
utility.execute()
File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.5/site-packages/django/core/management/__init__.py", line 347, in execute
django.setup()
File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.5/site-packages/django/__init__.py", line 19, in setup
configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.5/site-packages/django/utils/log.py", line 73, in configure_logging
logging_config_func(logging_settings)
File "/usr/lib/python3.5/logging/config.py", line 795, in dictConfig
dictConfigClass(config).configure()
File "/usr/lib/python3.5/logging/config.py", line 566, in configure
'%r: %s' % (name, e))
ValueError: Unable to configure handler 'django_file': [Errno 30] Read-only file system: '/home/dsmr/dsmr-reader/logs/django.log'


--- Deployed version:
1.24b1


>>> Deployment complete. 
(dsmrreader) dsmr@raspberrypimeterkast:~/dsmr-reader $
---------------------------------

This transcript has been sent from my Android device with JuiceSSH

**Comment by mkruiver** [comment]
Mijn sd was corrupt, ik heb de boel weer draaien. Nu de pvo-consumption weer debuggen.

**Comment by dennissiemensma** [comment]
Bedankt voor je update en balen dat je kaartje stuk was. Ik hoor graag van je wanneer je weer in de gelegenheid bent om de (nieuwe) logs te bekijken.

**Comment by dennissiemensma** [comment]
Bedankt voor de update. 

Is er nog meer informatie die je inzichtelijk wil hebben? Ik weet niet zo goed waar ik nog verder in kan zoeken of veranderen.

**Comment by mkruiver** [comment]
Nee, ik vrees dat het gewoon aan het middelings-algoritme van PVOutput
ligt. De data die aangeleverd wordt lijkt me duidelijk....

Deze kan dicht. Mocht ik in de toekomst nog iets nodig hebben of ontdekken
dan meld ik me weer!

Bedankt voor je support van deze feature. Ondanks deze kleine rariteit is
het voor mij nog steeds goed bruikbaar.

**Comment by dennissiemensma** [comment]
Oke prima. Heb je nog wat aan deze code-branch qua debugging of kan ik hem helemaal verwijderen? 

Het uploaden van de data daarmee dan weer volgens de "oude" werking in de hoofdversie, zodra je lokaal terugwisselt naar `master`.

**Comment by mkruiver** [comment]
Hmmm, je wil de backend log niet standaard 'vervuilen' met pvo output
logging?
Gezien er toch niks aan te doen is, is dat op zich prima en kan het er
helemaal uit.

Wat wel fijn is is dat de upload timestamp / delay nu gesynced is met de pi
time. Had je daar ook iets aan veranderd?

**Comment by mkruiver** [comment]
Top, van mij mogen de tijden gemerged worden in de main!

**Comment by dennissiemensma** [comment]
Staat nu in `development` voor de volgende release, onder voorbehoud dat anderen geen last hebben van de wijziging.

**Comment by dennissiemensma** [comment]
Zou je eens kunnen terugswitchen naar `master` om te kijken of dat de piek weer tevoorschijn haalt? Ik kan er opzich weinig aan doen, maar dan kun je nog overwegen welke van de twee je liever draait.

**Comment by mkruiver** [comment]
De master laat even vaak af en toe de piek wegvallen. Het zal ook hier wel
aan het middelen van pvo liggen, denk ik.

**Comment by dennissiemensma** [comment]
Welke van de twee heeft dan de voorkeur, de oude in master of de nieuwe?

**Comment by dennissiemensma** [comment]
Prima dat laat ik het eerst zo voor de aankomende release.
