### ISSUE TITLE
Mqtt ontbrekende gasstatistieken

### ISSUE THREAD

**Issue by Pcdejong** [dennissiemensma/dsmr-reader#468]
Dag Dennis,

Sinds enige tijd enthousiast gebruiker van deze fantastisch tool. Dank daarvoor. 

Lees mijn slimme meter door en stuur via MQTT statistieken door naar mijn Home Assistant. Maar ik mis (of ik kijk niet goed) het gasverbruik per uur en de gasmeterstand. Kijk ik er overheen of is dit niet mogelijk?

Gr Peter

### Jouw omgeving
* DSMR-reader versie *(rechtsbovenin applicatie zichtbaar)*: `v1.6`
* Hardware *RaspberryPi 3B...`
* DSMR-protocol versie van slimme meter *V4)

**Comment by Pcdejong** [comment]
Dag Dennis,

Super bedankt voor je snelle antwoord. Zat me al af te vragen waar dat extra device op sloeg. Maar als dat de gas is perfect! Ik zal hem wel hernoemen in mijn HA. 

Ik gebruik inderdaad 1.16 sorry typo.

Gr Peter

**Comment by dennissiemensma** [comment]
Fijn om te horen. Ik heb het generiek 'extra device' genoemd, omdat er in theorie ook andere apparaten, zoals thermische meters en watermeters. In de praktijk is het echter vaak alleen een gasmeter.
