### ISSUE TITLE
Query latest reading via API is slow

### ISSUE THREAD

**Issue by swerveshot** [dennissiemensma/dsmr-reader#469]
Using the API example from the documentation 'fetch latest reading' takes about 5 to 6 seconds. The nice red indicator in the web interface updates much faster. Is there any way to speed this up? I'm sure it has something to do with the modest hardware I have dsmr-reader running on. But I suppose lots of people use a Raspberry Pi class of development boards.

I'm not an expert on databases, but when I execute the API call I noticed a spike in activity on the backend database when using `top`. Perhaps adding an index might improve performance.

### Environment
* DSMR-reader version: v1.16
* Hardware: Odroid U3
* DSMR protocol: v4 (I think, probably not relevant for this issue)

### Reproduce issue
* Look up the API key
* Use this key in the X-AUTHKEY header with a tool such as Postman and watch the execution time.

**Comment by dennissiemensma** [comment]
Bedankt voor je ticket. Het kan meerdere oorzaken hebben. 

Als het goed is zitten er al indexes op de tabel in de database. Echter, de metingen-tabel kan ook erg veel records bevatten, waardoor de API call beduidend trager wordt. 

* Hoeveel metingen zie je op de Statistieken-pagina? (je moet daarvoor klikken op de knop daar)
* Heb je toevallig al retentie ingeschakeld?

**Comment by swerveshot** [comment]
Dank voor de snelle follow-up zeg!

In totaal zie ik 9,428,051 telegram readings op de statistieken pagina, dus ik ben een goed eind op weg van de 30 miljoen die je op de docu pagina voor retentie noemt. Klopt ook wel want ik ben bijna 4 maanden aan het loggen.

Dus ja, misschien is retentie instellen wel een goed idee. Doe ik nu nog niet namelijk. Zal de retentie van een maand instellen aangezien de volgende stap een half jaar is en ik nu al performance problemen ondervind.

**Comment by dennissiemensma** [comment]
Prima, ik hoor graag of dat het voor je oplost.

**Comment by swerveshot** [comment]
Hoi Dennis,

Heb 2 dagen geleden de retentie instellingen gewijzigd. Uit de documentatie maak ik op dat dit ertoe zou moeten leiden dat het aantal readings gestaag moet afnemen. Alleen dat zie ik niet gebeuren.

Heb je suggesties om dit te verhelpen? Is een herstart nodig of moet ik log files gaan bekijken?

**Comment by dennissiemensma** [comment]
Als het goed is kun je in de logfiles zien of/wanneer gegevens opgeschoond worden.

Bijvoorbeeld in:
* `/var/log/supervisor/dsmr_backend.log`
* `/var/log/supervisor/dsmr_backend.log.1`

```
2018-05-02 02:00:01.079911+02:00: Calling backend services
Retention | Cleaning up: 2018-04-03 07:00:00+00:00 (ElectricityConsumption)
Retention | Cleaning up: 2018-04-03 08:00:00+00:00 (ElectricityConsumption)
Retention | Cleaning up: 2018-04-03 09:00:00+00:00 (ElectricityConsumption)
Retention | Cleaning up: 2018-04-03 10:00:00+00:00 (ElectricityConsumption)
Retention | Cleaning up: 2018-04-03 11:00:00+00:00 (ElectricityConsumption)
Retention | Cleaning up: 2018-04-03 12:00:00+00:00 (ElectricityConsumption)
Retention | Cleaning up: 2018-04-03 13:00:00+00:00 (ElectricityConsumption)
Retention | Cleaning up: 2018-04-03 14:00:00+00:00 (ElectricityConsumption)
Retention | Cleaning up: 2018-04-03 15:00:00+00:00 (ElectricityConsumption)
Retention | Cleaning up: 2018-04-03 16:00:00+00:00 (ElectricityConsumption)
Retention | Cleaning up: 2018-04-03 17:00:00+00:00 (ElectricityConsumption)
Retention | Cleaning up: 2018-04-03 18:00:00+00:00 (ElectricityConsumption)
Retention | Cleaning up: 2018-04-03 19:00:00+00:00 (ElectricityConsumption)
Retention | Cleaning up: 2018-04-03 20:00:00+00:00 (ElectricityConsumption)
Retention | Cleaning up: 2018-04-03 21:00:00+00:00 (ElectricityConsumption)
Retention | Cleaning up: 2018-04-03 22:00:00+00:00 (ElectricityConsumption)
Retention | Cleaning up: 2018-04-03 23:00:00+00:00 (ElectricityConsumption)
Retention | Cleaning up: 2018-04-03 07:00:00+00:00 (DsmrReading)
Retention | Cleaning up: 2018-04-03 08:00:00+00:00 (DsmrReading)
Retention | Cleaning up: 2018-04-03 09:00:00+00:00 (DsmrReading)
Retention | Cleaning up: 2018-04-03 10:00:00+00:00 (DsmrReading)
Retention | Cleaning up: 2018-04-03 11:00:00+00:00 (DsmrReading)
Retention | Cleaning up: 2018-04-03 12:00:00+00:00 (DsmrReading)
Retention | Cleaning up: 2018-04-03 13:00:00+00:00 (DsmrReading)
```

Zie je dat ergens terug?

**Comment by swerveshot** [comment]
Nope, helaas nemen de readings alleen maar toe.

```
dsmrreader=# select count(*) from dsmr_datalogger_dsmrreading;
  count
---------
 9718872
(1 row)

dsmrreader=# select count(*) from dsmr_consumption_electricityconsumption;
 count
-------
 40197
(1 row)

dsmrreader=# select count(*) from dsmr_consumption_gasconsumption;
 count
-------
 11412
(1 row)
```

**Comment by dennissiemensma** [comment]
Als het goed is is het inderdaad `yyyy-dd-mm`.
