### ISSUE TITLE
MQTT stales DSMR when MQTT server isn't available.

### ISSUE THREAD

**Issue by joopy** [dennissiemensma/dsmr-reader#491]
When using MQTT with DSMR (eg home assistant) when Home Assistant isn't working 'crash stuck' (100% cpu) DSMR datalogger stales. Tested and can confirm this is the case.

**Comment by dennissiemensma** [comment]
Bedankt voor het uitproberen en je melding. Ik zal dan kijken of ik het zelf ook kan reproduceren.

Bedoel je dat je Home Assistant laat crashen of iets om het na te bootsen?

**Comment by dennissiemensma** [comment]
@joopy Bedoel je dat je Home Assistant laat crashen of iets, om het na te bootsen? Of zet je server waar HA op draait uit?

**Comment by joopy** [comment]
wanneer HA crasht dus mqtt niet beschikbaar dan loopt ook dsmr vast. Zijn twee aparte raspberries.

**Comment by dennissiemensma** [comment]
De volgende release bevat een complete refactoring van MQTT. Het MQTT-verhaal is daarmee losgetrokken van de backend en zou niet meer in de weg moeten zitten.

Ik wacht even de volgende release af, zodat je die dan kan uitproberen.

**Comment by joopy** [comment]
Ben heel benieuwd!

**Comment by joopy** [comment]
Dennis ik heb versie 1.23 draaien voor nu alles goed! Hou je op de hoogte.

**Comment by dennissiemensma** [comment]
Voor nu sluit ik deze. Mocht je toch nog tegen issues aanlopen, dan hoor ik het graag!
