### ISSUE TITLE
Gegevens opslaan\ Dsmr-reader afsluiten

### ISSUE THREAD

**Issue by Jovink** [dennissiemensma/dsmr-reader#496]
Is het mogelijk om Dmsr-reader af te sluiten zonder dat er gegevens verloren gaan?
Volgens mij wordt de date pas rond 1.00 naar de database geschreven. 
Dat zou dus betekenen dat als ik nu de stekker er even uit trek ik de gegevens van vandaag kwijt ben..

Verder een heel mooi project.
Bedankt Dennis.

**Comment by dennissiemensma** [comment]
Bedankt voor je vraag en goed om te horen dat je zo tevreden bent.

Als je de standaardinstallatie hebt gedaan dan gaan er nooit gegevens verloren. PostgreSQL garandeert dat er geen datacorruptie kan optreden. Je kunt er dus altijd de stekker uit trekken, al is een clean shutdown altijd netter.

*Echter*, het kan wel zijn dat je SD-kaart zelf defect raakt (dat gebeurt altijd op den duur). Daarmee kun je wel gegevens verliezen, dus het is zaak dat je zorgt voor een goede dagelijkse backup (of gebruik de ingebouwde + dropbox).
