### ISSUE TITLE
Kleinigheidje: missende vertalingen

### ISSUE THREAD

**Issue by jorisvervuurt** [dennissiemensma/dsmr-reader#497]
Een kleinigheidje: na de update naar v1.21, merkte ik op dat op de Trends-pagina een aantal (Nederlandse) vertalingen missen in de onderste twee energieverbruik-grafieken. Er staat ‘electricity1’ en ‘electricity2’, waar ik ‘Elektriciteit 1 (daltarief)’ en ‘Elektriciteit 2 (piektarief)’ zou verwachten.

Helemaal onbelangrijk: tijdens het laden van de grafieken zie ik kort ‘loading’ staan in plaats van ‘laden’. 😛

**Comment by dennissiemensma** [comment]
Bedankt voor je opmerkingen. Ik zal kijken of ik die vertalingen kan oplossen.

**Comment by dennissiemensma** [comment]
Ik heb het opgelost in 1d68500c792bab255da9db77ee886af77024aeca. Gaat zo mee met de patch release die ik al klaar had staan.

**Comment by jorisvervuurt** [comment]
Top, dankjewel!
