### ISSUE TITLE
Lijn grafiek bij geen teruglevering

### ISSUE THREAD

**Issue by Bl4ckviper** [dennissiemensma/dsmr-reader#501]
Dennis, 

Mooie nieuwe grafieken. Echter 1 vraag. Ik zie dat als er geen teruglevering is de groene lijn toch ook getoond wordt op de lijn van het verbruik.

Andersom is dit niet het geval. Zie screenshot.
Is dit by design?
![capture](https://user-images.githubusercontent.com/28338927/42986508-14aa8180-8bf6-11e8-90b0-1e29b331a59e.JPG)

![capture2](https://user-images.githubusercontent.com/28338927/42986546-3e51e398-8bf6-11e8-9541-505b1602d418.JPG)

**Comment by dennissiemensma** [comment]
Bedankt voor je terugkoppeling. Het is niet bewust, maar wel iets waar ik nog eigenlijk een keuze in moet maken.

De oorzaak is dat ik tegen de grafiek zeg "stapel ze maar" en daarbij is de teruglevering altijd bovenop en wordt die (blijkbaar) altijd getoond.

De stapel-optie kan ik ook uitzetten en dan worden de grafieken door elkaar heen getoond. Het contrast is dan minder, maar er zitten dan geen lijnen door elkaar heen. Zie hieronder een voorbeeld van dezelfde data en let dan ook op de schaal links:

**Gestapeld**
![menu_004](https://user-images.githubusercontent.com/16581744/43002897-bd20248a-8c2a-11e8-901b-357c990814db.png)

**Normaal**
![menu_005](https://user-images.githubusercontent.com/16581744/43002898-bd3a31ae-8c2a-11e8-874e-07e0be92277c.png)

Ik denk dat ik het stapelen voor de levering/teruglevering-grafiek dan uitzet en voor fases actief laat.

**Comment by dennissiemensma** [comment]
Je kunt zelf ook even kijken of het beter is wanneer je het stapelen uitzet voor je grafiek. 

Deze file kun je dan aanpassen: 
`/var/www/dsmrreader/static/dsmr_frontend/js/dsmr-reader/dashboard/electricity.js` 

Door op regels 60 en 68, de regels met `stack` uit te commenten of weg te halen:
![selection_006](https://user-images.githubusercontent.com/16581744/43003029-40e838a2-8c2b-11e8-9f00-40404def4140.png)

Vervolgens zou je, na een harde refresh in je browser, een ander soort grafieken moeten zien. Laat maar weten of dat beter werkt (ik heb zelf geen zonnepanelen en heb dit dan ook niet gezien). Ik denk dat ik het uiteindelijk sowieso doorvoer voor die grafiek.

**Comment by Bl4ckviper** [comment]
zal dit straks eens probren en je laten weten hoe t ging.

**Comment by dennissiemensma** [comment]
Dat ziet er een stuk beter uit zo ja, ik zal het dan doorvoeren voor de volgende release voor die grafiek. Tot die tijd kun je dit rustig laten staan in je bestand.

**Comment by dennissiemensma** [comment]
Ik heb het doorgevoerd in b9f766e32524bed0d22bf198c15bf16ab3d5ee15 voor de volgende release, nogmaals bedankt voor de headsup.

Voor het testen met teruglevering (wat ik naboots) heb ik de tool voor het genereren van nep-data wat aangepast, zodat die de werkelijkheid beter reflecteert en ik dit mogelijk een volgende keer eerder zie bij ontwikkelen.

**Comment by dennissiemensma** [comment]
Uitgebracht in `v1.22`.
