### ISSUE TITLE
Trend-grafiek kan niet gegenereerd worden

### ISSUE THREAD

**Issue by TampertK** [dennissiemensma/dsmr-reader#508]
In navolging op issue #506 van gisteren, blijkt bij verder gebruik van DSMR Reader dat ook de trend-grafieken (ELECTRICITY TARIFF RATIO) niet gegenereerd kunnen worden. De URL `/trends/xhr/consumption-by-tariff` geeft een vergelijkbare error:

> Server Error
> Exception:
> AttributeError: 'NoneType' object has no attribute 'items'
> Traceback:
>   File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
>     response = wrapped_callback(request, *callback_args, **callback_kwargs)
> 
>   File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
>     return self.dispatch(request, *args, **kwargs)
> 
>   File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
>     return handler(request, *args, **kwargs)
> 
>   File "/home/dsmr/dsmr-reader/dsmr_frontend/views/trends.py", line 86, in get
>     dsmr_stats.services.electricity_tariff_percentage(start_date=week_date).items()

**Comment by dennissiemensma** [comment]
Bedankt voor je melding! Ik zie dat dit komt doordat er nog geen data beschikbaar is. Bij het herschrijven van die pagina heb ik vermoedelijk de checks gemist die kijken of er uberhaupt data is om te gebruiken. Ik zal het meenemen voor de volgende release.

**Comment by TampertK** [comment]
Dank weer voor de snelle actie!

**Comment by dennissiemensma** [comment]
@TampertK heb je trouwens vandaag opnieuw een schone installatie gedaan of is dit dezelfde installatie als gisteren?

Ik zou namelijk verwachten dat de data in de Trends-pagina na de eerste nacht beschikbaar is, gezien de dagstatistieken een paar uur na de wisseling van een dag gegeneerd worden. Dus wellicht mis ik nog iets anders.
Als je deze URL bekijkt, zie je dan gegevens?
`http://ip-of-hostname-pi` `/admin/dsmr_stats/daystatistics/`

**Comment by TampertK** [comment]
Het is dezelfde installatie. Maar grappig genoeg doen de statistieken het vandaag wel... Dus kennelijk hebben de grafieken wat meer tijd nodig dan gedacht?

**Comment by dennissiemensma** [comment]
Bedankt voor je feedback. In dat geval is het inderdaad het issue wat ik dacht. Ik heb er inmiddels een fix voor gemaakt in da11a9a012921c9c56f41dc11128d84b7df652ac voor de volgende release. 
Nogmaals bedankt voor het melden. :]
