### ISSUE TITLE
Docker DSMR Datalogger

### ISSUE THREAD

**Issue by trizz** [dennissiemensma/dsmr-reader#527]
In navolging van een [complete DSMR Reader Docker container](https://hub.docker.com/r/xirixiz/dsmr-reader-docker/) heb ik een Docker container gemaakt puur voor het loggen van data vanaf een Raspberry Pi naar een remote DSMR Reader installatie. Het stelt allemaal niet zo heel veel voor; het is een iets aangepaste versie van het voorbeeldscript, maar wellicht is het handig voor mensen die, net als ik, steeds meer in Docker hebben draaien 😄 

Usage:
```
docker run -d \
    --device=/dev/ttyUSB0 \
    -e DSMR_USB_PORT=/dev/ttyUSB0 \
    -e DSMR_API_URL=https://<YOUR_DSMR_HOST>/api/v1/datalogger/dsmrreading \
    -e DSMR_API_KEY=<YOUR_API_KEY> \
    trizz/dsmr-remote-datalogger:latest
```

Meer info:
- https://hub.docker.com/r/trizz/dsmr-remote-datalogger/
- https://github.com/trizz/dsmr-remote-datalogger

Deze container heb ik dus voor eigen gebruik op een Raspberry Pi 2 (ARMv7) gemaakt en ik heb 't niet getest op andere platformen. Ik verwacht dat een Pi Zero of 3 geen problemen geeft.

**Comment by dennissiemensma** [comment]
Bedankt voor je toevoeging! Ik heb het opgenomen in de docs voor de volgende release:

https://dsmr-reader.readthedocs.io/nl/development/installation.html#docker-alternative
