### ISSUE TITLE
Energieprijzen worden niet getoond

### ISSUE THREAD

**Issue by RichieB2B** [dennissiemensma/dsmr-reader#538]
### Jouw omgeving
* DSMR-reader versie: `v1.25`
* Hardware: `RaspberryPi 3B+`
* DSMR-protocol versie van slimme meter: `v4`

### Bug, wens of iets anders
Ik heb mijn energiecontracten ingevuld. Maar de totale kosten zijn niet zichtbaar in het dashboard. Daar blijft `-` staan. Ik heb al geprobeerd om de prijzen met een punt ipv een komma in te vullen maar dat maakt geen verschil.

**Comment by dennissiemensma** [comment]
Bedankt voor je melding. 

Weet je zeker dat je de start- en einddatum van het betreffende contract goed hebt ingevuld? En dat die overlapt met vandaag?

**Comment by RichieB2B** [comment]
Veroorzaakt door #540
