### ISSUE TITLE
Dag verbruik is anders dan PVOutput

### ISSUE THREAD

**Issue by eterpstra** [dennissiemensma/dsmr-reader#551]
Hallo Dennis,

Ik heb de PVOutput api ingeschakeld. Alles wordt netjes naar PVOutput geupload. Echter als ik de meterstanden van DSMR Reader vergelijk met PVOutput (dagbasis) dan het verbruik op PVOutput 2 x zo hoog bijna.
Enig idee hoe dit kan?

BIjvoorbeeld:
PV Output op 05/11/18
05/11/18 | 0.000kWh | 0.000kWh/kW | 0.000kWh | 9.769kWh | 9.769kWh | €0,00 | €0,00 | €0,00▲ | €0,00 | 9.769kWh▼
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
In DSMR Archief:
Totaal 4,79  KWh  Teruggeleverd: 0,06 KWh

DMSR Reader is geupdate naar de nieuwste versie.

Gr,
Elroy

**Comment by dennissiemensma** [comment]
Doel je op het verbruik dat DSMR-reader naar PVOutput stuurt of doel je op het verbruik dat je omvormer naar PVOutput stuurt?

**Comment by eterpstra** [comment]
Hoi Dennis,

Het gaat mij puur om het verbruik van de slimme meter. Of klopt het dat PVoutput alleen het echte verbruik pakt zonder de teruglevering van zonnepanelen?

**Comment by dennissiemensma** [comment]
Wat ik wel weet is dat de slimme meter de **netto** opbrengst van je zonnepanelen rapporteert en dat het kan afwijken van je bruto opbrengst. Qua verbruik uploadt die telkens het totaal van de complete dag.

Je kunt eventueel logging aanzetten om te zien welke informatie `dsmr_backend` doorstuurt naar PVOutput: https://dsmr-reader.readthedocs.io/nl/latest/troubleshooting.html#logging. 
Mogelijk kun je aan de hand daarvan een conclusie trekken? Je kunt ze vinden in de log op: `PVOutput | Uploading data`.
Ik heb zelf geen zonnepanelen en gebruik dus ook geen PVOutput, dus het is voor mij erg lastig om te visualiseren waar je exact op doelt. De implementatie is gedaan in #9, mogelijk vind je daar nog hints?

Logica staat hier: https://github.com/dennissiemensma/dsmr-reader/blob/master/dsmr_pvoutput/services.py#L81

**Comment by dennissiemensma** [comment]
@eterpstra ben je hier verder nog zelf uit gekomen?

**Comment by eterpstra** [comment]
Hi Dennis,

Ik heb er nog geen tijd voor gehad. Ik zal er later nog eens gaan in duiken. In principe hou ik gewoon dsmr aan omdat ik dit ook mooier vind.

**Comment by dennissiemensma** [comment]
@eterpstra ben je hier nog aan toe gekomen? Anders laat ik dit issue voor wat het is.

**Comment by eterpstra** [comment]
Hi Dennis,

Sluit hem maar. Ik heb het bekeken en volgens mij klopt het nu wel gewoon

**Comment by dennissiemensma** [comment]
Oke bedankt voor je snelle terugkoppeling
