### ISSUE TITLE
Melding bij onvolledige vergelijking

### ISSUE THREAD

**Issue by voipmeister** [dennissiemensma/dsmr-reader#565]
### Jouw omgeving
*(Indien van toepassing)*
* DSMR-reader versie *(rechtsbovenin applicatie zichtbaar)*: `v1.26.1`
* Hardware *(RaspberryPi 2, 3 of iets anders)*: `RaspberryPi 3`
* DSMR-protocol versie van slimme meter *(v2, v4 of v5)*: `v...`

### Verbetering
Bij het vergelijken van 2 periodes wordt niet gekeken/gemeld of de periodes wel compleet zijn. De verbetering zou dan (mogelijk) bestaan uit het tonen van (in dit geval) twee meldingen, als ik 2017 met 2018 zou vergelijken:
* Let op, de data voor 2017 is niet compleet! (eerst gevonden data is van 14-07-2017)
* Let op, de data voor 2018 is (nog) niet compleet

Voorbeeld: midden in juli 2017 ben ik begonnen met de huidige installatie. Als ik 2017 met 2018 vergelijk, gaat de vergelijking mank:
* Er zijn pas gegevens vanaf 14 juli 2017
* 2018 is nog niet afgelopen

Het screenshot is van alleen de vergelijking van juli 2017 en juli 2018, ter onderbouwing van het eerste punt:

<img width="1013" alt="screenshot 2018-12-21 at 08 28 26" src="https://user-images.githubusercontent.com/12763807/50330422-6b006080-04fb-11e9-9c0f-22a40ebf6440.png">

En hierbij de archiefdata van juli 2017:

<img width="1202" alt="screenshot 2018-12-21 at 08 37 09" src="https://user-images.githubusercontent.com/12763807/50330481-b0bd2900-04fb-11e9-900e-37f1bf1dfa18.png">

Als ik nog wat mag verduidelijken of meer mag meedenken hoor ik het graag 😄

**Comment by dennissiemensma** [comment]
Bedankt voor je suggestie. Dat is inderdaad iets waar ik geen rekening mee heb gehouden. Het lijkt me goed om die melding dan toe te voegen.

**Comment by voipmeister** [comment]
Gezien mijn meeste recente SD-kaart crash en de herinstallatie + restore (ik had nog geen tijd genomen de setup te verbeteren) toch even mijn eigen suggestie 'bevestigen' in de zin dat ik nu 2 weken mis i.v.m. kapotte recente backups. Bij vergelijkingen heb ik dus een gat van 2 weken helaas, dat ga ik vast vergeten als ik 2019 met 2018 ga vergelijk begin 2020 ;-)

**Comment by dennissiemensma** [comment]
Ik heb dit in de volgende release opgelost met een melding:

![Selection_001](https://user-images.githubusercontent.com/16581744/76350434-0f8ede00-630c-11ea-9bbe-02b35d0e014b.png)

**Comment by dennissiemensma** [comment]
Uitgebracht in [v3.7](https://github.com/dennissiemensma/dsmr-reader/releases/tag/v3.7.0)
