### ISSUE TITLE
Feature request: Back-up (indien gewenst) versleuteld op cloudstorage plaatsen

### ISSUE THREAD

**Issue by voipmeister** [dennissiemensma/dsmr-reader#566]
### Wens
Voor het back-uppen van mijn privé laptop gebruik ik Arq. Deze software maakt het mogelijk om een encryptiesleutel in te voeren, die gebruikt wordt om alle data versleuteld op te slaan op cloudstorage. Ideaal als je cloudstorage over hebt en toch je data privé wenst te houden.

Een dergelijke constructie zou ook een mooie aanvulling zijn voor de offsite back-ups van DSMR-reader denk ik (met de optie om dit zelf wel of niet aan te zetten). Dat de sleutel in de lokale installatie zit, zou ik niet als bezwaar zien aangezien de installatie zich toch binnenshuis bevindt.

De mogelijkheid om de sleutel eenmalig (of op verzoek via een button) te mailen is misschien handig voor situaties waarin de SD-kaart echt kapot is geschreven.

**Comment by voipmeister** [comment]
> Overigens komt er in de volgende release een optie om een handmatig-pad op te geven, dus misschien kun je daar nog wat mee doen i.c.m. versleuteling?> maar valt het misschien wat pragmatischer op te lossen door Arq zelf de folder met individuele back-up's te laten versleutelen? 

Arq was meer een voorbeeld, ik zou dezelfde functie graag in DSMR-reader zien (als dat ook volgens jou meerwaarde heeft en dat past in de 'roadmap' natuurlijk).

> Overigens komt er in de volgende release een optie om een handmatig-pad op te geven, dus misschien kun je daar nog wat mee doen i.c.m. versleuteling?

Dat is al een heel fijne toevoeging (waarvoor dank!), dan kan ik de boel gewoon op mijn NAS plaatsen (naast de off-site Dropbox back-up).

**Comment by dennissiemensma** [comment]
De nieuwe release is uit en daarin zit het handmatige backup-pad.

**Comment by dennissiemensma** [comment]
Ik heb hier opnieuw naar gekeken, maar ik ga dit toch niet heroverwegen. Voor het meerendeel van de gebruikers zal dit niet echt wat toevoegen, omdat het meer een hobby-project is voor op een raspberry. En het valt redelijk buiten de scope van het project, met nog genoeg andere features te doen.

Voor techneuten zoals jij en ik zullen we het met een omweg moeten realiseren. Ik kan helaas niet meer voor je doen dan het back-up pad handmatig in te kunnen vullen.
