### ISSUE TITLE
Binnentemperatuur (thermostaat uitlezen)

### ISSUE THREAD

**Issue by hsleewis** [dennissiemensma/dsmr-reader#568]
Misschien wel heel interessant om ook de ingestelde temperatuur van de thermostaat uit te lezen. Al wordt dat misschien wat lastig als je met meerdere zone's gaat werken die anders ingesteld staan.

**Comment by dennissiemensma** [comment]
Bedankt voor je verzoek. Ik kan dit helaas niet toevoegen, want dit project beperkt zich tot het uitlezen van de slimme meter en puur het opslaan/bekijken/exporteren van die gegevens. Ondanks dat ik de wens zelf heel goed snap natuurlijk. :]
