### ISSUE TITLE
Trends klok omdraaien

### ISSUE THREAD

**Issue by SaturnusDJ** [dennissiemensma/dsmr-reader#571]
Suggestie om de rotatie van de trendtijden om te draaien zodat het overeen komt met een klok.

**Comment by dennissiemensma** [comment]
Bedankt voor je suggestie! Het is destijds geen bewuste keuze geweest, maar het lijkt me inderdaad stukken logischer om het om te draaien, nu je het zo aankaart.

**Comment by dennissiemensma** [comment]
Gezien het letterlijk 1 regel code was, heb ik het alvast doorgevoerd. Gaat mee in de eerstvolgende release.

**Comment by SaturnusDJ** [comment]
Super wat snel. Fijne software. 👍

**Comment by dennissiemensma** [comment]
Daar is zeker wat voor te zeggen, echter gezien het het belangrijkste is om verhoudingen tussen de uren te zien, laat ik het voor nu op 1 cirkel staan voor 24 uur.
