### ISSUE TITLE
Stil on the old version after updating

### ISSUE THREAD

**Issue by Blackpander** [dennissiemensma/dsmr-reader#572]
Ik maak  gebruik van versie 1.26.1 van DSMR-Reader op een Raspberry Pi 3B.

Ik heb volgens de handleiding de volgende handelingen gedaan:

sudo su - dsmr
./deploy.sh

Dit verloopt allemaal goed alleen aan het eind staat er deployed version 1.26.1. Dus niet de laatste versie 1.27.

**Comment by dennissiemensma** [comment]
Bedankt voor je melding. Ik neem aan dat je niet op een aparte branch hebt gedraaid eerder?

Je kunt dit nog proberen:
```
sudo su - dsmr
git fetch
git checkout master
git pull
./deploy.sh
```

**Comment by dennissiemensma** [comment]
@Blackpander ben je hier nog uit gekomen?

**Comment by Blackpander** [comment]
Hi @dennissiemensma Ja, ik kreeg de melding dat ik moest comitten, omdat ik een lokale aanpassing had gemaakt. Wat uiteraard zo was aangezien ik een aanpassing heb gemaakt om het DSMR-Reader Dashboard in een iFrame te kunnen gebruiken.

Ik heb dit opgelost met:

`git reset --hard origin/master
./deploy.sh

`

**Comment by dennissiemensma** [comment]
Top. Je zou de tool overigens prima in een iFrame moeten kunnen gebruiken, zie ook dit oude ticket met daarin de oplossing. Dit raakt geen bestanden die onder versiebeheer staan:

https://github.com/dennissiemensma/dsmr-reader/issues/344#issuecomment-315523564

**Comment by Blackpander** [comment]
@dennissiemensma Thanks! base.py hersteld en dit toegevogd aan de settings.py :)
