### ISSUE TITLE
Voltages via MQTT

### ISSUE THREAD

**Issue by cranberryNL** [dennissiemensma/dsmr-reader#581]
@dennissiemensma In een eerdere vraag over het loggen van voltages heb je aangegeven dit in de toekomst wellicht in te gaan bouwen. Tevens gaf je toen de suggestie om gebruik te maken van MQTT om zo complete diagrammen (of delen daarvan) te loggen. Gisteren ben ik hier verder in gedoken en het ik krijg netjes de rauwe data vanuit de slimme door DSMR reader doorgestuurd!

Graag zou ik gebruik maken van de 'split topic' functie. Ik mis daar echter nog de mapping fields voor de spanning. Zou je dit t.z.t. bij één van de volgende updates wellicht een keer mee kunnen nemen? Of zie ik een mogelijkheid over het hoofd om dit zelf te realiseren?
Als het handig is hiervoor een DSMR5 telegram te ontvangen, laat het maar even weten.

**Comment by dennissiemensma** [comment]
Bedankt, dat lijkt me inderdaad een goed aanvulling! Ik ga pas medio april weer verder met ontwikkelen, dus het zal wel even duren.

**Comment by Giel538** [comment]
@dennissiemensma 

Hoi,
Ik heb nog een paar vraagjes/toevoegingen over MQTT.
De voltages/stromen zou ik er ook wel bij willen zien. 
Is het ook mogelijk om het actuele gasverbruik over MQTT te sturen? Misschien heb ik er over heen gekeken maar ik kon hem niet vinden. Voor een DSMR5 meter krijg je elke 5 minuten een update. Je zou dus de (nieuwe waarde) - (vorige meting) moeten uitrekenen en deze op MQTT beschikbaar maken. Je krijgt dan elke 5 minuten een update. 

Over updates gesproken. Nu worden alle MQTT berichten elke seconde eruit gezonden ook al is er geen update. Bijvoorbeeld de spannings dips en power failures komen amper voor maar per dag krijg ik wel 60x60x24= heel veel berichten.

**Comment by dennissiemensma** [comment]
Bedankt voor je suggesties. Dat zijn goede aanvullingen. Ik zal het meenemen indien mogelijk en anders splits ik ze als een aparte feature. Lijkt me nuttig.

**Comment by Giel538** [comment]
Ik las dat je af zelf geen dsmr5 meter had. Mocht ik iets moeten testen moet je het maar laten weten.

**Comment by dennissiemensma** [comment]
@Giel538 mbt je vraag over MQTT, is dat hetzelfde als in #611? Want anders stel ik voor om dat issue te volgen en eventueel aanvullingen te doen. Het is handiger om een apart issue te hebben per onderwerp.

**Comment by Giel538** [comment]
@dennissiemensma Ja hoor prima, komt op hetzelfde neer

**Comment by dennissiemensma** [comment]
Dit wordt een vervolg op #518, die waarschijnlijk over twee feature releases opgepakt wordt.

**Comment by dennissiemensma** [comment]
In aankomende release komen de voltages in het dashboard de database. Daarna kunnen MQTT en API als followup

**Comment by Giel538** [comment]
Top. ik ga er naar kijken!

**Comment by dennissiemensma** [comment]
Ik heb dit ook werkend, bleek zeer eenvoudig uit te breiden. Gaat mee in v2.6

**Comment by dennissiemensma** [comment]
Bij upgraden naar v2.5 is dit ook al mogelijk. De mapping is pas gedocumenteerd in v2.6, maar werkt ook al in v2.5.

JSON:
```
phase_voltage_l1 = phase_voltage_l1
phase_voltage_l2 = phase_voltage_l2
phase_voltage_l3 = phase_voltage_l3
```

Split-topic:
```
phase_voltage_l1 = dsmr/reading/phase_voltage_l1
phase_voltage_l2 = dsmr/reading/phase_voltage_l2
phase_voltage_l3 = dsmr/reading/phase_voltage_l3
```

**Comment by dennissiemensma** [comment]
Uitgebracht in [v2.6](https://github.com/dennissiemensma/dsmr-reader/releases/tag/v2.6.0).
