### ISSUE TITLE
Installatie lukt niet op Ubuntu server

### ISSUE THREAD

**Issue by eterpstra** [dennissiemensma/dsmr-reader#589]
Hallo Dennis,

Ik probeer een versie installatie te doen op een mini pc.
Het betreft  Ubuntu server 18.04.  Ik heb de snelle stappen doorlopen, maar nu loop ik vast op het volgende commando:

sudo sudo -u dsmr /home/dsmr/.virtualenvs/dsmrreader/bin/pip3 install -r /home/dsmr/dsmr-reader/dsmrreader/provisioning/requirements/base.txt -r /home/dsmr/dsmr-reader/dsmrreader/provisioning/requirements/postgresql.txt

Als ik dit invul dan krijg ik de volgende permission denied error:

The directory '/home/eterpstra/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/eterpstra/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting crcmod==1.7 (from -r /home/dsmr/dsmr-reader/dsmrreader/provisioning/requirements/base.txt (line 1))
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/home/eterpstra/.cache/pip/wheels/50/24/4d/4580ca4a299f1ad6fd63443e6e584cb21e9a07988e4aa8daac'
Consider using the `--user` option or check the permissions.

De vorige stappen heeft hij wel gewoon netjes doorlopen dus vraag mij af waar het hem in zit.

Kun jij hierbij helpen? Of wellicht iemand anders?

Gr,
Elroy

**Comment by jeroenpeters1986** [comment]
Hoi @eterpstra, onder welke user werk je normaalgesproken?

Zou je ook eens de output van `ls -la /home/eterpstra/.cache` willen posten? 

Het ziet er naar uit dat de dsmr user geen rechten heeft om te werken in de pip-map, die is nodig om de libraries te installeren

**Comment by dennissiemensma** [comment]
@eterpstra ben je hier inmiddels uit gekomen?

**Comment by jossie67** [comment]
Ik heb het zelfde issue maar dan iop Ubunut 16.04

<code>
WARNING: The directory '/home/jos/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
WARNING: The directory '/home/jos/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting crcmod==1.7 (from -r /home/dsmr/dsmr-reader/dsmrreader/provisioning/r
</code>

**Comment by dennissiemensma** [comment]
@jossie67 dit zijn slechts warnings, maar mogelijk zit je onder een verkeerde user. 

Ik heb wel wat meer context nodig over wat je aan het doen was, welke stap, etc. Krijg je verder nog foutmeldingen of lukt de installatie verder wel?

**Comment by eterpstra** [comment]
@dennissiemensma Ik heb het inmiddels voor elkaar. Bij mij was het inderdaad een rechten kwestie die niet goed stond. Er ontbrak een alias.

**Comment by dennissiemensma** [comment]
Top, bedankt voor je terugkoppeling
