### ISSUE TITLE
Geen data piektarief

### ISSUE THREAD

**Issue by broekieman** [dennissiemensma/dsmr-reader#591]
Alles werkt en ik heb grafiek en totaalstand van electriciteit, maar zie geen verbruik bij piektarief, enkel telwerk 1.

**Comment by dennissiemensma** [comment]
Bedankt voor je melding. Uit mijn hoofd zou ik niet zo 123 een oorzaak of oplossing weten. Helaas kan ik pas medio april inhoudelijk voor je kijken.

**Comment by broekieman** [comment]
Ik heb de tarieven nu samenvoegd. Het is vreemd dat het telwerk voor het 
piektarief niet werkt terwijl de grafieken tijdens de piek gewoon worden 
opgebouwd en de totaalstand van electra ook klopt.

Met vriendelijke groet,

Maarten Broekman

------ Origineel bericht ------
Van: "Dennis Siemensma" <notifications@github.com>
Aan: "dennissiemensma/dsmr-reader" <dsmr-reader@noreply.github.com>
Cc: "broekieman" <broekman@ziggo.nl>; "Author" 
<author@noreply.github.com>
Verzonden: 10-2-2019 14:35:26
Onderwerp: Re: [dennissiemensma/dsmr-reader] Geen data piektarief (#591)

**Comment by dennissiemensma** [comment]
@broekieman werkt het inmiddels naar behoren of heb je nog hulp nodig?

**Comment by broekieman** [comment]
Het loste zichzelf op, maar ik ben gestopt met de software. Dank voor je reactie. Met vriendelijke groet,Maarten Broekman-------- Oorspronkelijk bericht --------Onderwerp: Re: [dennissiemensma/dsmr-reader] Geen data piektarief (#591)Van: Dennis Siemensma Aan: dennissiemensma/dsmr-reader Cc: broekieman ,Mention @broekieman werkt het inmiddels naar behoren of heb je nog hulp nodig?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/dennissiemensma/dsmr-reader","title":"dennissiemensma/dsmr-reader","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/dennissiemensma/dsmr-reader"}},"updates":{"snippets":[{"icon":"PERSON","message":"@dennissiemensma in #591: @broekieman werkt het inmiddels naar behoren of heb je nog hulp nodig?"}],"action":{"name":"View Issue","url":"https://github.com/dennissiemensma/dsmr-reader/issues/591#issuecomment-483282211"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/dennissiemensma/dsmr-reader/issues/591#issuecomment-483282211",
"url": "https://github.com/dennissiemensma/dsmr-reader/issues/591#issuecomment-483282211",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by dennissiemensma** [comment]
Dank voor je reactie. In dat geval laat ik het voor wat het is.
