### ISSUE TITLE
8n1 115200    7n1 9600

### ISSUE THREAD

**Issue by Arnaud48** [dennissiemensma/dsmr-reader#593]
LET OP: Wegens verminderde beschikbaarheid tot aan medio april 2019,
        kan het zijn dat de auteur minder snel of helemaal niet in de
        gelegenheid is om te reageren. Zie ook issue #576.
----

### Jouw omgeving
*(Indien van toepassing)*
* DSMR-reader versie *(rechtsbovenin applicatie zichtbaar)*: `v1.X.Y`
* Hardware *(RaspberryPi 2, 3 of iets anders)*: `RaspberryPi X...`
* DSMR-protocol versie van slimme meter *(v2, v4 of v5)*: `v...`

### Bug, wens of iets anders
* Bijvoorbeeld stappen hoe een probleem te reproduceren is...
* Of simpelweg een beschijving van een feature die je graag wenst te zien...
De dsmr reader werkt op onze meter landis en gyr e350  8n1 115200 
Nu wil ook een andere meter meten dit is een ouder type een iskra mt832   7n1  9600 wat moet ik dan aanpassen , kan het niet vinden. 
Bedankt

**Comment by Arnaud48** [comment]
Ik zag wel bij status dat er metingen voor verwerking klaar staan en weer verwerkt worden, echter zie geen nieuwe grafiek, alleen die van dag daarvoor van andere meter.

**Comment by dennissiemensma** [comment]
Je kunt de instellingen hier wijzigen: https://dsmr-reader.readthedocs.io/nl/latest/admin/datalogger.htmlDe applicatie heeft verder (nog) geen ondersteuning voor verschillende of meerdere meters. Als je dezelfde instantie van dsmr-reader wisselt over meerdere meters, is de kans groot dat het niet goed verwerkt wordt.

**Comment by Arnaud48** [comment]
Ik had getest met de landis en gyr dat ging goed.
Ook de instelling naar dsmr 2... gezet. Systeem opnieuw opgestart.
Moest er dan nog iets gedaan worden? 
Bedankt

**Comment by dennissiemensma** [comment]
Je zult dan eigenlijk de database moeten leeggooien qua metingen en verwerkte data. Ik ben helaas niet in de gelegenheid om de exacte tabellen en commando's te maken voor je. Als alternatief kun je de hele database verwijderen en opnieuw aanmaken.

**Comment by dennissiemensma** [comment]
@Arnaud48 ben je hier inmiddels uit gekomen of heb je nog meer assistentie nodig?
