### ISSUE TITLE
1-fase VS 3-fase Graph differences

### ISSUE THREAD

**Issue by jorkzijlstra** [dennissiemensma/dsmr-reader#595]
### Jouw omgeving
*(Indien van toepassing)*
* DSMR-reader versie *(rechtsbovenin applicatie zichtbaar)*: `v1.2.8`
* Hardware *(RaspberryPi 2, 3 of iets anders)*: `RaspberryPi 1` 
* DSMR-protocol versie van slimme meter *(v2, v4 of v5)*: `v4.2`

### Bug, wens of iets anders
* Bijvoorbeeld stappen hoe een probleem te reproduceren is...
* Of simpelweg een beschijving van een feature die je graag wenst te zien...
I just turned on the 3-fase view since I have that and the overview graphs show different data.

![image](https://user-images.githubusercontent.com/15804835/52847434-78595600-310c-11e9-9c65-c496168349e0.png)

![image](https://user-images.githubusercontent.com/15804835/52847631-01708d00-310d-11e9-9c9f-4486192b1092.png)

I was expecting the first graph to be the aggregated version of the last one. Mainly the L+ metrics are missing from the first graph. To me it look like the top graph only show the L+ when for all 3 fases there is a positive number. When there is 0 for one of the metric is disappears

Regards, Jork Zijlstra

**Comment by dennissiemensma** [comment]
Bedankt voor je melding! Ik zal hier medio april inhoudelijk voor je naar kijken.

**Comment by jorkzijlstra** [comment]
Hoi Dennis, geen probleem. 

Ik ga ergens  deze week switchen naar een rock pi 4 en weet niet of de data mee kan komen. 
Heb je nog meer data nodig? Iets van bijvoorbeeld de data calls?

Grt, Jork

**Comment by dennissiemensma** [comment]
Ik denk dat ik daar op dit moment helaas weinig mee kan doen, maar ik laat dat tzt dan weten. Erg bedankt voor je aanbod!

**Comment by jorkzijlstra** [comment]
Ik dacht dat heel misschien de raspberry pi 1 te langzaam zou zijn en metingen zou missen (niet genoeg cpu cycles hebben om alles op te vangen). Nu had ik deze te leen om deze software te testen en heb nu zelf een Rock Pi B 4b aangeschaft en daar een nvme disk aan gehangen. Performance wise is er dus nu geen probleem meer, maar het probleem lijkt nog steeds aanwezig.

Ik heb de data ook kunnen overzetten naar mijn nieuwe setup. Laat het maar weten of je nog wat van mij nodig hebt als je er naar gaat kijken. 

Hierbij nog wat screenshot:
![screenshot from 2019-03-08 11-23-50](https://user-images.githubusercontent.com/15804835/54023370-159c2d00-4195-11e9-8de4-bc4d11e2bf10.png)

![screenshot from 2019-03-08 11-23-42](https://user-images.githubusercontent.com/15804835/54023381-1c2aa480-4195-11e9-9f8b-088e998a0ec1.png)

**Comment by dennissiemensma** [comment]
Bedankt voor je toevoeging. Ik zal het in april verder bekijken.

**Comment by dennissiemensma** [comment]
Zou je nog eens kunnen proberen uit te leggen wat je exact mist of niet goed is? Ik lees er waarschijnlijk overheen, maar ik wil zeker weten dat we over hetzelfde praten. :]

**Comment by jorkzijlstra** [comment]
Hoi Dennis,

Ten eerste maar even bevestigen dat ik de grafieken goed lees. Als ik beide grafieken namelijk lees op het zelfde tijdstip verwacht ik bij de bovenste grafiek hetzelfde totaal als in de onderste grafiek waarbij ik alle fasen samen op tel.

In de bovenstaande screenshots kan je zien dat bij de geaggregeerde versie 305W staat terwijl de som van de 3fase grafiek kom ik op 349W uit. Ook lever ik bij de 3 fase grafiek stroom terug terwijl in de andere grafiek ik niks terug lever.

Klopt mijn verwachting dus dat de geaggregeerde versie het totaal van de 3 fase versie zou moeten bevatten?

MvG, Jork

**Comment by dennissiemensma** [comment]
Aah juist, ik snap nu wat je bedoelt en ik zie hetzelfde bij mij thuis (ook zonder teruglevering). Kan het zijn dat je het "groeperen van metingen" aan hebt staan (standaard = aan)? Zo ja, dan worden gemiddeldes berekend over alle metingen binnen de minuut en dat is dan onnauwkeurig. 

De data van de twee grafieken komen namelijk uit verschillende waardes in het telegram uit je meter, dus het is niet iets wat de applicatie checkt of narekent. Ik ga er vanuit dat de slimme meter exact sluitende waardes geeft. Je kunt:

A) Het groeperen van metingen uitzetten en kijken of het dan wel klopt.

B) Of eerst even een telegram uit je slimme meter bekijken en hier posten, dan check ik even of de optelling daarvan inderdaad klopt (ik ga uit van wel). Als je het hier post, haal wel even de (twee) serienummers uit het telegram. Deze staat bijna bovenaan en de tweede staat in dezelfde regel als je gasstand.

**Comment by jorkzijlstra** [comment]
Hoi Dennis,

Bedankt voor je snelle reactie. Ik heb inmiddels de groeperen van metingen naar "per meting" gezet waardoor de grafiek idd gedetailleerde werd.

De grafiek is idd meer op elkaar gaan lijken, maar bevatten nog niet dezelfde waardes.

![Screenshot from 2019-04-16 21-00-05](https://user-images.githubusercontent.com/15804835/56237249-d31b1980-608b-11e9-9e3e-675d30f83157.png)

![Screenshot from 2019-04-16 20-58-58](https://user-images.githubusercontent.com/15804835/56237333-11b0d400-608c-11e9-94f5-f71ce66ebbfb.png)

![Screenshot from 2019-04-16 20-59-02](https://user-images.githubusercontent.com/15804835/56237335-14132e00-608c-11e9-80a4-6946c8fdb71e.png)
 
Een meting: 
´´´
1-3:0.2.8(50)
0-0:1.0.0(190416210449S)
0-0:96.1.1(.......)
1-0:1.8.1(000104.265*kWh)
1-0:1.8.2(000096.684*kWh)
1-0:2.8.1(000090.434*kWh)
1-0:2.8.2(000219.845*kWh)
0-0:96.14.0(0002)
1-0:1.7.0(00.127*kW)
1-0:2.7.0(00.000*kW)
0-0:96.7.21(00010)
0-0:96.7.9(00002)
1-0:99.97.0(1)(0-0:96.7.19)(000101010000W)(0000000506*s)
1-0:32.32.0(00007)
1-0:52.32.0(00010)
1-0:72.32.0(00010)
1-0:32.36.0(00000)
1-0:52.36.0(00000)
1-0:72.36.0(00001)
0-0:96.13.0()
1-0:32.7.0(233.1*V)
1-0:52.7.0(233.8*V)
1-0:72.7.0(232.9*V)
1-0:31.7.0(000*A)
1-0:51.7.0(000*A)
1-0:71.7.0(000*A)
1-0:21.7.0(00.003*kW)
1-0:41.7.0(00.000*kW)
1-0:61.7.0(00.124*kW)
1-0:22.7.0(00.000*kW)
1-0:42.7.0(00.000*kW)
1-0:62.7.0(00.000*kW)
0-1:24.1.0(003)
0-1:96.1.0(......)
0-1:24.2.1(190416210012S)(00139.128*m3)
!9A51
´´´

In welk bestand wordt deze meting geparsed? Ben zelf programmeur en kan python op zich wel lezen. Ik ben al wel even wezen spitten en vind het er logisch uit zien maar het parse gedeelte heb ik nog niet kunnen vinden.

Grt, Jork

**Comment by dennissiemensma** [comment]
In principe zijn het deze regels in het telegram en dat lijkt wel goed:

```
1-0:1.7.0(00.127*kW)

1-0:2.7.0(00.000*kW)

...

1-0:21.7.0(00.003*kW)
1-0:41.7.0(00.000*kW)
1-0:61.7.0(00.124*kW)

1-0:22.7.0(00.000*kW)
1-0:42.7.0(00.000*kW)
1-0:62.7.0(00.000*kW)
```

Het parsen gebeurt in: https://github.com/dennissiemensma/dsmr-reader/blob/master/dsmr_datalogger/services.py#L170

Ik zie hier zelf trouwens wisselende gegevens. Soms komen de drie-fasen exact overeen en soms niet. Wellicht goed om nog wat extra telegrammen te bekijken om te zien of je van hetzelfde last hebt.

**Comment by jorkzijlstra** [comment]
Hoi Dennis,

Het lijkt inderdaad de meter te zijn. Ik zie hier ook dat soms de drie-fasen exact overeen en soms niet.

[meter_log-1604.txt](https://github.com/dennissiemensma/dsmr-reader/files/3091144/meter_log-1604.txt)

Even een grote aanname: als programmeur kan ik mij voorstellen dat voor de totalen iets van windowing gedaan wordt, waardoor je eventueel dit soort gedrag kan krijgen.

In ieder geval bedankt voor het helpen nakijken

**Comment by dennissiemensma** [comment]
Bedankt voor je terugkoppeling. Ik kan daar dus helaas niet veel aan doen. Heb je nog andere vragen m.b.t. dit issue?

**Comment by jorkzijlstra** [comment]
Hoi Dennis, geen andere vragen meer en ik sluit dit issue dan ook.

Grt, Jork
