### ISSUE TITLE
Missing dsmr-reader directory during configuration

### ISSUE THREAD

**Issue by Zilv3r** [dennissiemensma/dsmr-reader#597]
I'm following the tutorial at https://dsmr-reader.readthedocs.io/nl/latest/installation/explained.html

System: Raspberry Pi with Hassbian

At the end of step 6 I'm encountering an error when logging out (ctrl-d) and logging in (sudo su - dsmr):

`-su: cd: /home/dsmr/dsmr-reader: No such file or directory`

The prompt says:

`(dsmrreader) dsmr@hassbian:~ $`

**Comment by Zilv3r** [comment]
Found the problem: I did not log in as dsmr user before cloning the git step 5

**Comment by dennissiemensma** [comment]
Bedankt voor je terugkoppeling, fijn dat je het zelf zo snel hebt gevonden!

**Comment by Zilv3r** [comment]
Dank voor je reactie. En wat een fantastisch programma! :-)

Wat ik nog wel een beetje vreemd vond bij de installatie volgens het stappenplan 'Installatie: Toegelicht' was het commando:

`sudo sudo -u postgres psql -c "alter user dsmrreader with password 'dsmrreader';"`

Ik heb dit letterlijk ge-copy-paste, maar het was voor mij niet duidelijk of dat de bedoeling was (of dat ik tussen de quotes nog een wachtwoord moest invullen ofzo). Misschien dat anderen daar ook tegenaan lopen en dat het handig is dit nog even expliciet te melden in het stappenplan. Het draait hier in elk geval helemaal super volgens mij.

**Comment by dennissiemensma** [comment]
Bedankt voor je toevoeging. Het wachtwoord staat ook in een van de configs, dus als je die zo hebt overgenomen is dat prima. Indien gewenst kan men het wachtwoord wijzigen, maar ik denk dat de user-case daarvoor vrij beperkt is.
