### ISSUE TITLE
Stroomverbruik per fase via remote datalog?

### ISSUE THREAD

**Issue by Gerben321** [dennissiemensma/dsmr-reader#599]
Hoi allemaal,

Ik gebruik de meest recente versie van dit mooie stukje software sinds vandaag met een Docker image. Werkt allemaal prima. Ik heb een raspberry in de meterkast staan die via de V1 API remote datalog de ruwe telegrams doorstuurt.

Ik krijg netjes mijn verbruik te zien, maar ik zie geen onderscheid in fases? Zie ik iets over het hoofd of werkt dat niet momenteel via deze manier van data verzamelen? Ik zie wel voor de drie fases in huis de storingen.

Ik krijg wel netjes het verbruik per fase te zien via bijvoorbeeld Home Assistant als ik dat configureer via ser2net (los van DSMR reader verder).

Bij voorbaat dank!

**Comment by dennissiemensma** [comment]
Bedankt voor je opmerking, wellicht moet ik dat in de toekomst nog wat meer verduidelijken voor andere gebruikers (of met een eenmalige intro na installatie) . Het is nu niet altijd even helder denk ik, dus logisch dat je even moest zoeken.
