### ISSUE TITLE
hoe gaat dsmr-reader om met server downtime?

### ISSUE THREAD

**Issue by RezzZ** [dennissiemensma/dsmr-reader#603]
Ik kan het in de [FAQ](https://dsmr-reader.readthedocs.io/en/latest/) niet zo 123 vinden.

Hoe gaat dsmr-reader om met server downtime ivm het updaten van je system of eventuele crashes? Heb ik dan een gat in mijn totale verbruik of wordt dat bij de eerst volgende ontvangen telegram netjes gecorrigeerd? Ik denk het laatste maar hoor het graag!

Misschien kan deze vraag in de FAQ toegevoegd worden?

**Comment by dennissiemensma** [comment]
In principe wordt het totale verbruik hersteld en heb je dan alleen een gat of verschuiving in de detailweergave. Als de downtime over de dagwisseling heen schuift, dan kan het zijn dat het verbruik op de volgende dag wordt gerekend. In de meeste gevallen is dat niet erg denk ik.

**Comment by RezzZ** [comment]
duidelijk! bedankt voor de toelichting
