### ISSUE TITLE
Archive: View past days details

### ISSUE THREAD

**Issue by dennissiemensma** [dennissiemensma/dsmr-reader#61]
The history page only displays the day totals (of the last X weeks) and the dashboard only of the last hours or days. 

it should be possible to display a full day with summary and 24 data point in graph for each hour using `HourStatistics` models.

**Comment by dennissiemensma** [comment]
Done after adding some tests.

**Comment by dennissiemensma** [comment]
Deployed and works!

**Comment by dennissiemensma** [comment]
@jeroenpeters1986 deze feature is ook klaar, ik denk dat je hem wel tof vindt. Nieuw menu item met archief-optie om (eindelijk) door alle voorgaande dagen heen te bladeren. :]

**Comment by jeroenpeters1986** [comment]
Ik ben al aan het deployen :)

**Comment by jeroenpeters1986** [comment]
Heel erg gaaf, vette interface ook!
Happy user :))
