### ISSUE TITLE
MQTT publiceert vaker dan nodig?

### ISSUE THREAD

**Issue by RezzZ** [dennissiemensma/dsmr-reader#611]
### Jouw omgeving
* DSMR-reader versie *(rechtsbovenin applicatie zichtbaar)*: `v1.28`
* Hardware *(RaspberryPi 2, 3 of iets anders)*: `RaspberryPi 3B+`
* DSMR-protocol versie van slimme meter *(v2, v4 of v5)*: `v5`

### Bug, wens of iets anders
MQTT publiceert veel frequenter dan noodzakelijk. Ik vermoed dat bij elk ontvangen telegram DSMR reader alles publiceert wat staat ingeschakeld. Ook dagstatistieken, ookal kunnen deze urenlang hetzelfde (bv bij gasverbruik). Is dit niet een beetje overbodig? of is de overhead voor de broker zo laag dat de effort om code te schrijven om alleen wijzigingen te publiceren hier niet tegen op weegt?

**Comment by dennissiemensma** [comment]
Bedankt voor je aanvulling. Als ik het me goed herinner liep iemand recent tegen hetzelfde aan. Ik zal kijken of ik dit eenvoudig kan realiseren, wanneer ik weer aan de slag ga.

**Comment by trizz** [comment]
Wellicht is het dan wel een idee om de [`retain`](http://www.steves-internet-guide.com/mqtt-retained-messages-example/) flag te zetten om ervoor te zorgen dat systemen die de MQTT data gebruiken niet hoeven wachten op een statuswijziging als deze herstart worden.

**Comment by dennissiemensma** [comment]
Pak ik op via #723. Ik zal kijken of dat werkbaar is.
