### ISSUE TITLE
Meter statistieken weergeven wanneer leeg

### ISSUE THREAD

**Issue by vincentweeda** [dennissiemensma/dsmr-reader#625]
### Jouw omgeving
* DSMR-reader versie : v2.0.2
* Hardware: RaspberryPi 3
* DSMR-protocol versie van slimme meter:  v4.2
* Python versie (sudo su - dsmr):  3.5.3

### Bug
Wanneer ik de statistieken opvraag van mijn slimmemeter in het admin menu via de optie "DSMR Meter statistics (readonly)" krijg ik  sinds de nieuwe versie data terug.

Als ik kijk op het dashboard onder "Statistics" is het blok van de meter statisieken leeg. 

Zie ook de screenshots ter (hopelijk) verduidelijking.

![Meterstats_admin](https://user-images.githubusercontent.com/13239975/56573465-65a64600-65c1-11e9-87f6-31e9bc733c8a.PNG)
![Meterstats_dashboard](https://user-images.githubusercontent.com/13239975/56573466-663edc80-65c1-11e9-8eab-fa20b9cc797d.PNG)

**Comment by dennissiemensma** [comment]
Dat is vreemd. Kun je eens in de database kijken of je gegevens ziet?

```
sudo su - postgres
psql dsmrreader
select * from dsmr_datalogger_meterstatistics;
```

**Comment by vincentweeda** [comment]
De volgende info is zichtbaar in de database; 

`
 id |       timestamp        | electricity_tariff | power_failure_count | long_power_failure_count | voltage_sag_count_l1 | voltage_sag_count_l2 | voltage_sag_count_l3 | voltage_swell_count_l1 | voltage_swell_count_l2 | voltage_swell_count_l3 | rejected_telegrams | dsmr_version
----+------------------------+--------------------+---------------------+--------------------------+----------------------+----------------------+----------------------+------------------------+------------------------+------------------------+--------------------+--------------
  1 | 2019-04-23 16:20:11+00 |                  2 |                   0 |                        0 |                    0 |                      |                      |                      0 |                        |                        |                  0 | 42
(1 row)
`

**Comment by dennissiemensma** [comment]
Het lijkt erop dat de gegevens wel bijgewerkt worden, maar dat ze leeg zijn. Alsin dat de meter zegt dat er geen storingen enzo geweest zijn. Als er geen gegevens zijn omte tonen, worden ze verborgen.

Dus in dat opzicht klopt het, ware het niet dat ik dan eigenlijk ook nog het kopje moet verbergen in dit geval.

**Comment by vincentweeda** [comment]
Dat zou het wel duidelijker maken denk ik. Of eventueel de waardes ook weergeven indien ze nul zijn?

**Comment by dennissiemensma** [comment]
Ik zal er over nadenken wat handig is.

**Comment by dennissiemensma** [comment]
Ik heb het visueel aangepast voor de volgende versie. Ze worden altijd getoond. Als ze leeg zijn, staat er straks een `-`.
