### ISSUE TITLE
Inladen oude gegevens gaat mis met live gas consumption

### ISSUE THREAD

**Issue by drvdijk** [dennissiemensma/dsmr-reader#646]
### Mijn omgeving
* DSMR-reader versie *(rechtsbovenin applicatie zichtbaar)*: `v2.1`
* Hardware *(RaspberryPi 2, 3 of iets anders)*: `RaspberryPi 3B+`
* DSMR-protocol versie van slimme meter *(v2, v4 of v5)*: `v5`

### Bug, wens of iets anders
* Zoals @conradhagemans in https://github.com/dennissiemensma/dsmr-reader/issues/520#issuecomment-422726493_ noemde, loop ik ook tegen negatieve gaswaarden aan. Dit bij het importeren van oude data vanuit InfluxDB waarbij ik alle originele meetwaarden van het afgelopen jaar transformeer naar SQL inserts voor de `dsmr_datalogger_dsmrreading` tabel met `processed = 'f'`.
* extra vraag: het afgelopen half jaar dus, dat is grofweg 15 miljoen datapunten. Is dit "veel" voor dsmr-reader? Ik ben nu alleen nog bezig geweest met importeren van een klein beetje data op een dev-omgeving die een stuk sneller is dan de Raspberry Pi 3B+ waar het straks op moet draaien, maar misschien is 15 miljoen punten wat overdreven?

Ik ben een beetje aan het prutsen geslagen (ik ben niet dagelijks met Python bezig), en denk een oplossing gebakken te hebben. PR komt eraan.

**Comment by dennissiemensma** [comment]
Kan het zijn dat je toevallig DSMR-reader's `dsmr_backend` proces al hebt draaien terwijl je aan het importeren bent? En dat die data niet perse op volgorde staat? Het belangrijkste is dat het tijdstip klopt, want [daar sorteert die als het goed is ook op](https://github.com/dennissiemensma/dsmr-reader/blob/v2.1.0/dsmr_datalogger/models/reading.py#L116) bij het verwerken.

----

Wat betreft je andere vraag. Het aantal datapunten maakt niet uit, alleen kan het wat langer duren voordat die alles gehad heeft. Uiteindelijk wordt alle data omgezet naar twee tabellen: Dagstatistieken (1 record per dag) en uurstatistieken (24 records per dag). Dat zijn ook de tabellen waar alle informatie uit het Archief gehaald en getoond wordt.

Dus ja, 15 miljoen datapunten zijn wat overdreven, maar je kunt ze prima importeren. En als alles geimporteerd en verwerkt is, kun je retentie aanzetten in de applicatie, waardoor die alle oude meetdata weggooit.

**Comment by drvdijk** [comment]
Op het moment van importeren (`cat historical.sql | docker exec -i dsmrdb psql -U dsmrreader`) draait `dsrm` in het geheel niet: in mijn ontwikkelomgeving draai ik de docker variant van `dsmr`.

Hoe zo'n `historical.sql` eruit ziet:

```
COPY public.dsmr_datalogger_dsmrreading ("timestamp", electricity_delivered_1, electricity_returned_1, electricity_delivered_2, electricity_returned_2, electricity_currently_delivered, electricity_currently_returned, extra_device_timestamp, extra_device_delivered, processed, phase_currently_delivered_l1, phase_currently_delivered_l2, phase_currently_delivered_l3, phase_currently_returned_l1, phase_currently_returned_l2, phase_currently_returned_l3) FROM stdin;
2019-05-23T21:00:00.538844072Z	1529.436	1.535	1606.904	0	0.181	0	2019-05-23T21:00:00.538844072Z	1757.587	f	\N	\N	\N	\N	\N	\N
2019-05-23T21:00:01.541137278Z	1529.436	1.535	1606.904	0	0.179	0	
......
2019-05-23T21:00:00.538844072Z	1757.587	f	\N	\N	\N	\N	\N	\N
\.
```

**Comment by dennissiemensma** [comment]
In dat geval zal ik er een test voor schrijven om te kijken waar dat in zit en of ik het gereproduceerd krijg. Mogelijk dat ik er vandaag nog aan toekom en anders wordt het pas volgende week vermoed ik.

**Comment by drvdijk** [comment]
Ha, je was net te snel met reageren voor ik m'n comment aangevuld had met meer informatie!

Zoals ik het in mijn hoofd heb zitten heeft dit puur met het "live verbruik" van gas te maken. Dat wordt niet in de telegrammen meegestuurd, dus moet je die berekenen aan de hand van de voorgaande waarde. En dat doet-ie dus prima bij normaal gedrag, en met mijn PR ook bij het invoegen van nieuwe meetpunten.

Ik bedenk me wel een ander probleem wat nog niet opgelost is. Zodra het historisch meetpunt `B` (met als "live verbruik" `currently_delivered` het verschil tussen voorgaand punt `A` en dit punt `B`) is ingevoegd, moet ook het eerstvolgende meetpunt `C` aangepast worden. Die was immers berekend aan de hand van het verschil tussen `A` en `C`.

---

Dank voor het antwoord op de vele-punten-vraag! Tsja, dat wordt dan maar even doorploeteren op die Raspberry Pi... Of eerst in influxdb een continous query maken om te downsampelen en dan dat te importeren... Hmm even over nadenken :) En voorlopig nog even niet alle oude data weggooien!

**Comment by dennissiemensma** [comment]
Bedankt voor de toelichting.De applicatie houdt inderdaad geen rekening met data die eerder is verwerkt, om daar vervolgens weer nieuwe data vóór te stoppen.

Wat je echter wel kan doen is alle geaggregeerde data weggooien, alle metingen resetten en vervolgens alles opnieuw laten berekenen. Daarmee los je ook het probleem op van de historische meetpunten.

Dus:
* Normale data importeren
* Historische data importeren
* Alle afgeleide data verwijderen en metingen resetten
* DSMR-reader weer aanzetten en begint weer bij de allereerste meting met alles opnieuw te berekenen

Dat kan alleen als je dus alle metingen nog hebt, ook de bestaande in je applicatie.

Het punt:
* Alle afgeleide data verwijderen en metingen resetten

Kan al met:

```
./manage.py dsmr_backend_delete_aggregated_data --help
```

Waarschijnlijk wil je alles resetten, dus:

```
./manage.py dsmr_backend_delete_aggregated_data --consumption --statistics --readings
```

Je kunt dat nog even proberen in je testomgeving.

**Comment by drvdijk** [comment]
Ik draai nu inderdaad nog even de
```
./manage.py dsmr_backend_delete_aggregated_data --consumption --statistics --readings
```
met de code voor de aanpassing. Hoewel die nog bezig is met de ~200.000 punten, kan ik nu al zien dat hij de data in `dsmr_consumption_gasconsumption` inderdaad chronologisch opbouwt, en daarmee het probleem ook zou verhelpen. Dan komt het probleem verder alleen nog in de API voor lijkt me?

**Comment by dennissiemensma** [comment]
Dat is fijn om te horen. Wat betreft de API. Deze is eigenlijk bedoeld voor live-dataloggers, alsmede de rest van het project. 

Desnietemin vind ik het niet erg om aan de achterkant wat ondersteuning te hebben voor hobbyisten, zoals met `dsmr_backend_delete_aggregated_data` al gedaan is. In principe is dat ook te gebruiken wanneer alle data met terugwerkende kracht via de API aangemaakt wordt.

Ik zal kijken of de fix uit je pull-request testbaar te maken is, maar ook dat is niet waterdicht. Uiteindelijk zal men toch hun backend-proces moeten stoppen, maar wie weet helpt het al iets.

**Comment by dennissiemensma** [comment]
Ik heb je verbetering meegenomen in 70c7311ce6f9dd1eead1a66689517fdc0dd7b6dc. Nogmaals bedankt.

**Comment by drvdijk** [comment]
Geen dank, leuk bij te dragen!
