### ISSUE TITLE
problemen met installatie

### ISSUE THREAD

**Issue by eterpstra** [dennissiemensma/dsmr-reader#663]
Hallo Dennis,

Inmiddels heeft een vriend van mij ook interesse in jouw software. Helaas gaat het installeren weer niet goed. Ik heb de handleiding step bij step gevolgd.

Ik heb ubuntu server 19 geinstalleerd.
Ik loop vast op het volgende stukje:

virtualenv ~/.virtualenvs/dsmrreader --no-site-packages --python python3

Ik ben ingelogd als DSMR user maar krijg dan deze error:

```
Please use the *system* python to run this script
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 2375, in <module>
    main()
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 724, in main
    symlink=options.symlink)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 946, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.6/posixpath.py", line 378, in abspath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

```

Heb jij enige idee wat er fout gaat?

**Comment by dennissiemensma** [comment]
Ik heb deze foutmelding nog niet eerder gezien. Het lijkt iets met Python of de virtualenv. 

Welke versie van Ubuntu 19 gebruik je? De laatste minor? Kun je `lsb_release -a` doen en terugkoppelen wat die aangeeft?

Ik zal dan eens kijken of ik het kan reproduceren, want ik zou niet zo 1-2-3 weten waar dit door komt.

**Comment by eterpstra** [comment]
Hi Dennis,

Ik zie dat het toch nog om versie 18 gaan:

Distributor ID: Ubuntu                                                                                                                                                                                                                    
Description:    Ubuntu 18.04.2 LTS                                                                                                                                                                                                        
Codename:       bionic

**Comment by eterpstra** [comment]
Overigens lees ik hier ook nog iets over op een ander stukje van het forum:

https://github.com/aws/chalice/issues/275

**Comment by eterpstra** [comment]
Dennis,

Hij mag dicht. Ik heb per ongeluk de virtual env als sudo user gedaan en niet als dsmr.

**Comment by dennissiemensma** [comment]
Bedankt voor je update en fijn dat je het zo snel gevonden hebt!
