### ISSUE TITLE
API v1 doet 't niet?

### ISSUE THREAD

**Issue by ThaStealth** [dennissiemensma/dsmr-reader#664]
Hi Dennis,

### Jouw omgeving
* DSMR-reader versie *(rechtsbovenin applicatie zichtbaar)*: `v2.1.0`
* Hardware *(RaspberryPi 2, 3 of iets anders)*: `Docker (xirixiz/dsmr-reader-docker:latest)'
* DSMR-protocol versie van slimme meter *(v2, v4 of v5)*: `v5`

### Bug, wens of iets anders
Als ik naar http://IP:PORT/api/v1/datalogger/dsmrreading ga krijg ik een HTTP405 (method not allowed).
De v2 API op http://IP:PORT/api/v2/datalogger/dsmrreading doet het wel. Het lijkt erop dat de API v1 versie niet luistert? Hoe kan ik dit verder debuggen?

**Comment by ThaStealth** [comment]
Nvm, ik moet posten ipv getten...

**Comment by ThaStealth** [comment]
Ik gebruikte de GET ipv POST

**Comment by dennissiemensma** [comment]
Bedankt voor je terugkoppeling en fijn dat je het zelf al zo snel gevonden had!
