### ISSUE TITLE
Standen kloppen niet meer na meterwissel

### ISSUE THREAD

**Issue by ThaStealth** [dennissiemensma/dsmr-reader#666]
### Jouw omgeving
*(Indien van toepassing)*
* DSMR-reader versie *(rechtsbovenin applicatie zichtbaar)*: `v2.1`
* Hardware *(RaspberryPi 2, 3 of iets anders)*: `Docker`
* DSMR-protocol versie van slimme meter *(v2, v4 of v5)*: `v.5`

Ik denk dat je over deze usecase misschien niet nagedacht hebt (wat ook logisch is want zo vaak zal een meter niet gewisseld worden)
Ik heb een nieuwe slimme meter gekregen, de meterstanden zijn dus bij 0 begonnen. Alle weergaven kloppen met selecties binnen deze overvang met de historische weergave kloppen dus ook niet meer. Bijvoorbeeld, mijn huidige energiecontract periode denkt dat ik geld moet terugkrijgen omdat de stand nu stukken lager is dan waar ik mee begon.

Ik weet niet of je hier tijd in wilt steken (lijkt me nogal een omvangrijke aanpassing) voor een wat nu een edge case is. Maar een optie om een "meterwissel" toe te voegen lijkt me wel handig voor de toekomst, de huidige generatie slimme meters zal ooit vervangen worden (mijn gok is als 3G/4G uit gaat)

**Comment by dennissiemensma** [comment]
Bedankt voor je melding. Het klopt dat ik daar geen rekening mee heb gehouden en er staat ook een issue voor open: #507

Als het goed is heb je hier één dag last van en daarna zou die weer goed moeten gaan. Je kunt voor de foute dag zelf de gegevens corrigeren. Zie hier voor meer informatie: https://github.com/dennissiemensma/dsmr-reader/issues/507#issuecomment-407127424

Mocht je er toch niet uitkomen of tegen iets anders aanlopen, dan hoor ik het graag!
