### ISSUE TITLE
Gas wordt niet verwerkt uit telegram bij digitale meters in België

### ISSUE THREAD

**Issue by floyson-reference** [dennissiemensma/dsmr-reader#697]
DSMR-reader versie: v2.2.3
* Hardware: RaspberryPi 3
* DSMR-protocol versie van slimme meter v5

Bug:
Bij digitale meters in België wordt gas niet herkend, terwijl het wel in het telegram zit.
![image](https://user-images.githubusercontent.com/42807373/63461355-bc7d3880-c458-11e9-9e89-5bcded7c5a8c.png)

**Comment by dennissiemensma** [comment]
Bedankt voor je melding! Heb je toevallig meer informatie over andere verschillen tussen de telegrammen?

**Comment by dennissiemensma** [comment]
Heb je trouwens bovenstaand telegram in tekst-vorm? 

Je mag de twee serienummers wel weglaten. Dat zijn de regels die beginnen met:
```
0-0:96.1.1(
0-1:96.1.0(
```

**Comment by floyson-reference** [comment]
Dag Dennis,

Telegram:

/FLU5\253769484_A

0-0:96.1.4(50213)
0-0:96.1.1(…)
0-0:1.0.0(190821210025S)
1-0:1.8.1(000260.129*kWh)
1-0:1.8.2(000338.681*kWh)
1-0:2.8.1(000000.010*kWh)
1-0:2.8.2(000000.425*kWh)
0-0:96.14.0(0002)
1-0:1.7.0(00.261*kW)
1-0:2.7.0(00.000*kW)
1-0:32.7.0(231.0*V)
1-0:52.7.0(000.0*V)
1-0:72.7.0(230.9*V)
1-0:31.7.0(000*A)
1-0:51.7.0(000*A)
1-0:71.7.0(000*A)
0-0:96.3.10(1)
0-0:17.0.0(999.9*kW)
1-0:31.4.0(999*A)
0-0:96.13.0()
0-1:24.1.0(003)
0-1:96.1.1(...)
0-1:24.4.0(1)
0-1:24.2.3(190821210011S)(00029.553*m3)
!BE13

Mvg
Frederic

**Comment by dennissiemensma** [comment]
Bedankt! Ik heb er nu een generiekere oplossing voor gemaakt die ook werkt wanneer de gasmeter op bus 1,2 of 3 zit. Ik neem het mee voor de volgende release. Tot die tijd kun je gerust je eigen fix gebruiken.

**Comment by floyson-reference** [comment]
Ok dankjewel!

Mvg
Frederic Loyson

Op 22 aug. 2019 om 18:25 heeft Dennis Siemensma <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Bedankt! Ik heb er nu een generiekere oplossing voor gemaakt die ook werkt wanneer de gasmeter op bus 1,2 of 3 zit. Ik neem het mee voor de volgende release. Tot die tijd kun je gerust je eigen fix gebruiken.

**Comment by dennissiemensma** [comment]
Onderdeel van nieuwe release [v2.3](https://github.com/dennissiemensma/dsmr-reader/releases/tag/v2.3.0).

**Comment by dennissiemensma** [comment]
In #750 heb ik dit anders opgelost. Zou moeten blijven werken gezien ik bovenstaand telegram als automatisch test heb gebruikt.
