### ISSUE TITLE
DSMR remote data logger als docker image op een Synology NAS

### ISSUE THREAD

**Issue by jan-dewit** [dennissiemensma/dsmr-reader#709]
Ik heb DSMR draaien als Ubuntu VM, en dat werkt prima, echter heb ik nog geen data.
Nu is het zo dat mijn NAS erg dicht in de buurt staat van mijn slimme meter.
Ik heb dus de kabel in mijn NAS geprikt, en de UsbSerialDrivers van Jadahl geinstalleerd.
zie: http://www.jadahl.com/drivers_6.2/?arch=apollolake

Dit werkt allemaal feilloos, USB poort wordt herkend, nu alleen de missing link nog om de data die het stuurt naar DSMR te krijgen.

Ik dacht gebruik te kunnen maken van het volgende docker image:
https://github.com/trizz/dsmr-remote-datalogger

Maar dit image is specifiek gemaakt voor een RaspberryPi, en werkt niet op andere architectuur.
Al denk ik zelf dat dit niet zo heel veel aanpassingen vereist (aanname van iemand die er zelf geen ervaring mee heeft)

Is er iemand die iets gelijkwaardigs heeft gebouwd/bedacht? Tips/Tricks zijn welkom.

**Comment by dennissiemensma** [comment]
Wellicht kun je de seriele poort van je kabel doorlussen in de VM. Binnen de VM kun je dan de standaard datalogger gebruiken.

Als alternatief kun je op je VM-host de datalogger installeren en configureren zodat die het doorstuurt naar DSMR-reader binnen de VM. Daarvoor zul je dan de http(s) poort op je VM moeten openzetten voor je host (voor zover dat al niet standaard gebeurt).

**Comment by jan-dewit** [comment]
Hi Dennis, voor de volledigheid: ik heb een VM-host, en ik heb een NAS. 
DSMR draait op de VM, en de USB kabel zit in de NAS, en daartussen zit wel IP connectiviteit maar meer dan 40 meter, dus geen mogelijkheid om USB daar heen te brengen. 
The magic moet dus echt gebeuren op de Synology NAS, maar hoe?

**Comment by dennissiemensma** [comment]
Ik heb zelf helaas geen ervaring met dataloggers op een NAS. Ik neem aan dat je niet een (oude) RaspberryPi hebt liggen?

Als er Unix op draait kun je het waarschijnlijk wel werkend krijgen, maar ik vermoed dat het iets is als een Synology?

**Comment by trizz** [comment]
@jan-dewit Gisteren heb ik een multi-arch Docker image gebouwd van de remote datalogger, momenteel nog als 'test' onder de tag `develop`. Hierin heb ik geprobeerd de meest gebruikte architecturen te ondersteunen. Ik heb 'm zelf nog niet op een Synology getest, maar ik verwacht dat het wel werkt. De ondersteunde architecturen in de `develop` tag:
```
    linux/amd64
    linux/arm64
    linux/386
    linux/arm/v7
    linux/arm/v6
```

Graag hoor ik van je of dit je probleem oplost. Als er verder geen problemen naar boven komen (o.a. vanuit [deze](https://github.com/dennissiemensma/dsmr-reader/issues/714) issue) zal ik die image binnenkort naar `latest` builden.

**Comment by jan-dewit** [comment]
@trizz Ik heb 'm geinstalleerd en draait op dit moment perfect, de P1 data wordt netjes aan DSMR doorgegeven. Als ik bijzonderheden tegen kom, zal ik die melden.

Bedankt voor je bijdrage en tijd, dit werkt op deze manier echt fantastisch!

**Comment by dennissiemensma** [comment]
Super om te horen, bedankt trizz! Voor nu sluit ik deze dan.

**Comment by trizz** [comment]
@jan-dewit Zojuist heb ik de 'develop' versie een release gegeven, je kunt nu ook de `latest` of `v1` tag gebruiken. Zie de [readme](https://github.com/trizz/dsmr-remote-datalogger#versioning) voor meer informatie betreffende de te gebruiken tags.
