### ISSUE TITLE
MQTT - delete messages

### ISSUE THREAD

**Issue by remcoongit** [dennissiemensma/dsmr-reader#724]
*Bedankt voor het aanmaken van een issue!*
### Wat gebruik je?
v2.4.0 - 2019-09-19
VM debian
protocol v2/v4 maakt niet zoveel uit

### Bij fouten
http://ip/status
MQTT messages | Queued messages: 14,712,528
Ik was vergeten mqtt berichten uit te zetten. Heb zelf in homeassistant een script gemaakt die via http de status ophaalt.

Hoe kan ik die berichten weggooien?

**Comment by dennissiemensma** [comment]
```
sudo su - postgres
psql dsmrreader

# Query
truncate table dsmr_mqtt_message;
```

**Comment by remcoongit** [comment]
Worked like a charm!

**Comment by dennissiemensma** [comment]
Ik zal er sowieso voor zorgen dat dit in een volgende release niet meer gebeurt. Het heeft geen zin om 14M berichten in te plannen als die toch niet verstuurd worden namelijk.
