### ISSUE TITLE
overwerkte telegrammen

### ISSUE THREAD

**Issue by style2k** [dennissiemensma/dsmr-reader#725]
![image](https://user-images.githubusercontent.com/55606882/65984901-05c19e80-e481-11e9-8a4e-f36a43d115ec.png)

ik kijk in het status scherm en zie dit , heeft dit invloed op de metingen ??

**Comment by dennissiemensma** [comment]
Je kunt kijken of je wat ziet in de log van `dsmr_backend`: https://dsmr-reader.readthedocs.io/nl/latest/troubleshooting.html#logging

**Comment by style2k** [comment]
[dsmr_backend.log](https://github.com/dennissiemensma/dsmr-reader/files/3677815/dsmr_backend.log)

dit is de log file ik zie iets van een netwerk maar de pi heeft gewoon verbinding met het netwerk

**Comment by dennissiemensma** [comment]
Hij probeert verbinding te maken met de mailserver die je insteld hebt vermoed ik. Kan het zijn dat daar wat mee is?

Desnietemin zou dat niet de rest moeten ophouden, dus ik zal daar wat dieper naar kijken.

**Comment by dennissiemensma** [comment]
Ik heb het even geprobeerd en ondanks de foutmelding, zou die wel telegrammen moeten verwerken, zoals bedoeld. Je kunt de logging op `DEBUG` zetten (zie eerdere link) voor meer informatie over wat het proces exact doet.

**Comment by style2k** [comment]
o ok naja heb email config ff uitgezet en heb nog precies hetzelfde/
kan de file niet wegschrijven  na ik die aangepast heb
is dat niet in dsmr  te zetten dat je een logfile kan zien ofzo . dat command line gebeuren heb ik echt nix mee

**Comment by style2k** [comment]
ik zie overigens wel dat de onverwerkte telegrams afnemen heel langzaam nadat ik dus de email backup heb uitgezet

**Comment by jeroenpeters1986** [comment]
@style2k, deed de backups via een eigen server of via Gmail? Ik heb voor
gmail andere instellingen gebruikt namelijk omdat ik bij de instellingen
uit de suggestie je een foutmelding krijgt achter een IPv6 ipadres (wat ik
thuis uitgaand heb).

**Comment by style2k** [comment]
via een gmail adres en daar heb ik de gegevens ingevuld die er bij stonden 

Heb je GMail? Voer dan als host aspmx.l.google.com in, als poort 25 en gebruik TLS. Voer vervolgens niet je gebruikersnaam of wachtwoord in. Vul je GMail-adres hierboven in als ontvanger

**Comment by jeroenpeters1986** [comment]
Ah okay. Ik kreeg daarmee een foutmelding (niet dezelfde als jij).

Ik gebruik nu als host `smtp.gmail.com`, met poort `587` en met mijn eigen username en wachtwoord van het (speciaal voor dit soort systemen gemaakte) e-mailaccount.

**Comment by style2k** [comment]
die settings werken wel idd ff een app wachtwoord aangemaakt bij google die ingevuld en die test komt ook goed door . dus de backup ook weer aangezet . 
er zijn nog steeds onverwerkte telegrams maar de aantallen lopen nog steeds naar beneden straks nog is kijken of dat het uiteindelijk weer oplost dan :)

**Comment by style2k** [comment]
de errors zijn weg nu . dus het probleem was idd de email instelling.
