### ISSUE TITLE
Aantal metingen per minuut aanpassen?

### ISSUE THREAD

**Issue by bikeymouse** [dennissiemensma/dsmr-reader#729]
*l *Bedankt** voor het aanmaken van een issue!*
### Wat gebruik je?
* DSMR-reader versie *(rechtsbovenin applicatie zichtbaar)*: v2.5
* Hardware *(RaspberryPi 3, 4 of iets anders)*: RaspberryPi 2
* DSMR-protocol slimme meter *(v2, v4 of v5)*: v.4/5

### Overige
Ik weet niet wat er precies is veranderd maar sinds ik de applicatie van 2.3 naar 2.5 heb ge-update (via de [xirixiz docker-versie](https://github.com/xirixiz/dsmr-reader-docker))lijkt het erop dat ik veel meer metingen per minuut in de database krijg. Ik lees deze uit via Grafana en zie nu een meting per seconde, terwijl dat eerst per minuut was. Is daar iets veranderd, of heb ik per-ongeluk een parameter aangepast?
Ik heb geëxperimenteerd met de "Groepering" in de Verbruiksconfiguratie, maar dat heeft (zoals beschreven) alleen impact op de weergave, niet op het aantal daadwerkelijke metingen.
Verder heb ik de variabele DSMRREADER_DATALOGGER_SLEEP op 60 seconden staan en DSMRREADER_BACKEND_SLEEP op 120 seconden.
P.s. na experimenteren lijkt het dat het wellicht aan de Docker-image ligt, zie ook melding daar.

**Comment by dennissiemensma** [comment]
Mochten jullie het niet kunnen oplossen in de docker image, dan hoor ik het graag alsnog. :]
