### ISSUE TITLE
DSMR Reader stop na x tijd met meten

### ISSUE THREAD

**Issue by eterpstra** [dennissiemensma/dsmr-reader#732]
Hoi Dennis,

Ik heb sinds een paar dagen DSMR reader op een ODroid N2 boardje geinstalleerd.

Het probleem is dat DSMR reader soms geen verbinding meer heeft met de slimme meter. Ik zie dan zie ik in het dashboard ''laatste meting 1 uur gelden of ''laatste meting 22 min geleden''

Als ik vervolgens supervisor services herstart ( sudo supervisorctl restart all
)  dan werkt het weer.  Een bepaalde periode van tijden dat het niet werkt  is er niet echt.

Heb je enig idee wat dit kan zijn? EN waar zou ik eventueel de logs kunnen vinden?

Gr,
Elroy

**Comment by dennissiemensma** [comment]
Je kunt sowieso deze logfiles bekijken: https://dsmr-reader.readthedocs.io/nl/latest/troubleshooting.html

Ik zou beginnen bij de datalogger.

**Comment by dennissiemensma** [comment]
@eterpstra ben je nog wat wijzer geworden?

**Comment by eterpstra** [comment]
Ik moet nog even afwachten of het is gelukt.. het script voor dataloggers stopte elke keer.. dus heb nu een aanpassing gedaan om te zien of dat werkt.

Ik laat het je einde week weten.

**Comment by dennissiemensma** [comment]
@eterpstra werkt het nu wel?

**Comment by dennissiemensma** [comment]
Mocht ik je alsnog verder kunnen helpen en hoor ik het graag!
