### ISSUE TITLE
Dubbele voorloopnul in MQTT-waarde

### ISSUE THREAD

**Issue by megapearl** [dennissiemensma/dsmr-reader#733]
### Wat gebruik je?
* DSMR-reader versie: `v2.6`
* Hardware: `Ubuntu Linux`
* DSMR-protocol slimme meter: `v5`

### Overige

Hoi Dennis,

Dit is meer een vraag dan een probleem, is het mogelijk om via MQTT de waardes in Watt's door te geven ipv Kilowatts? Nu zie ik bv bij teruglevering dat er een waarde staat van '00.155' kW ik zou hier graag 155 W willen zien, of waarom is er een leading "00." en kan die verwijderd worden?

Nu kan ik in de homeassistant (domotica software) een nieuwe sensor maken op basis van de mqtt sensor die het door 1000 deelt, maar misschien is het bij de bron ook aan te passen in dsmr-reader wat misschien wat makkelijker is.

Ik heb de sensor nu zo opgebouwd dat de 00. eraf wordt gestript, dit werkt natuurlijk maar is niet de mooiste oplossing.

```
  - platform: mqtt
    name: "Power Consumption"
    state_topic: "dsmr/reading/electricity_currently_delivered"
    unit_of_measurement: "W"
    value_template: "{{ (value.lstrip('00.') | int) }}"
  - platform: mqtt
    name: "Power Production"
    state_topic: "dsmr/reading/electricity_currently_returned"
    unit_of_measurement: "W"
    value_template: "{{ (value.lstrip('00.') | int) }}"
```
Groetjes,
Donald.

**Comment by dennissiemensma** [comment]
Bedankt voor je melding. 

* Wat betreft het omzetten naar Watt: Als ik het project opnieuw zou doen zou ik alles in Watt doen. Ik heb echter ooit gekozen voor kWh omdat de slimme meter dat ook zo teruggeeft en ik kan dat helaas niet meer achteraf wijzigen. Andere gebruikers lossen het volgens mij ook op door het in de sensor-template zelf te vermenigvuldigen met 1000, dus ik dat dat de manier is om het te fixen.

* Wat betreft de dubbele voorloopnul. Dat is een bug en zeker niet de bedoeling. Ik heb inmiddels de oorzaak gevonden en de fix gaat mee in de volgende release.
