### ISSUE TITLE
Feature Request: Temperatuur bij vergelijkingen

### ISSUE THREAD

**Issue by dataegg** [dennissiemensma/dsmr-reader#738]
* v2.4
* ESX 6.5, debian 10
* DSMR-protocol slimme meter v5

Kan bij de vergelijking ook de gemiddelde temperatuur zichtbaar worden gemaakt per periode. Met deze informatie is het makkelijker om stook kosten (gas) te vergelijken.

**Comment by dataegg** [comment]
Nog een aanvulling. Een totaal van Elektriciteit (dal + piek) zou ook handig zijn in het vergelijkingsoverzicht

**Comment by dennissiemensma** [comment]
Bedankt voor je verzoek. Ik zal het overwegen.

Betreffende je aanvulling, je kunt er ook voor kiezen om de tarieven in de applicatie te laten samenvoegen. Dat is een optie in de admin bij de frontend/weergave instellingen.

**Comment by dataegg** [comment]
Dank de reactie en tip.

**Comment by dimitrizetzsche** [comment]
+1

**Comment by dennissiemensma** [comment]
Ik heb het opnieuw overwogen, maar ik denk dat je in dat geval beter kunt kijken naar MinderGas.nl. 

Daar wordt ook gerekend met [graaddagen](https://mindergas.nl/degree_days_calculation/explanation) dus je kunt kijken of je daar de informatie heen kunt sturen (kan automatisch) of een paar meterstanden handmatig invullen. Vooral omdat temperatuur alleen niet voldoende zegt over het gasverbruik.
