### ISSUE TITLE
Update issue (1.28)

### ISSUE THREAD

**Issue by djvanas** [dennissiemensma/dsmr-reader#740]
*Bedankt voor het aanmaken van een issue!*
### Wat gebruik je?
* DSMR v1.28
* Pi3
* DSMR-protocol slimme meter  v4

Na sudo su - dsmr, ./deploy.sh en bevstigen van update gebeurt er van alles maar uiteindelijk is versie 1.28 were deployed. Zie screenshot

![image](https://user-images.githubusercontent.com/56652120/66947867-eff0d380-f053-11e9-89ec-bd34739142e1.png)

**Comment by djvanas** [comment]
> Wat krijg je als je dit doet:
> 
> ```
> sudo su - dsmr
> git branch
> ```

![image](https://user-images.githubusercontent.com/56652120/66957677-f3da2100-f066-11e9-8f93-09a189372a5a.png)

**Comment by dennissiemensma** [comment]
Je zou dan dit kunnen proberen:
```
sudo su - dsmr
git fetch
git pull
./post-deploy.sh
```

**Comment by djvanas** [comment]
Dan krijg ik dit met resultaat dat 1.28 gedeployed blijft;

![image](https://user-images.githubusercontent.com/56652120/66981479-26f6d180-f0b4-11e9-927f-6570f51cf046.png)

**Comment by dennissiemensma** [comment]
Ik denk dat het belangrijk is dat je eventuele fouten ook doorgeeft. Op de rand van je screenshot zie ik nog net bovenin een foutmelding staan. Er lijken lokaal wijzigingen gedaan in de code die onder versiebeheer staat. 

Ik weet niet wat je hebt aangepast en of dat bewust is geweest, maar je zult dat ongedaan moeten maken:

```
sudo su - dsmr
git reset --hard
./deploy.sh
```

**Comment by dennissiemensma** [comment]
Mocht je nog meer hulp nodig hebben, dan hoor ik het graag.

**Comment by djvanas** [comment]
Tnx - fixed
