### ISSUE TITLE
Feature Request: Opgewekte stroom via SMA uitlezen

### ISSUE THREAD

**Issue by floyson-reference** [dennissiemensma/dsmr-reader#744]
*Bedankt voor het aanmaken van een issue!*
### Wat gebruik je?
* DSMR-reader versie *(rechtsbovenin applicatie zichtbaar)*: `v2.2.3`
* Hardware *(RaspberryPi 3, 4 of iets anders)*: `RaspberryPi 3B+`
* DSMR-protocol slimme meter v5

Bestaat er een mogelijkheid om via DSMR ook je SMA omvormer (Sunny Boy) uit te lezen?
Dit lijkt me handig om zo te kunnen achterhalen wat je effectief verbruikt en wat je werkelijk opwekt.

**Comment by dennissiemensma** [comment]
Bedankt voor je vraag! Je wens is begrijpelijk, echter beperkt dit project zich tot DSMR en het uitlezen van de slimme meter. Je kunt de gegevens uit DSMR-reader wel op allerlei manieren exporteren naar andere systemen of partijen, zoals PVOutput.
