### ISSUE TITLE
Opbrengst niet verzonden naar PVoutput.org

### ISSUE THREAD

**Issue by Erik050572** [dennissiemensma/dsmr-reader#751]
*Bedankt voor het aanmaken van een issue!*
### Wat gebruik je?
* DSMR-reader versie *(rechtsbovenin applicatie zichtbaar)*: `v2.7`
* Hardware *(RaspberryPi 3, 4 of iets anders)*: `RaspberryPi 3`
* DSMR-protocol slimme meter *(v2, v4 of v5)*: `v.5`

Goedenavond Dennis,

Als ik kijk naar de dashboard, had ik vandaag opbrengst gehad van mijn panelen.
Echter deze opbrengst is niet terug te vinden op PVoutput.org.
Daar is het een vlakke lijn op 0 Watt

Ik heb dit bij zowel mijn installatie gezien (met een 1 fase omvormer) als bij een 3 fase omvormer.

Moet ik ergens een vink weghalen of is dit een fout in het programma?
Ik hoor het graag van je.
Mvg,
Erik

**Comment by dennissiemensma** [comment]
DSMR-reader stuurt alleen verbruik naar PVOutput en geen opbrengst. 

De gedachte daarachter is dat je omvormer (meestal) zelf de opbrengst naar PVOutput uploadt. Die opbrengst is namelijk bruto, zonder dat het in je huishouden opgenomen is. De slimme meter ziet namelijk alleen wat je teruglevert en dus niet wat je opgewerkt hebt.

Meer achtergrondinformatie over de integratie kun je vinden in issue nummer #9.
