### ISSUE TITLE
Uitzetten DSMR en DSMR remote telegrams?

### ISSUE THREAD

**Issue by Muit1980** [dennissiemensma/dsmr-reader#753]
Ik heb DSMR in een docker draaen en DSMR remote datalogger in een docker op de Pi.

Ik heb net DSMR reader even uitgezet (15 min) ivm server reset.

Mis ik dan telegrams als de reader weer aan staat? Worden die bv in een que gezet in de DSMR remote datareader? OF ben ik data kwijt? zo niet hoe lang ik de DSMR uitzetten zonder dataverlies?

**Comment by dennissiemensma** [comment]
Bedankt voor je vraag. De datalogger bewaart lokaal geen data. De data ben je dan kwijt.

Je kunt de applicatie rustig een uur of wat uitzetten. Je krijgt dan alleen een klein gat in de uurstatistieken, maar de dagtotalen zouden nog steeds moeten kloppen.

Mocht je meer informatie nodig hebben dan hoor ik het graag.
