### ISSUE TITLE
Buienradar API bron/foutafhandeling verbeteren

### ISSUE THREAD

**Issue by mrvanes** [dennissiemensma/dsmr-reader#755]
### Wat gebruik je?
* kersverse DSMR pull

Sinds gisteravond 17.00 triggert de Track weather plugin ~1000 api.buienradar.nl DNS requests per 10 minuten, wat opviel in m'n Pi-hole dashboard. Disablen van de Track Weather plugin stopt de requests.
![image](https://user-images.githubusercontent.com/1901782/67472282-29779f00-f651-11e9-98e1-1cd7d93d303d.png)

**Comment by tiki1980** [comment]
Ik heb dit ook gezien idd, per seconde ongeveer één uitvraag.

![image](https://user-images.githubusercontent.com/5437362/67489134-5045cd80-f671-11e9-83f7-3ab69dd7621b.png)

**Comment by mrvanes** [comment]
Het lijkt erop dat het API request mislukt, maar dat de plugin nogal agressief door blijft vragen. Dat heb ik verder niet onderzocht.

**Comment by vincedh** [comment]
Hier hetzelfde probleem inderdaad... Voorlopig de module maar uitgezet.

**Comment by dennissiemensma** [comment]
Bedankt voor jullie melding. Ik zie hier nu hetzelfde: ` Failed to read Buienradar API `.

Het is uiteraard niet de bedoeling dat die het zovaak opnieuw probeert. Zoiets was al eerder gemeld in #399 en ik dacht dat ik er toen ook iets aan had gedaan. Ik onderzoek eerst even de oorzaak.

**Comment by dennissiemensma** [comment]
De API zelf lijkt kapot of veranderd: https://api.buienradar.nl/

Er komt wel een HTTP 200 OK terug, maar geen inhoud. Ik weet niet of er een sotring is, of dat RTL de API de nek om heeft gedraaid.

**Comment by dennissiemensma** [comment]
Ik zie in https://www.buienradar.nl/overbuienradar/gratis-weerdata geen melding van wijzigingen, maar wel een referentie naar https://data.buienradar.nl/2.0/feed/json met soortgelijke gegevens.

Wellicht is dat een oplossing.

**Comment by dennissiemensma** [comment]
Ik ben er ook achter waarom DSMR-reader het elke seconde opnieuw probeert.

Er zie [een check in](https://github.com/dennissiemensma/dsmr-reader/blob/v2.8.0/dsmr_weather/services.py#L48) om bij onbereikbare API 5 minuten te wachten. Hetzelfde [geldt voor onjuiste data](https://github.com/dennissiemensma/dsmr-reader/blob/v2.8.0/dsmr_weather/services.py#L74). Helaas klapt die er uit op een derde scenario: geen data. Dus ik zal het herschrijven naar een nog betere check.

**Comment by dennissiemensma** [comment]
Ik heb zowel de foutafhandeling verbeterd als de nieuwe API van buienradar ingebouwd. Gaat mee met volgende release.

**Comment by dennissiemensma** [comment]
Even dit issue pinnen zodat helder is dat het opgelost wordt.

**Comment by dennissiemensma** [comment]
Uitgebracht in [v2.9.0](https://github.com/dennissiemensma/dsmr-reader/releases/tag/v2.9.0).
