### ISSUE TITLE
Buienradar API error

### ISSUE THREAD

**Issue by PascalBu** [dennissiemensma/dsmr-reader#758]
DSMR reader 2.8
Raspberry Pi 3B

Sinds vandaag error bij verbinden met Buienradar API, probeert veel connecties te maken (te zien in PiHole) maar haalt geen buitentemperatuur op.

Sinds upgrade naar 2.8 gister begonnen?

**Comment by dennissiemensma** [comment]
Bedankt voor je melding. Er is iets veranderd in de API van buienradar. Het is opgelost in #755 voor de volgende release. Waarschijnlijk morgen.

**Comment by PascalBu** [comment]
Ok top!

Op do 24 okt. 2019 22:45 schreef Dennis Siemensma <notifications@github.com
