### ISSUE TITLE
Database-fouten in dsmr_backend.log

### ISSUE THREAD

**Issue by dajappie** [dennissiemensma/dsmr-reader#759]
### Wat gebruik je?
* DSMR-reader versie *(rechtsbovenin applicatie zichtbaar)*: `v2.8`
* Hardware *(RaspberryPi 3, 4 of iets anders)*: `RaspberryPi .3b`
* DSMR-protocol slimme meter *(v2, v4 of v5)*: `v4`

### Bij fouten
Aangezien de weer-integratie geen gegevens meer liet zien gaan kijken in de logs. De dsmr_backendlog stond vol met fouten zoals deze:

```
pg_dump: [archiver (db)] query failed: ERROR:  permission denied for relation kdual
pg_dump: [archiver (db)] query was: LOCK TABLE public.kdual IN ACCESS SHARE MODE
[2019-10-22 07:05:49,236] ERROR    'NoneType' object has no attribute 'read'
NoneType: None
```

In PSQL de permissies een beetje ruimer gezet voor dsmrreader:

```
GRANT USAGE ON SCHEMA public TO dsmr;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO dsmr;
```

Daarna geen problemen meer met KDUAL, maar wel met andere queries:

```
pg_dump: [archiver (db)] query failed: ERROR:  permission denied for relation agentschedule_schedid_seq
pg_dump: [archiver (db)] query was: SELECT sequence_name, start_value, increment_by, CASE WHEN increment_by > 0 AND max_value = 9223372036854775807 THEN NULL      WHEN increment_by < 0 AND max_value = -1 THEN NULL      ELSE max_value END AS max_value, CASE WHEN increment_by > 0 AND min_value = 1 THEN NULL      WHEN increment_by < 0 AND min_value = -9223372036854775807 THEN NULL      ELSE min_value END AS min_value, cache_value, is_cycled FROM public.agentschedule_schedid_seq
[2019-10-25 09:51:15,106] ERROR    'NoneType' object has no attribute 'read'
NoneType: None
[2019-10-25 09:51:15,107] ERROR    no element found: line 1, column 0
NoneType: None
```

Dus botte bijl en alle permissies gegeven:

```
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO dsmrreader;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO dsmrreader;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO dsmrreader;
```

Nu geen permissiefouten meer, maar nog wel elke seconde:

```
[2019-10-25 10:13:17,005] ERROR    no element found: line 1, column 0
NoneType: None
[2019-10-25 10:13:18,346] ERROR    no element found: line 1, column 0
NoneType: None
[2019-10-25 10:13:19,687] ERROR    no element found: line 1, column 0
NoneType: None
[2019-10-25 10:13:20,951] ERROR    no element found: line 1, column 0
NoneType: None
[2019-10-25 10:13:22,285] ERROR    no element found: line 1, column 0
NoneType: None
[2019-10-25 10:13:23,574] ERROR    no element found: line 1, column 0
NoneType: None
```

Enig idee? Alle reguliere functionaliteit mbt opslaan van inkomende metingen werken prima.

**Comment by dennissiemensma** [comment]
Bedankt voor je melding. Welke versie van Postgresql draai je?

**Comment by dennissiemensma** [comment]
Ik herken nu pas de fouten. Het komt door Buienradar die de API gewijzigd heeft. Kun je eens updaten naar v2.9 en kijken of het nog voor komt?

**Comment by dajappie** [comment]
Net geüpgraded naar 2.9 en de fout lijkt opgelost, vooralsnog geen nieuwe log errors.  Kwam de database issue overigens ook voort uit Buienradar? Btw Postgres v9.6.13

**Comment by dennissiemensma** [comment]
Bedankt voor je terugkoppeling.

De postgres-fout staat er los van en heb ik geen verklaring voor. In principe zouden rechtenissues niet voor moeten komen als de database met dezelfde user wordt aangemaakt als in de applicatie. Maar fijn dat je het hebt kunnen oplossen.
