### ISSUE TITLE
Fibaro Home Center 2 integratie

### ISSUE THREAD

**Issue by Erik050572** [dennissiemensma/dsmr-reader#768]
Goedemiddag Dennis,

Wederom bedankt voor al het werk dat je in dit project steekt.
Naar aanleiding van jouw opmerking ( [https://github.com/dennissiemensma/dsmr-reader/issues/761#issuecomment-547588097](url) ), post ik hier het verzoek voor een nieuw feature:
De integratie in een Fibaro Home Center 2.

Het probleem tenopzichte van #761 is dat de Fibaro niet luistert naar MQTT berichten 

Alvast bedankt
MVG,
Erik

**Comment by dennissiemensma** [comment]
Bedankt voor je verzoek. Ik kijk hier op termijn naar en ik kan vanzelfsprekend niets beloven.

**Comment by dennissiemensma** [comment]
Ik heb hier nog even naar gekeken, maar ik zie geen praktische mogelijkheid om dit te ontwikkelen of integeren. 

Ik denk dat je dit het beste kunt beleggen in de community van Fibaro zelf. Mijn rol is dan beperkt tot ondersteuning voor de API of MQTT, voor zover dat nodig is.
