### ISSUE TITLE
Dashboard: energiekost elektriciteit fout berekend?

### ISSUE THREAD

**Issue by dimitrizetzsche** [dennissiemensma/dsmr-reader#771]
**Wat gebruik je?**
* DSMR-reader versie *(rechtsbovenin applicatie zichtbaar)*: `v2.9`
* Hardware *(RaspberryPi 3, 4 of iets anders)*: `RaspberryPi 2`
* DSMR-protocol slimme meter *(v4 of v5)*: `v5`

Het ziet er naar uit dat de energiekost voor elektriciteit op het dashboard fout wordt berekend:
<img width="882" alt="Schermafbeelding 2019-10-31 om 17 38 48" src="https://user-images.githubusercontent.com/3658214/67967158-5efa2a80-fc05-11e9-9929-69d04f0f7137.png">

Volgend energiecontract is actief — hier zijn de totalen wel OK:
<img width="882" alt="Schermafbeelding 2019-10-31 om 17 39 58" src="https://user-images.githubusercontent.com/3658214/67967206-7df8bc80-fc05-11e9-8586-557e02db4d44.png">

Op het dashboard zou de prijs van mijn elektriciteit 4,15*0,7776€=3,23€ moeten zijn. De gas is OK: 11,38*0,02847=0,32€

**Comment by dennissiemensma** [comment]
Bedankt voor je melding.

Ik zie dat je een enkel tarief gebruikt. Voor de zekerheid: Je hebt dezelfde prijs ingevuld voor hoog- als laagtarief he?

**Comment by dennissiemensma** [comment]
Nevermind, ik zie nu pas je tweede screenshot. De meeste recente wijziging m.b.t. prijzen zijn afrondingen, maar dat zou hooguit een cent verschil moeten maken. Ik zal kijken of ik het kan reproduceren.

**Comment by dennissiemensma** [comment]
Bij nader inzien, volgens mij klopt de prijs, maar wellicht hebben we een andere kijk op dezelfde gegevens? De ingevoerde prijs is 7 cent en niet 77 cent. Zit daar een afwijking in?

Ik kom ook uit op 32 cent:
![Selection_001](https://user-images.githubusercontent.com/16581744/67974844-645e7180-fc13-11e9-8e11-8399df44315a.png)

Teruglevering van stroom wordt overigens momenteel niet verrekend in de prijs.

**Comment by dimitrizetzsche** [comment]
Je hebt gelijk. Ik heb om een of andere reden (meerdere keren) verkeerd gerekend :-). Toevallig zijn bij vermenigvuldigingen hetzelfde :-).

No issue dus.
--

**Comment by dennissiemensma** [comment]
Kan gebeuren, bedankt voor je terugkoppeling.
