### ISSUE TITLE
Backups lopen niet meer

### ISSUE THREAD

**Issue by floyson-reference** [dennissiemensma/dsmr-reader#773]
Hallo,
Ik heb deze week geupgrade naar v2.9, maar mijn backups lijken niet meer te lopen. Is er ergens logging die ik kan checken of bepaalde stappen die ik kan controleren?

Ik gebruik raspbian (raspberry pi 3B+)
PS: ik ben geen echte Linux kenner...

**Comment by floyson-reference** [comment]
Ok never mind, in /var/log/supervisor vond ik een log waarin stond dat er blijkbaar onvoldoende rechten waren op de map /home/dsmr/dsmr-reader/backups.
Daarna ook nog te weinig diskspace...
Na toekennen van rechten en opkuisen van files werkt alles terug :-)

**Comment by dennissiemensma** [comment]
Fijn dat je het zo snel zelf hebt kunnen vinden!
