### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by hjkoster400d** [dennissiemensma/dsmr-reader#779]
Sinds een tijdje geeft de Raspberry Pi 3 een 502 error.
Afgelopen week heb ik de update gedaan naar de laatste versie (probleem was daarvoor ook al wel).

Raspberry leek wel te kampen met een power issue, maar dat is nu met een nieuwe adapter opgelost.

./manage.py levert het onderstaande resultaat op:
<img width="1044" alt="Schermafbeelding 2019-11-09 om 09 04 15" src="https://user-images.githubusercontent.com/7768158/68525284-532afa00-02d0-11ea-9488-9456d90a599d.png">

Er staat wel dat er email settings missen, maar die hebben er nooit ingestaan.... Enig idee wat het zou kunnen zijn?

Alvast bedankt.

M.v.g.
Rik Koster

**Comment by dennissiemensma** [comment]
Bedankt voor je melding. Het is een stuk code genaamd EmailSettings die er mist, niet de instellingen zelf, want die zijn optioneel.

Vermoedelijk is er iets met de installatie, want het pad klopt verder wel. Kun je eens dit proberen:
```
sudo su - dsmr
git reset --hard
./post-deploy.sh
```

**Comment by dennissiemensma** [comment]
En als dat niet werkt, kun je dit nog proberen, de interne cache van Python-bestanden weggooien:

```
sudo su - dsmr
find . -type f -iname '*.pyc' -delete
./reload.sh
```

**Comment by hjkoster400d** [comment]
Heey Dennis,

Allereerst; Heel erg bedankt voor je snelle hulp!

Beide oplossingen heb ik geprobeerd (weliswaar is de omgekeerde volgorde, dus eerst je laatste oplossing en daarna de eerste).

Nu is de 502 weg, maar geeft de webpagina een Internal Server Error.

Hieronder de laatste regels van de console na het uitvoeren van de ./reload.sh

<img width="655" alt="Schermafbeelding 2019-11-09 om 13 12 11" src="https://user-images.githubusercontent.com/7768158/68528420-ba59a600-02f2-11ea-8058-6bc422e52a10.png">

Alvast bedankt (nogmaals).
M.v.g.
Rik

**Comment by hjkoster400d** [comment]
Aanvullend de dsmr.log file geeft deze melding, wellicht dat dat er iets mee te maken heeft?

<img width="888" alt="Schermafbeelding 2019-11-09 om 14 02 29" src="https://user-images.githubusercontent.com/7768158/68528971-b2513480-02f9-11ea-9fd9-4b0580ee4718.png">

**Comment by dennissiemensma** [comment]
Ik denk dat er meerdere dingen aan de hand zijn. Je kunt het beste nog eens updaten en dan alles herstarten.

```
sudo su - dsmr
./deploy.sh
CTRL+D

sudo supervisorctl restart all
```

Dat lost het niet van de telegrammen op, maar het is een begin. Die logs zijn ook van 2 november, dus dat is al een tijdje terug.

**Comment by hjkoster400d** [comment]
Top! 
Ik ga het even proberen en laat het z.s.m. weten.

Bedankt voor de geweldig goede service trouwens.

**Comment by hjkoster400d** [comment]
Zojuist even deploy opnieuw gedaan en alles gerestart. De processen leken allemaal netjes op te starten maar een aantal blijven herstarten.... Webserver draait wel op poort 81, dat zal het probleem toch niet zijn lijkt mij?

<img width="487" alt="Schermafbeelding 2019-11-09 om 14 19 20" src="https://user-images.githubusercontent.com/7768158/68529153-f0e7ee80-02fb-11ea-8fe1-30238767328f.png">


<img width="1037" alt="Schermafbeelding 2019-11-09 om 14 15 46" src="https://user-images.githubusercontent.com/7768158/68529128-77e89700-02fb-11ea-829d-7b47ac925faa.png">

**Comment by dennissiemensma** [comment]
Er mist software, maar een deploy zou dat automatisch moeten installeren. Je kunt het handmatig proberen:

```
sudo su - dsmr
pip3 install -r dsmrreader/provisioning/requirements/base.txt
CTRL+D

sudo supervisorctl restart all
```

**Comment by hjkoster400d** [comment]
Alle software is 'satisfied' zegt ie, dus alles lijkt geïnstalleerd te zijn. Op de zelfde Raspberry staat ook de homeassistant installatie, kan dat elkaar wellicht in de weg zitten?

**Comment by dennissiemensma** [comment]
Dat zou niet uit mogen maken. Wat krijg je hier te zien:

```
sudo su - dsmr
pip freeze | grep PyCRC
```

**Comment by hjkoster400d** [comment]
<img width="509" alt="Schermafbeelding 2019-11-09 om 15 23 49" src="https://user-images.githubusercontent.com/7768158/68530049-f1d14e00-0304-11ea-8c32-886f7f85691c.png">

**Comment by dennissiemensma** [comment]
En krijg je hier een fout op?

```
sudo su - dsmr
python3

from PyCRC.CRC16 import CRC16
```

Bijvoorbeeld `ImportError: cannot import name 'CRC16'`.

**Comment by dennissiemensma** [comment]
En hier krijg je dus sowieso een fout op?
```
sudo su - dsmr
./manage.py dsmr_frontend_clear_cache
```

**Comment by hjkoster400d** [comment]
Klopt inderdaad, beiden geven de CRC16 import error.

**Comment by hjkoster400d** [comment]
Kan dit een oplossingsrichting zijn?

https://www.google.com/url?sa=t&source=web&rct=j&url=https://stackoverflow.com/a/37228009&ved=2ahUKEwiZ0tG8-d3lAhUSa1AKHWptAUcQ4-4CMAB6BAgFEAg&usg=AOvVaw2mEJEFqqwL0-t2GjN_rfwH&cshid=1573330757442

**Comment by dennissiemensma** [comment]
In principe gaat alles via Python3 en pip3, dus ik verwacht daar geen issues. Ik heb geen idee wat de oorzaak is, want aan de ene kant geeft pip aan dat de package geinstalleerd is en aan de andere kant geeft Python aan dat die de package niet kent. 

Wat je nog kunt doen is de virtualenv met alle packages verwijderen en opnieuw installeren.
```
sudo supervisorctl stop all

sudo su - dsmr
deactivate
rm -rf /home/dsmr/.virtualenvs
mkdir /home/dsmr/.virtualenvs
virtualenv /home/dsmr/.virtualenvs/dsmrreader --no-site-packages --python python3
pip3 install -r /home/dsmr/dsmr-reader/dsmrreader/provisioning/requirements/base.txt
pip3 install -r /home/dsmr/dsmr-reader/dsmrreader/provisioning/requirements/postgresql.txt

CTRL+D
sudo su - dsmr
# Als het goed is kreeg je geen fout bij het vorige command.

# Kijk of je nog steeds fouten krijgt:
./manage.py dsmr_frontend_clear_cache

# Zo nee, alles starten
CTRL+D

sudo supervisorctl stop all
```

**Comment by hjkoster400d** [comment]
Heb de stappen uitgevoerd, maar hij geeft nu de volgende melding

<img width="588" alt="Schermafbeelding 2019-11-12 om 20 29 25" src="https://user-images.githubusercontent.com/7768158/68703634-51408f80-058b-11ea-8296-49d88e49d3a4.png">

Enig idee?

**Comment by jeroenpeters1986** [comment]
Heb je het volledig uitgevoerd zoals Dennis het aangaf? 
Je zou verwachten dat Django goed geinstalleerd moet zijn, heb je nog meldingen gekregen toen je de `pip3 install -r ...` commando's uitvoerde?

Zo niet, wil je dan eens kijken wat `pip3 freeze` voor je aangeeft?

**Comment by hjkoster400d** [comment]
Ja heb de stappen exact opgevolgd, en zojuist voor de zekerheid nogmaals gedaan maar krijg dezelfde foutmelding. 
De pip -r commando's geven aan dat de packages uit de cache worden gebruikt, verder geen bijzondere meldingen. 

Het pip3 freeze command geeft deze melding:
<img width="596" alt="Schermafbeelding 2019-11-12 om 21 13 40" src="https://user-images.githubusercontent.com/7768158/68707057-50aaf780-0591-11ea-86f7-50a96a05cd71.png">

Nogmaals erg bedankt voor de hulp die jullie bieden, dat waardeer ik enorm!

**Comment by jeroenpeters1986** [comment]
Ik weet niet of ik dan wat kan toevoegen nog. Als je geen foutmeldingen krijgt en alles geinstalleerd lijkt te worden, dan is het heel erg raar dat je met `pip3 freeze` geen packages te zien krijgt.

Toch nog voor de zekerheid, je hebt er geen `sudo` voor de commando's met `pip3 install -r`, en je weet ook zeker dat je `pip3` gedaan hebt ipv `pip`?

**Comment by dennissiemensma** [comment]
Ik zie dat ik nog 1 command was vergeten. Na het aanmaken van de virtualenv moet die nog geactiveerd worden. Kun je dit proberen:

```
sudo su - dsmr
source /home/dsmr/.virtualenvs/dsmrreader/bin/activate

pip3 install -r /home/dsmr/dsmr-reader/dsmrreader/provisioning/requirements/base.txt
pip3 install -r /home/dsmr/dsmr-reader/dsmrreader/provisioning/requirements/postgresql.txt

# Controleer nu of pip3 freeze meer teruggeeft.
pip3 freeze

CTRL+D
sudo su - dsmr
# Als het goed is kreeg je geen fout bij het vorige command.

# Kijk of je nog steeds fouten krijgt:
./manage.py dsmr_frontend_clear_cache

# Zo nee, alles starten
CTRL+D

sudo supervisorctl start all
```

**Comment by hjkoster400d** [comment]
Helemaal top! De activatie was inderdaad nodig. freeze gaf netjes een hele lijst terug en clear_cache gaf geen fouten meer. Reader loopt weer! 

Heel erg bedankt Dennis en Jeroen!

**Comment by hjkoster400d** [comment]
Dag,

Wat mij opviel was dat na deze actie de grafieken op de hoofdpagina niet meer werken en de datum verkeerd staat. 
Daarnaast geeft de Status pagina een Server Error:

<img width="733" alt="Schermafbeelding 2019-11-13 om 15 05 20" src="https://user-images.githubusercontent.com/7768158/68770743-05432880-0627-11ea-9969-44017138beda.png">

Actuele verbruik e.d. werken prima. Archief lijkt ook te werken, behalve dat deze denkt dat het 7 nonvember is...

**Comment by hjkoster400d** [comment]
Heb zojuist ./manage gestart en heeft 2.11.1 geïnstalleerd. Nadien werkte alles weer naar behoren.
Hij heeft nog wel 55000+ telegrammen die niet verwerkt zijn.... Dat verwerkingsprocess heeft natuurlijk een tijdje uit gestaan. Worden die met terugwerkende kracht nog verwerkt trouwens?

Nogmaals bedankt!

**Comment by dennissiemensma** [comment]
Je kunt het beste de meest recente versie installeren met `./deploy.sh`. Die voert eventuele database migraties ook uit.

Als alle processen verder draaien, haalt die vanzelf de achterstand in.

**Comment by hjkoster400d** [comment]
Ik bedoelde inderdaad ./deploy. Draait weer als een zonnetje hoor! Achterstand is intussen weggewerkt! Bedankt voor je hulp
