### ISSUE TITLE
PVoutput download data and new graph feature request

### ISSUE THREAD

**Issue by sanderplug** [dennissiemensma/dsmr-reader#785]
Hi, I was hoping that there would be a possibility to download PVoutput data and to import this into dsmr reader. This way it would be possible to overlap the generation data from the solar panels with the usage / return data.

This would allow for a possibility to calculate the total usage of the house, something like:
total usage kWh = usage from the net + solar panel generation - delivery to the net

Has this feature been explored? Although generally pvoutput data is only every 5 minutes, it could be a new graph with 5 minute detail level showing this.

**Comment by dennissiemensma** [comment]
Bedankt voor je verzoek. DSMR-reader is hier helaas niet het juiste project voor. Zie oa. #594 voor meer informatie.

Het is overigens wel mogelijk om je (netto) verbruik te uploaden naar PVOutput. Zie daarvoor #9.
