### ISSUE TITLE
Alle meldingen in 1x sluiten

### ISSUE THREAD

**Issue by wouzzie** [dennissiemensma/dsmr-reader#793]
Hoi Dennis,

Allereerst bedankt voor je fantastische project! 

Gisteren heeft door een storing mijn internet er halve dag uitgelegen. Voor DSMR-reader geen probleem natuurlijk, ware het niet dat dit ook betekent dat de buienradar API niet bereikt kon worden. Sinds een paar updates geleden toont dit natuurlijk netjes als notificatie. Dit levert nu bij mij de situatie op dat er een lijst is ontstaan van 25+ notifiticaties die ik handmatig moet accepteren. 

![afbeelding](https://user-images.githubusercontent.com/43322796/70343824-85406500-1858-11ea-9f37-7152c5f40f7c.png)

Zou er een mogelijkheid  zijn om een "accept all" of "dismiss all"-achtige mogelijkheid in te bouwen voor de notificaties? 

Alvast bedankt en keep up the good work!

**Comment by dennissiemensma** [comment]
Bedankt voor je suggestie. Dat lijkt me een goede toevoeging. Ik denk dat ik sowieso alle notificaties verplaats naar een aparte pagina en in het dashboard alleen een melding geeft dat er notificaties zijn. Bulk sluiten is daar dan een nuttige feature.

**Comment by dennissiemensma** [comment]
Voor `v2.14` heb ik de notificaties verplaatst naar een aparte pagina, waar je ze straks ook in bulk kunt sluiten. Screenshots:

![Selection_001](https://user-images.githubusercontent.com/16581744/71785642-37a74b80-3002-11ea-82aa-558603919a23.png)

![Selection_002](https://user-images.githubusercontent.com/16581744/71785643-37a74b80-3002-11ea-8847-079a73e2e9ba.png)

**Comment by dennissiemensma** [comment]
Doorgevoerd in develop branch.
