### ISSUE TITLE
Simplify parallel execution of several dsmrreader instances

### ISSUE THREAD

**Issue by JeanMiK** [dennissiemensma/dsmr-reader#805]
I am soon getting my PV Installation connected, and here in Luxembourg, this means a mandatory second Smarty smartmeter.

I know I could probably just run the dockerized versions twice with different settings, but I wanted to avoid the corresponding overhead.

It is in fact quite easy to run a second instance along the first, it is *almost* enough to just create additional supervisor jobs that either specify environment variables to override the values in dsmrreader/settings.py, or to specify a different Settings file altogether via variable DJANGO_SETTINGS_MODULE, and none of this requires any changes to the source code.

The only thing I could not overcome without source code changes is the handling of the PID files and reload.sh: to have seperate files to handle the stop-restart seperately, I had to modify method _write_pid_file in dsmr_backend/mixins.py to modify the name of the pid file by adding the content of an environment variable DSMRREADER_INSTANCE in a format 'dsmrreader-{}-{}.pid', and then to use the same environment variable in reload.sh

If you would include this or something similar in the regular release, I would no longer need my local changes. If you want, I can make a pull request with my local changes, but they are fairly obvious.

Especially when dealing with multiple instances, it can also be useful to add a 'group' section at the end of the Supervisor configuration file dsmr-reader.conf

```
[group:dsmr]
programs=dsmr_datalogger,dsmr_backend,dsmr_mqtt,dsmr_webinterface
```
That way, it is possible to start / stop all processes of the instance with e.g.
`sudo supervisorctl stop dsmr:*`

**Comment by dennissiemensma** [comment]
Thanks for your input. Even though I understand your situation and it might be possible, I'm not sure whether this is the right solution for the problem. You may still want to try using Docker first, as the overhead shouldn't be that bad on linux anyway.

Supporting these kind of workarounds will cause maintaining the project somewhat harder and there aren't many users benefitting from it. I think that Docker is the best solution for this situation, as many people already use it these days for DSMR-reader.
