### ISSUE TITLE
Meterstatistieken doorgeven via API

### ISSUE THREAD

**Issue by rubenverhoef** [dennissiemensma/dsmr-reader#820]
Ik zou graag naast de standaard parameters alle extra parameters van het DSMR telegram oversturen via de API V2.
Dit zijn de standaard parameters in de API v2:
https://dsmr-reader.readthedocs.io/nl/latest/api.html#id4

Ik zou graag alle parameters waar DSMR-Reader wat mee doet over willen sturen via de V2 API.
(zoals DSMR versie, Tariff indicator, `Number of power failures in any phases`, etc.)

Momenteel is dat alleen mogelijk om het volledige telegram bericht over te sturen (APIV1) en niet als losse parameters zoals APIV2

**Comment by dennissiemensma** [comment]
Bedankt voor je verzoek. Dat lijkt me opzich een prima toevoeging. Het zal wel even duren voordat ik hier aan toekom vermoedelijk.

**Comment by rubenverhoef** [comment]
Oke, ik zie het wel een keer verschijnen bedankt! :)

**Comment by dennissiemensma** [comment]
Ik heb hier nu een opzet voor werkend. 

Alleen zit ik nog even met de API-documentatie. Deze is nog vrij ouderwets, dus ik wil die nog eerst omzetten naar een OpenAPI-variant, met evt Postman. dat scheelt een hoop voorbeelden en eveneens vertalen (ik houd het dan bij Engels).

Tot die tijd kun je denk ik ondertussen eerst upgraden naar DSMR-reader v3.0. Deze feature komt waarschijnlijk in v3.1.

**Comment by dennissiemensma** [comment]
Gemerged naar release-branch, docs via #839.

**Comment by rubenverhoef** [comment]
Bedankt!

Ik zal er eerdaags naar kijken. Klopt het dat ik alles van de [`PATCH`](https://github.com/dennissiemensma/dsmr-reader/blob/90c0d4b00b146b92840eefce137195b532c8ce8f/docs/api.rst#patch---dataloggermeter-statistics) moet gaan implementeren?

**Comment by dennissiemensma** [comment]
Alle parameters zijn optioneel bij de PATCH, zodat je zelf kunt bepalen wat je wel en niet wilt/kan bijwerken.

**Comment by dennissiemensma** [comment]
De release staat voor morgen gepland. Er zit ook een Postman-collectie bij zodat je werkende voorbeelden hebt.
