### ISSUE TITLE
Is het mogelijk om de P1 kabel op de GPIO poorten van de pi aan te sluiten?

### ISSUE THREAD

**Issue by HeyItsMeNobody** [dennissiemensma/dsmr-reader#837]
**Wat gebruik je?**
* DSMR-reader versie *(rechtsbovenin applicatie zichtbaar)*: `v2.14.1`
* Hardware *(RaspberryPi 3, 4 of iets anders)*: `RaspberryPi 3B`
* DSMR-protocol slimme meter *(v4 of v5)*: `v5`

Ik vroeg me af of ik de P1 kabel rechtstreeks op de pi kon aansluiten, Ik heb dit geprobeerd maar krijg geen data binnen. Ik kon dit wel met een esp8266.

**Comment by dennissiemensma** [comment]
Bedankt voor je vraag. Ik denk dat het wel kan, maar ik ben daar zelf niet zo bedreven in. Ik gebruik zelf een kant-en-klare kabel.

Ik kan je echter wel wijzen naar een plek waar je sowieso geholpen kan worden. Probeer je situatie eens op Tweakers te delen: https://gathering.tweakers.net/forum/list_messages/1578510
In dat topic is heel veel kennis aanwezig van specialisten en ook hobbyisten die zelf kabeltjes e.d. maken. 

Zodra je [het kunt uitlezen met `cu`](https://dsmr-reader.readthedocs.io/en/latest/installation/explained.html#your-first-reading-optional) (en het dan nog niet werkt in DSMR-reader), kan ik je verder helpen.
