### ISSUE TITLE
"ModuleNotFoundError: No module named 'django'" bij upgrade naar DSMR-reader v3.x

### ISSUE THREAD

**Issue by raoulteeuwen** [dennissiemensma/dsmr-reader#840]
Gaat er iets fout, maar weet je niet wat? [Bekijk de logfiles](https://dsmr-reader.readthedocs.io/nl/v2/troubleshooting.html) als startpunt.

**Wat gebruik je?**
* DSMR-reader versie *(rechtsbovenin applicatie zichtbaar)*: `v2.xxx (weet ik niet: ben dsmr aan het upgraden)
* Hardware *(RaspberryPi 3, 4 of iets anders)*: `RaspberryPi 4 4GB
* DSMR-protocol slimme meter *(v4 of v5)*: `v...` (weet ik niet)

Ik heb https://dsmr-reader.readthedocs.io/en/v3/faq/v3_upgrade.html gevolgd. Alles ging mi goed, tot de laatste stap. Ik krijg dan:

"
(dsmrreader) dsmr@RPi4:~/dsmr-reader $ ./deploy.sh

 --- You are currently running version: 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/dsmr/dsmr-reader/dsmrreader/__init__.py", line 1, in <module>
    from django.utils.version import get_version
ModuleNotFoundError: No module named 'django'

     [!] FAILED to call Django (did you activate the 'dsmrreader' VirtualEnv before running?)

[!] Halted in pre-deployment: Either user ABORTED or script FAILED

"

**Comment by raoulteeuwen** [comment]
pip3 list levert

(dsmrreader) dsmr@RPi4:~/dsmr-reader $ pip3 list
Package         Version
--------------- -------
pip             19.3.1 
pkg-resources   0.0.0  
psycopg2-binary 2.8.4  
setuptools      45.0.0 
wheel           0.33.6

**Comment by dennissiemensma** [comment]
Wil je eens kijken of dit het oplost:

```
sudo su - dsmr
pip3 install -r dsmrreader/provisioning/requirements/base.txt
```

En dan weer verder gaan met waar je was.

**Comment by raoulteeuwen** [comment]
Yes, nu loopt hij door, dank!

**Comment by dennissiemensma** [comment]
Jij bedankt voor het melden. Kleine check waar ik geen rekening mee gehouden had.

Het is inmiddels aangepast in de documentatie.

**Comment by Djjvb** [comment]
<removed>

**Comment by dennissiemensma** [comment]
@Djjvb je kunt hier het beste even een apart issue voor maken, om te voorkomen dat iedereen die ooit dit topic heeft gevolgd er ook allemaal mail van krijgt.

https://github.com/dennissiemensma/dsmr-reader/issues/new?assignees=&labels=&template=help.md&title=
