### ISSUE TITLE
Gasgrafiek als staafdiagram

### ISSUE THREAD

**Issue by mkruiver** [dennissiemensma/dsmr-reader#842]
DSMR draait nog steeds goed, dank daarvoor!

Ik heb een verzoekje: ik zou graag de gasgrafiek als staafdiagram kunnen weergeven, zodat ik bijvoorbeeld kan zien dat er in een bepaald uur 0.6m3 verbruikt is. De huidige representatie met m3/h op de y-as vind ik erg lastig te lezen.

**Comment by dennissiemensma** [comment]
Ik heb even voor je geprobeerd of het daadwerkelijk verschilt qua weergave en dat is inderdaad zo. Ik zal het in v3.2 standaard aanpassen naar staaf. Als er veel klachten over komen dan maak ik het wel instelbaar.

Voorbeelden:
![Selection_005](https://user-images.githubusercontent.com/16581744/72663475-75897400-39f3-11ea-926e-feb9bfc05505.png)

![Selection_006](https://user-images.githubusercontent.com/16581744/72663476-75897400-39f3-11ea-8bbb-c686623a2b4b.png)

**Comment by dennissiemensma** [comment]
@mkruiver je kunt het trouwens voor jezelf aanpassen.

`/var/www/dsmrreader/static/dsmr_frontend/js/dsmr-reader/dashboard/gas.js` op regel `59`:
```
type: 'line',
```

Naar:
```
type: 'bar',
```

Idem voor `/var/www/dsmrreader/static/dsmr_frontend/js/dsmr-reader/archive/gas.js` op regel `54`.


Bij de eerste volgende deploy die je doet wordt het weer overschreven met de repo standaard.

**Comment by mkruiver** [comment]
Gaaf, dat was snel! Het werkt inderdaad, mooi, bedankt!

Kan ik nog ergens instellen dat ik meer dan 5min per staafje wil zien, bijv 1 staaf per 30 of 60min ipv 5?

![Screenshot_20200118-163111](https://user-images.githubusercontent.com/3832319/72666505-310dd080-3a13-11ea-86a4-d8114b675301.png)

**Comment by dennissiemensma** [comment]
Daarvoor moet eerst iets gemaakt worden dat de metingen kan groeperen. Voor nu is het afhankelijk van of je een v4 of v5 meter hebt.

**Comment by FutureCow** [comment]
Zou het ook mogelijk zijn om in de nieuwe staafdiagram een gedeelte te selecteren, zodat je kunt zien hoeveel er in dat tijdbestek is verbruikt?

**Comment by Mixpower** [comment]
Ik zou het toch erg prettig vinden als ik dit instelbaar is, ik neb namelijk veel liever een line om de hele flow te zien dat is nu niet meer mogelijk en zit ik met een staafdiagram. Heb hem nu handmatig weer aangepast naar line, maar een instelmogelijkheid zo toch wel heel fijn zijn!

**Comment by dennissiemensma** [comment]
@Mixpower bedankt voor je feedback. Dan zal ik daar wat voor maken.

**Comment by dennissiemensma** [comment]
Ik heb er  #860 voor gemaakt

**Comment by dennissiemensma** [comment]
@FutureCow ik denk het niet. Wat je wel kunt doen is het weer terugzetten naar lijn of het gas laten groeperen per uur. Dat kan al iets helpen.

**Comment by mkruiver** [comment]
Waar kun je eigenlijk groeperen per uur? En is dat dan alleen voor de
frontend of ook voor de database?

**Comment by Mixpower** [comment]
> Waar kun je eigenlijk groeperen per uur? En is dat dan alleen voor de frontend of ook voor de database?

Configuratie > Verbruiksconfiguratie > Gasmetingen groeperen

**Comment by dennissiemensma** [comment]
> En is dat dan alleen voor de frontend of ook voor de database?
Voor de database.

**Comment by Helloitsme** [comment]
is het ook mogelijk om ook voor stroom er een (stacked) bar van te maken? vooral in het archief (maand) overzicht zou dit handig zijn want nu heb ik 2 lijn grafieken: voor laag en hoog tarief, maar daardoor kan je het totaalverbruik van een dag niet makkelijk zien. met een stacked bar (of een stacked line / area) kan je dat wel

**Comment by dennissiemensma** [comment]
@Helloitsme ik denk dat je hier het beste een apart issue voor kan maken. Dan kijk ik tzt wat mogelijk is.
