### ISSUE TITLE
Dropbox App: een DSMR app in plaats van allemaal een eigen app

### ISSUE THREAD

**Issue by tomkooij** [dennissiemensma/dsmr-reader#843]
Dropbox sync is nu (IMHO) onnodig moeilijk omdat we allemaal een aparte "eigen" Dropbox App maken als developer. Je kunt ook niet de naam "DSMR" of "DSMRreader" kiezen want die hebben anderen al.

Groot nadeel van deze methode vind ik dat je dan een "development" app maakt, die niet in de normale Dropbox gebruikersinterface te vinden is. Als je ooit weer eens in Dropbox aan het klikken bent, kun je de DSMR app niet terug vinden.

Hoe het -volgens mij- zou moeten:
 - @dennissiemensma maakt de app DSMR (oid) aan in Dropbox zoals het nu in de docs staat.
 - "Enable additional users" wordt [aangezet](https://www.dropbox.com/developers/reference/developer-guide#production-approval), details van de app komen in de docs van dsmrreader.
 - Wij melden ons aan via die app.
 - Bij genoeg gebruikers kan @dennissiemensma de app van "development" naar "production" promoveren. Er is dan een "echte" app, die alle gebruikers kunnen kiezen in de normale dropbox webinterface.

**Comment by dennissiemensma** [comment]
Bedankt voor je input. Het klopt dat de huidige manier van instellen niet handig is. Idealiter zou ik hier gewoon OAuth of iets voor gebruiken.

Het punt is dat ik eigenlijk zo min mogelijk energie wil steken in backup's, omdat ze puur voortkomen uit SD-kaartjes die corrupt raken. Daardoor is het ooit een workaround geweest om de gegevens soort van veilig te stellen via Dropbox. 
Maar het is een hoop gedoe om het goed te krijgen, helemaal qua foutafhandeling en roteren. En inmiddels zijn er ook gebruikers die vanzelfsprekend geen Dropbox hebben, maar OneDrive of Google Drive. Ik heb besloten om daar voor nu ook niets mee te doen, omdat het een behoorlijke lap aan code en onderhoud is om dat goed te krijgen.

Wat betreft de Dropbox Apps, als ik het goed begrijp is dat meer bedoeld als externe service, want de OAuth URL moet ergens naar toewijzen. En hoewel ik het wel overwogen heb, wil ik liever geen centrale server hosten die toegang heeft tot de gegevens van gebruikers, ook al staan er geen persoonsgegevens in.

Daarom ben ik afgestapt van het advies qua om te gebruiken Raspberry Pi's voor dit project. Het werkt er prima op, maar de SD-kaart is iets wat ik softwarematig nooit betrouwbaar krijg. Ik ben er nog niet helemaal uit wat de beste oplossing is.
