### ISSUE TITLE
Wachtwoord voor de gehele interface

### ISSUE THREAD

**Issue by powergrim** [dennissiemensma/dsmr-reader#845]
Op dit moment gebruik ik DSMR reader voor realtime inzicht in verbruikt en logging. Net zoals we dat allemaal doen. Echter wil ik dit overal, en altijd kunnen inzien. Ik zou dit kunnen oplossen met een VPN. Maar een LetsEncrypt certificaatje en een forward naar buiten toe en zodoende mijn verbruik op mijn telefoon kunnen zien is nog iets leuker. Is er een optie toe te voegen dat de gehele interface achter username en PW zit, en niet alleen de admin-interface. Het is niet geheel hackerproof, maar dan kan de gemiddelde inbreker in ieder geval niet zomaar op basis van energieverbruik aanwezigheid bepalen van het huis.

**Comment by dennissiemensma** [comment]
Bedankt voor je vraag. 

Er staat hier meer informatie gedocumenteerd over hoe je dat kunt doen: https://dsmr-reader.readthedocs.io/nl/v3/application.html#public-webinterface-warning
